# TCL File Generated by Component Editor 23.3
# Fri May 24 18:11:42 IST 2024
# DO NOT MODIFY


# 
# radio_config "radio_config" v1.0
#  2024.05.24.18:11:42
# 
# 

# 
# request TCL package from ACDS 23.3
# 
package require -exact qsys 23.3


# 
# module radio_config
# 
set_module_property DESCRIPTION ""
set_module_property NAME radio_config
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME radio_config
set_module_property DATASHEET_URL false
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL radio_config
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file struct_typedef.sv SYSTEM_VERILOG PATH ../common/struct_typedef.sv
add_fileset_file radio_config.sv SYSTEM_VERILOG PATH radio_config.sv TOP_LEVEL_FILE
add_fileset_file def_param.vh OTHER PATH ../common/def_param.vh

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL radio_config
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file struct_typedef.sv SYSTEM_VERILOG PATH ../common/struct_typedef.sv
add_fileset_file radio_config.sv SYSTEM_VERILOG PATH radio_config.sv
add_fileset_file def_param.vh OTHER PATH ../common/def_param.vh


# 
# documentation links
# 
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/pheeps_peak/IN-PhippsPeak/designs/lib/qsys_comp/false


# 
# parameters
# 


# 
# display items
# 


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressGroup 0
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock_csr
set_interface_property csr associatedReset reset_csr_n
set_interface_property csr bitsPerSymbol 8
set_interface_property csr bridgedAddressOffset ""
set_interface_property csr bridgesToMaster ""
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr minimumResponseLatency 1
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr transparentBridge false
set_interface_property csr waitrequestAllowance 0
set_interface_property csr writeWaitTime 0
set_interface_property csr dfhFeatureGuid 0
set_interface_property csr dfhGroupId 0
set_interface_property csr dfhParameterId ""
set_interface_property csr dfhParameterName ""
set_interface_property csr dfhParameterVersion ""
set_interface_property csr dfhParameterData ""
set_interface_property csr dfhParameterDataLength ""
set_interface_property csr dfhFeatureMajorVersion 0
set_interface_property csr dfhFeatureMinorVersion 0
set_interface_property csr dfhFeatureId 35
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""
set_interface_property csr IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property csr SV_INTERFACE_TYPE ""
set_interface_property csr SV_INTERFACE_MODPORT_TYPE ""

add_interface_port csr csr_address address Input 7
add_interface_port csr csr_write write Input 1
add_interface_port csr csr_writedata writedata Input 32
add_interface_port csr csr_readdata readdata Output 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_dsp
# 
add_interface clock_dsp clock end
set_interface_property clock_dsp ENABLED true
set_interface_property clock_dsp EXPORT_OF ""
set_interface_property clock_dsp PORT_NAME_MAP ""
set_interface_property clock_dsp CMSIS_SVD_VARIABLES ""
set_interface_property clock_dsp SVD_ADDRESS_GROUP ""
set_interface_property clock_dsp IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock_dsp SV_INTERFACE_TYPE ""
set_interface_property clock_dsp SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock_dsp clk_dsp clk Input 1


# 
# connection point clock_csr
# 
add_interface clock_csr clock end
set_interface_property clock_csr ENABLED true
set_interface_property clock_csr EXPORT_OF ""
set_interface_property clock_csr PORT_NAME_MAP ""
set_interface_property clock_csr CMSIS_SVD_VARIABLES ""
set_interface_property clock_csr SVD_ADDRESS_GROUP ""
set_interface_property clock_csr IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock_csr SV_INTERFACE_TYPE ""
set_interface_property clock_csr SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock_csr clk_csr clk Input 1


# 
# connection point clock_eth
# 
add_interface clock_eth clock end
set_interface_property clock_eth ENABLED true
set_interface_property clock_eth EXPORT_OF ""
set_interface_property clock_eth PORT_NAME_MAP ""
set_interface_property clock_eth CMSIS_SVD_VARIABLES ""
set_interface_property clock_eth SVD_ADDRESS_GROUP ""
set_interface_property clock_eth IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock_eth SV_INTERFACE_TYPE ""
set_interface_property clock_eth SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock_eth clk_eth clk Input 1


# 
# connection point reset_csr_n
# 
add_interface reset_csr_n reset end
set_interface_property reset_csr_n associatedClock clock_csr
set_interface_property reset_csr_n synchronousEdges DEASSERT
set_interface_property reset_csr_n ENABLED true
set_interface_property reset_csr_n EXPORT_OF ""
set_interface_property reset_csr_n PORT_NAME_MAP ""
set_interface_property reset_csr_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_csr_n SVD_ADDRESS_GROUP ""
set_interface_property reset_csr_n IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset_csr_n SV_INTERFACE_TYPE ""
set_interface_property reset_csr_n SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset_csr_n rst_csr_n reset_n Input 1


# 
# connection point reset_dsp_n
# 
add_interface reset_dsp_n reset end
set_interface_property reset_dsp_n associatedClock clock_dsp
set_interface_property reset_dsp_n synchronousEdges DEASSERT
set_interface_property reset_dsp_n ENABLED true
set_interface_property reset_dsp_n EXPORT_OF ""
set_interface_property reset_dsp_n PORT_NAME_MAP ""
set_interface_property reset_dsp_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_dsp_n SVD_ADDRESS_GROUP ""
set_interface_property reset_dsp_n IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset_dsp_n SV_INTERFACE_TYPE ""
set_interface_property reset_dsp_n SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset_dsp_n rst_dsp_n reset_n Input 1


# 
# connection point reset_eth_n
# 
add_interface reset_eth_n reset end
set_interface_property reset_eth_n associatedClock clock_eth
set_interface_property reset_eth_n synchronousEdges DEASSERT
set_interface_property reset_eth_n ENABLED true
set_interface_property reset_eth_n EXPORT_OF ""
set_interface_property reset_eth_n PORT_NAME_MAP ""
set_interface_property reset_eth_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_eth_n SVD_ADDRESS_GROUP ""
set_interface_property reset_eth_n IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset_eth_n SV_INTERFACE_TYPE ""
set_interface_property reset_eth_n SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset_eth_n rst_eth_n reset_n Input 1


# 
# connection point frame_status
# 
add_interface frame_status conduit end
set_interface_property frame_status associatedClock ""
set_interface_property frame_status associatedReset ""
set_interface_property frame_status ENABLED true
set_interface_property frame_status EXPORT_OF ""
set_interface_property frame_status PORT_NAME_MAP ""
set_interface_property frame_status CMSIS_SVD_VARIABLES ""
set_interface_property frame_status SVD_ADDRESS_GROUP ""
set_interface_property frame_status IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property frame_status SV_INTERFACE_TYPE ""
set_interface_property frame_status SV_INTERFACE_MODPORT_TYPE ""

add_interface_port frame_status frame_status radio_config_status Output 68


# 
# connection point auxN_tx_rfp
# 
add_interface auxN_tx_rfp conduit end
set_interface_property auxN_tx_rfp associatedClock ""
set_interface_property auxN_tx_rfp associatedReset ""
set_interface_property auxN_tx_rfp ENABLED true
set_interface_property auxN_tx_rfp EXPORT_OF ""
set_interface_property auxN_tx_rfp PORT_NAME_MAP ""
set_interface_property auxN_tx_rfp CMSIS_SVD_VARIABLES ""
set_interface_property auxN_tx_rfp SVD_ADDRESS_GROUP ""
set_interface_property auxN_tx_rfp IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property auxN_tx_rfp SV_INTERFACE_TYPE ""
set_interface_property auxN_tx_rfp SV_INTERFACE_MODPORT_TYPE ""

add_interface_port auxN_tx_rfp auxN_tx_rfp data Input 1


# 
# connection point dl_input_hfn_pulse
# 
add_interface dl_input_hfn_pulse conduit end
set_interface_property dl_input_hfn_pulse associatedClock ""
set_interface_property dl_input_hfn_pulse associatedReset ""
set_interface_property dl_input_hfn_pulse ENABLED true
set_interface_property dl_input_hfn_pulse EXPORT_OF ""
set_interface_property dl_input_hfn_pulse PORT_NAME_MAP ""
set_interface_property dl_input_hfn_pulse CMSIS_SVD_VARIABLES ""
set_interface_property dl_input_hfn_pulse SVD_ADDRESS_GROUP ""
set_interface_property dl_input_hfn_pulse IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property dl_input_hfn_pulse SV_INTERFACE_TYPE ""
set_interface_property dl_input_hfn_pulse SV_INTERFACE_MODPORT_TYPE ""

add_interface_port dl_input_hfn_pulse dl_input_hfn_pulse dl_input_hfn_pulse Output 1


# 
# connection point ul_input_hfn_pulse
# 
add_interface ul_input_hfn_pulse conduit end
set_interface_property ul_input_hfn_pulse associatedClock ""
set_interface_property ul_input_hfn_pulse associatedReset ""
set_interface_property ul_input_hfn_pulse ENABLED true
set_interface_property ul_input_hfn_pulse EXPORT_OF ""
set_interface_property ul_input_hfn_pulse PORT_NAME_MAP ""
set_interface_property ul_input_hfn_pulse CMSIS_SVD_VARIABLES ""
set_interface_property ul_input_hfn_pulse SVD_ADDRESS_GROUP ""
set_interface_property ul_input_hfn_pulse IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property ul_input_hfn_pulse SV_INTERFACE_TYPE ""
set_interface_property ul_input_hfn_pulse SV_INTERFACE_MODPORT_TYPE ""

add_interface_port ul_input_hfn_pulse ul_input_hfn_pulse ul_input_hfn_pulse Output 1


# 
# connection point lte_sfn_sf
# 
add_interface lte_sfn_sf conduit end
set_interface_property lte_sfn_sf associatedClock ""
set_interface_property lte_sfn_sf associatedReset ""
set_interface_property lte_sfn_sf ENABLED true
set_interface_property lte_sfn_sf EXPORT_OF ""
set_interface_property lte_sfn_sf PORT_NAME_MAP ""
set_interface_property lte_sfn_sf CMSIS_SVD_VARIABLES ""
set_interface_property lte_sfn_sf SVD_ADDRESS_GROUP ""
set_interface_property lte_sfn_sf IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property lte_sfn_sf SV_INTERFACE_TYPE ""
set_interface_property lte_sfn_sf SV_INTERFACE_MODPORT_TYPE ""

add_interface_port lte_sfn_sf lte_sfn_sf lte_sfn_sf Output 14


# 
# connection point rst_soft_n
# 
add_interface rst_soft_n conduit end
set_interface_property rst_soft_n associatedClock ""
set_interface_property rst_soft_n associatedReset ""
set_interface_property rst_soft_n ENABLED true
set_interface_property rst_soft_n EXPORT_OF ""
set_interface_property rst_soft_n PORT_NAME_MAP ""
set_interface_property rst_soft_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_soft_n SVD_ADDRESS_GROUP ""
set_interface_property rst_soft_n IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst_soft_n SV_INTERFACE_TYPE ""
set_interface_property rst_soft_n SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst_soft_n rst_soft_n rst_soft_n Output 1


# 
# connection point ul_req_disable
# 
add_interface ul_req_disable conduit end
set_interface_property ul_req_disable associatedClock ""
set_interface_property ul_req_disable associatedReset ""
set_interface_property ul_req_disable ENABLED true
set_interface_property ul_req_disable EXPORT_OF ""
set_interface_property ul_req_disable PORT_NAME_MAP ""
set_interface_property ul_req_disable CMSIS_SVD_VARIABLES ""
set_interface_property ul_req_disable SVD_ADDRESS_GROUP ""
set_interface_property ul_req_disable IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property ul_req_disable SV_INTERFACE_TYPE ""
set_interface_property ul_req_disable SV_INTERFACE_MODPORT_TYPE ""

add_interface_port ul_req_disable ul_req_disable ul_req_disable Output 1


# 
# connection point bw_config_cc1
# 
add_interface bw_config_cc1 conduit end
set_interface_property bw_config_cc1 associatedClock ""
set_interface_property bw_config_cc1 associatedReset ""
set_interface_property bw_config_cc1 ENABLED true
set_interface_property bw_config_cc1 EXPORT_OF ""
set_interface_property bw_config_cc1 PORT_NAME_MAP ""
set_interface_property bw_config_cc1 CMSIS_SVD_VARIABLES ""
set_interface_property bw_config_cc1 SVD_ADDRESS_GROUP ""
set_interface_property bw_config_cc1 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property bw_config_cc1 SV_INTERFACE_TYPE ""
set_interface_property bw_config_cc1 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port bw_config_cc1 bw_config_cc1 bw_config_cc1 Output 8


# 
# connection point bw_config_cc2
# 
add_interface bw_config_cc2 conduit end
set_interface_property bw_config_cc2 associatedClock ""
set_interface_property bw_config_cc2 associatedReset ""
set_interface_property bw_config_cc2 ENABLED true
set_interface_property bw_config_cc2 EXPORT_OF ""
set_interface_property bw_config_cc2 PORT_NAME_MAP ""
set_interface_property bw_config_cc2 CMSIS_SVD_VARIABLES ""
set_interface_property bw_config_cc2 SVD_ADDRESS_GROUP ""
set_interface_property bw_config_cc2 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property bw_config_cc2 SV_INTERFACE_TYPE ""
set_interface_property bw_config_cc2 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port bw_config_cc2 bw_config_cc2 bw_config_cc2 Output 8


# 
# connection point ul_eaxc_id_intr
# 
add_interface ul_eaxc_id_intr conduit end
set_interface_property ul_eaxc_id_intr associatedClock ""
set_interface_property ul_eaxc_id_intr associatedReset ""
set_interface_property ul_eaxc_id_intr ENABLED true
set_interface_property ul_eaxc_id_intr EXPORT_OF ""
set_interface_property ul_eaxc_id_intr PORT_NAME_MAP ""
set_interface_property ul_eaxc_id_intr CMSIS_SVD_VARIABLES ""
set_interface_property ul_eaxc_id_intr SVD_ADDRESS_GROUP ""
set_interface_property ul_eaxc_id_intr IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property ul_eaxc_id_intr SV_INTERFACE_TYPE ""
set_interface_property ul_eaxc_id_intr SV_INTERFACE_MODPORT_TYPE ""

add_interface_port ul_eaxc_id_intr ul_axc_id_intr ul_axc_id_intr Input 1


# 
# connection point dl_axc_id_intr
# 
add_interface dl_axc_id_intr conduit end
set_interface_property dl_axc_id_intr associatedClock ""
set_interface_property dl_axc_id_intr associatedReset ""
set_interface_property dl_axc_id_intr ENABLED true
set_interface_property dl_axc_id_intr EXPORT_OF ""
set_interface_property dl_axc_id_intr PORT_NAME_MAP ""
set_interface_property dl_axc_id_intr CMSIS_SVD_VARIABLES ""
set_interface_property dl_axc_id_intr SVD_ADDRESS_GROUP ""
set_interface_property dl_axc_id_intr IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property dl_axc_id_intr SV_INTERFACE_TYPE ""
set_interface_property dl_axc_id_intr SV_INTERFACE_MODPORT_TYPE ""

add_interface_port dl_axc_id_intr dl_axc_id_intr dl_axc_id_intr Input 1


# 
# connection point ul_rtc_id_intr
# 
add_interface ul_rtc_id_intr conduit end
set_interface_property ul_rtc_id_intr associatedClock ""
set_interface_property ul_rtc_id_intr associatedReset ""
set_interface_property ul_rtc_id_intr ENABLED true
set_interface_property ul_rtc_id_intr EXPORT_OF ""
set_interface_property ul_rtc_id_intr PORT_NAME_MAP ""
set_interface_property ul_rtc_id_intr CMSIS_SVD_VARIABLES ""
set_interface_property ul_rtc_id_intr SVD_ADDRESS_GROUP ""
set_interface_property ul_rtc_id_intr IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property ul_rtc_id_intr SV_INTERFACE_TYPE ""
set_interface_property ul_rtc_id_intr SV_INTERFACE_MODPORT_TYPE ""

add_interface_port ul_rtc_id_intr ul_rtc_id_intr ul_rtc_id_intr Input 1


# 
# connection point cu_coupling_status
# 
add_interface cu_coupling_status conduit end
set_interface_property cu_coupling_status associatedClock ""
set_interface_property cu_coupling_status associatedReset ""
set_interface_property cu_coupling_status ENABLED true
set_interface_property cu_coupling_status EXPORT_OF ""
set_interface_property cu_coupling_status PORT_NAME_MAP ""
set_interface_property cu_coupling_status CMSIS_SVD_VARIABLES ""
set_interface_property cu_coupling_status SVD_ADDRESS_GROUP ""
set_interface_property cu_coupling_status IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property cu_coupling_status SV_INTERFACE_TYPE ""
set_interface_property cu_coupling_status SV_INTERFACE_MODPORT_TYPE ""

add_interface_port cu_coupling_status cu_coupling_status cu_coupling_status Input 32


# 
# connection point cu_coupling_version
# 
add_interface cu_coupling_version conduit end
set_interface_property cu_coupling_version associatedClock ""
set_interface_property cu_coupling_version associatedReset ""
set_interface_property cu_coupling_version ENABLED true
set_interface_property cu_coupling_version EXPORT_OF ""
set_interface_property cu_coupling_version PORT_NAME_MAP ""
set_interface_property cu_coupling_version CMSIS_SVD_VARIABLES ""
set_interface_property cu_coupling_version SVD_ADDRESS_GROUP ""
set_interface_property cu_coupling_version IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property cu_coupling_version SV_INTERFACE_TYPE ""
set_interface_property cu_coupling_version SV_INTERFACE_MODPORT_TYPE ""

add_interface_port cu_coupling_version cu_coupling_version cu_coupling_version Input 32


# 
# connection point coupling_err_clear
# 
add_interface coupling_err_clear conduit end
set_interface_property coupling_err_clear associatedClock ""
set_interface_property coupling_err_clear associatedReset ""
set_interface_property coupling_err_clear ENABLED true
set_interface_property coupling_err_clear EXPORT_OF ""
set_interface_property coupling_err_clear PORT_NAME_MAP ""
set_interface_property coupling_err_clear CMSIS_SVD_VARIABLES ""
set_interface_property coupling_err_clear SVD_ADDRESS_GROUP ""
set_interface_property coupling_err_clear IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property coupling_err_clear SV_INTERFACE_TYPE ""
set_interface_property coupling_err_clear SV_INTERFACE_MODPORT_TYPE ""

add_interface_port coupling_err_clear coupling_err_clear coupling_err_clear Output 1


# 
# connection point loopback_enable
# 
add_interface loopback_enable conduit end
set_interface_property loopback_enable associatedClock ""
set_interface_property loopback_enable associatedReset ""
set_interface_property loopback_enable ENABLED true
set_interface_property loopback_enable EXPORT_OF ""
set_interface_property loopback_enable PORT_NAME_MAP ""
set_interface_property loopback_enable CMSIS_SVD_VARIABLES ""
set_interface_property loopback_enable SVD_ADDRESS_GROUP ""
set_interface_property loopback_enable IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property loopback_enable SV_INTERFACE_TYPE ""
set_interface_property loopback_enable SV_INTERFACE_MODPORT_TYPE ""

add_interface_port loopback_enable loopback_enable loopback_enable Output 2


# 
# connection point short_long_prach_sel
# 
add_interface short_long_prach_sel conduit end
set_interface_property short_long_prach_sel associatedClock ""
set_interface_property short_long_prach_sel associatedReset ""
set_interface_property short_long_prach_sel ENABLED true
set_interface_property short_long_prach_sel EXPORT_OF ""
set_interface_property short_long_prach_sel PORT_NAME_MAP ""
set_interface_property short_long_prach_sel CMSIS_SVD_VARIABLES ""
set_interface_property short_long_prach_sel SVD_ADDRESS_GROUP ""
set_interface_property short_long_prach_sel IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property short_long_prach_sel SV_INTERFACE_TYPE ""
set_interface_property short_long_prach_sel SV_INTERFACE_MODPORT_TYPE ""

add_interface_port short_long_prach_sel short_long_prach_select short_long_prach_sel Input 1


# 
# connection point timeout_cntr_intr_cplane
# 
add_interface timeout_cntr_intr_cplane conduit end
set_interface_property timeout_cntr_intr_cplane associatedClock ""
set_interface_property timeout_cntr_intr_cplane associatedReset ""
set_interface_property timeout_cntr_intr_cplane ENABLED true
set_interface_property timeout_cntr_intr_cplane EXPORT_OF ""
set_interface_property timeout_cntr_intr_cplane PORT_NAME_MAP ""
set_interface_property timeout_cntr_intr_cplane CMSIS_SVD_VARIABLES ""
set_interface_property timeout_cntr_intr_cplane SVD_ADDRESS_GROUP ""
set_interface_property timeout_cntr_intr_cplane IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property timeout_cntr_intr_cplane SV_INTERFACE_TYPE ""
set_interface_property timeout_cntr_intr_cplane SV_INTERFACE_MODPORT_TYPE ""

add_interface_port timeout_cntr_intr_cplane timeout_cntr_intr_cplane timeout_cntr_intr_cplane Input 1


# 
# connection point timeout_cntr_intr_uplane
# 
add_interface timeout_cntr_intr_uplane conduit end
set_interface_property timeout_cntr_intr_uplane associatedClock ""
set_interface_property timeout_cntr_intr_uplane associatedReset ""
set_interface_property timeout_cntr_intr_uplane ENABLED true
set_interface_property timeout_cntr_intr_uplane EXPORT_OF ""
set_interface_property timeout_cntr_intr_uplane PORT_NAME_MAP ""
set_interface_property timeout_cntr_intr_uplane CMSIS_SVD_VARIABLES ""
set_interface_property timeout_cntr_intr_uplane SVD_ADDRESS_GROUP ""
set_interface_property timeout_cntr_intr_uplane IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property timeout_cntr_intr_uplane SV_INTERFACE_TYPE ""
set_interface_property timeout_cntr_intr_uplane SV_INTERFACE_MODPORT_TYPE ""

add_interface_port timeout_cntr_intr_uplane timeout_cntr_intr_uplane timeout_cntr_intr_uplane Input 1


# 
# connection point timeout_cntr_intr_clear
# 
add_interface timeout_cntr_intr_clear conduit end
set_interface_property timeout_cntr_intr_clear associatedClock ""
set_interface_property timeout_cntr_intr_clear associatedReset ""
set_interface_property timeout_cntr_intr_clear ENABLED true
set_interface_property timeout_cntr_intr_clear EXPORT_OF ""
set_interface_property timeout_cntr_intr_clear PORT_NAME_MAP ""
set_interface_property timeout_cntr_intr_clear CMSIS_SVD_VARIABLES ""
set_interface_property timeout_cntr_intr_clear SVD_ADDRESS_GROUP ""
set_interface_property timeout_cntr_intr_clear IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property timeout_cntr_intr_clear SV_INTERFACE_TYPE ""
set_interface_property timeout_cntr_intr_clear SV_INTERFACE_MODPORT_TYPE ""

add_interface_port timeout_cntr_intr_clear timeout_cntr_intr_clear timeout_cntr_intr_clear Output 2


# 
# connection point timeout_cntr_intr_mask
# 
add_interface timeout_cntr_intr_mask conduit end
set_interface_property timeout_cntr_intr_mask associatedClock ""
set_interface_property timeout_cntr_intr_mask associatedReset ""
set_interface_property timeout_cntr_intr_mask ENABLED true
set_interface_property timeout_cntr_intr_mask EXPORT_OF ""
set_interface_property timeout_cntr_intr_mask PORT_NAME_MAP ""
set_interface_property timeout_cntr_intr_mask CMSIS_SVD_VARIABLES ""
set_interface_property timeout_cntr_intr_mask SVD_ADDRESS_GROUP ""
set_interface_property timeout_cntr_intr_mask IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property timeout_cntr_intr_mask SV_INTERFACE_TYPE ""
set_interface_property timeout_cntr_intr_mask SV_INTERFACE_MODPORT_TYPE ""

add_interface_port timeout_cntr_intr_mask timeout_cntr_intr_mask timeout_cntr_intr_mask Output 2


# 
# connection point fifo_full_intr_mask
# 
add_interface fifo_full_intr_mask conduit end
set_interface_property fifo_full_intr_mask associatedClock ""
set_interface_property fifo_full_intr_mask associatedReset ""
set_interface_property fifo_full_intr_mask ENABLED true
set_interface_property fifo_full_intr_mask EXPORT_OF ""
set_interface_property fifo_full_intr_mask PORT_NAME_MAP ""
set_interface_property fifo_full_intr_mask CMSIS_SVD_VARIABLES ""
set_interface_property fifo_full_intr_mask SVD_ADDRESS_GROUP ""
set_interface_property fifo_full_intr_mask IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property fifo_full_intr_mask SV_INTERFACE_TYPE ""
set_interface_property fifo_full_intr_mask SV_INTERFACE_MODPORT_TYPE ""

add_interface_port fifo_full_intr_mask fifo_full_intr_mask fifo_full_intr_mask Output 1


# 
# connection point fifo_full_intr_clear
# 
add_interface fifo_full_intr_clear conduit end
set_interface_property fifo_full_intr_clear associatedClock ""
set_interface_property fifo_full_intr_clear associatedReset ""
set_interface_property fifo_full_intr_clear ENABLED true
set_interface_property fifo_full_intr_clear EXPORT_OF ""
set_interface_property fifo_full_intr_clear PORT_NAME_MAP ""
set_interface_property fifo_full_intr_clear CMSIS_SVD_VARIABLES ""
set_interface_property fifo_full_intr_clear SVD_ADDRESS_GROUP ""
set_interface_property fifo_full_intr_clear IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property fifo_full_intr_clear SV_INTERFACE_TYPE ""
set_interface_property fifo_full_intr_clear SV_INTERFACE_MODPORT_TYPE ""

add_interface_port fifo_full_intr_clear fifo_full_intr_clear fifo_full_intr_clear Output 1


# 
# connection point timeout_intr_idle_ms
# 
add_interface timeout_intr_idle_ms conduit end
set_interface_property timeout_intr_idle_ms associatedClock ""
set_interface_property timeout_intr_idle_ms associatedReset ""
set_interface_property timeout_intr_idle_ms ENABLED true
set_interface_property timeout_intr_idle_ms EXPORT_OF ""
set_interface_property timeout_intr_idle_ms PORT_NAME_MAP ""
set_interface_property timeout_intr_idle_ms CMSIS_SVD_VARIABLES ""
set_interface_property timeout_intr_idle_ms SVD_ADDRESS_GROUP ""
set_interface_property timeout_intr_idle_ms IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property timeout_intr_idle_ms SV_INTERFACE_TYPE ""
set_interface_property timeout_intr_idle_ms SV_INTERFACE_MODPORT_TYPE ""

add_interface_port timeout_intr_idle_ms timeout_intr_idle_ms timeout_intr_idle_ms Output 12


# 
# connection point fifo_ful_intr
# 
add_interface fifo_ful_intr conduit end
set_interface_property fifo_ful_intr associatedClock ""
set_interface_property fifo_ful_intr associatedReset ""
set_interface_property fifo_ful_intr ENABLED true
set_interface_property fifo_ful_intr EXPORT_OF ""
set_interface_property fifo_ful_intr PORT_NAME_MAP ""
set_interface_property fifo_ful_intr CMSIS_SVD_VARIABLES ""
set_interface_property fifo_ful_intr SVD_ADDRESS_GROUP ""
set_interface_property fifo_ful_intr IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property fifo_ful_intr SV_INTERFACE_TYPE ""
set_interface_property fifo_ful_intr SV_INTERFACE_MODPORT_TYPE ""

add_interface_port fifo_ful_intr fifo_full_intr fifo_full_intr Input 1


# 
# connection point downlink_eaxc_id_concat
# 
add_interface downlink_eaxc_id_concat conduit end
set_interface_property downlink_eaxc_id_concat associatedClock ""
set_interface_property downlink_eaxc_id_concat associatedReset ""
set_interface_property downlink_eaxc_id_concat ENABLED true
set_interface_property downlink_eaxc_id_concat EXPORT_OF ""
set_interface_property downlink_eaxc_id_concat PORT_NAME_MAP ""
set_interface_property downlink_eaxc_id_concat CMSIS_SVD_VARIABLES ""
set_interface_property downlink_eaxc_id_concat SVD_ADDRESS_GROUP ""
set_interface_property downlink_eaxc_id_concat IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property downlink_eaxc_id_concat SV_INTERFACE_TYPE ""
set_interface_property downlink_eaxc_id_concat SV_INTERFACE_MODPORT_TYPE ""

add_interface_port downlink_eaxc_id_concat downlink_eaxc_id_concat data Output 128


# 
# connection point uplink_eaxc_id_concat
# 
add_interface uplink_eaxc_id_concat conduit end
set_interface_property uplink_eaxc_id_concat associatedClock ""
set_interface_property uplink_eaxc_id_concat associatedReset ""
set_interface_property uplink_eaxc_id_concat ENABLED true
set_interface_property uplink_eaxc_id_concat EXPORT_OF ""
set_interface_property uplink_eaxc_id_concat PORT_NAME_MAP ""
set_interface_property uplink_eaxc_id_concat CMSIS_SVD_VARIABLES ""
set_interface_property uplink_eaxc_id_concat SVD_ADDRESS_GROUP ""
set_interface_property uplink_eaxc_id_concat IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property uplink_eaxc_id_concat SV_INTERFACE_TYPE ""
set_interface_property uplink_eaxc_id_concat SV_INTERFACE_MODPORT_TYPE ""

add_interface_port uplink_eaxc_id_concat uplink_eaxc_id_concat data Output 256


# 
# connection point lphy_ss_conduit_ports_concat
# 
add_interface lphy_ss_conduit_ports_concat conduit end
set_interface_property lphy_ss_conduit_ports_concat associatedClock ""
set_interface_property lphy_ss_conduit_ports_concat associatedReset ""
set_interface_property lphy_ss_conduit_ports_concat ENABLED true
set_interface_property lphy_ss_conduit_ports_concat EXPORT_OF ""
set_interface_property lphy_ss_conduit_ports_concat PORT_NAME_MAP ""
set_interface_property lphy_ss_conduit_ports_concat CMSIS_SVD_VARIABLES ""
set_interface_property lphy_ss_conduit_ports_concat SVD_ADDRESS_GROUP ""
set_interface_property lphy_ss_conduit_ports_concat IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property lphy_ss_conduit_ports_concat SV_INTERFACE_TYPE ""
set_interface_property lphy_ss_conduit_ports_concat SV_INTERFACE_MODPORT_TYPE ""

add_interface_port lphy_ss_conduit_ports_concat lphy_ss_conduit_ports_concat data Output 110


# 
# connection point dspba_cnfg_param_concat
# 
add_interface dspba_cnfg_param_concat conduit end
set_interface_property dspba_cnfg_param_concat associatedClock ""
set_interface_property dspba_cnfg_param_concat associatedReset ""
set_interface_property dspba_cnfg_param_concat ENABLED true
set_interface_property dspba_cnfg_param_concat EXPORT_OF ""
set_interface_property dspba_cnfg_param_concat PORT_NAME_MAP ""
set_interface_property dspba_cnfg_param_concat CMSIS_SVD_VARIABLES ""
set_interface_property dspba_cnfg_param_concat SVD_ADDRESS_GROUP ""
set_interface_property dspba_cnfg_param_concat IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property dspba_cnfg_param_concat SV_INTERFACE_TYPE ""
set_interface_property dspba_cnfg_param_concat SV_INTERFACE_MODPORT_TYPE ""

add_interface_port dspba_cnfg_param_concat dspba_cnfg_param_concat data Output 322

