# TCL File Generated by Component Editor 24.1
# Tue Oct 08 15:01:05 IST 2024
# DO NOT MODIFY


# 
# signal_replicator "signal_replicator" v1.0
#  2024.10.08.15:01:05
# 
# 

# 
# request TCL package from ACDS 24.1
# 
package require -exact qsys 24.1


# 
# module signal_replicator
# 
set_module_property DESCRIPTION ""
set_module_property NAME signal_replicator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME signal_replicator
set_module_property DATASHEET_URL false
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL signal_replicator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file signal_replicator.v VERILOG PATH signal_replicator.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL signal_replicator
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file signal_replicator.v VERILOG PATH signal_replicator.v


# 
# documentation links
# 
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/Phipps_peak_hhsi_mig/IN-PhippsPeak_FPGA/src/ip/custom/phipps_peak/false
add_documentation_link "Data Sheet" file:///mnt/media/Tools/Avinash/Phipps_peak_hhsi_mig/IN-PhippsPeak_FPGA/src/ip/custom/phipps_peak/false
add_documentation_link "Data Sheet" file:///home/avinash/azure/phipps_peak/IN-PhippsPeak_FPGA/src/ip/custom/phipps_peak/false
add_documentation_link "Data Sheet" file:///home/avinash/azure/PP_D2/IN-PhippsPeak_FPGA/fpga/src/ip/custom/phipps_peak/false


# 
# parameters
# 


# 
# display items
# 


# 
# connection point bw_config_cc1
# 
add_interface bw_config_cc1 conduit end
set_interface_property bw_config_cc1 associatedClock ""
set_interface_property bw_config_cc1 associatedReset ""
set_interface_property bw_config_cc1 ENABLED true
set_interface_property bw_config_cc1 EXPORT_OF ""
set_interface_property bw_config_cc1 PORT_NAME_MAP ""
set_interface_property bw_config_cc1 CMSIS_SVD_VARIABLES ""
set_interface_property bw_config_cc1 SVD_ADDRESS_GROUP ""
set_interface_property bw_config_cc1 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property bw_config_cc1 SV_INTERFACE_TYPE ""
set_interface_property bw_config_cc1 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port bw_config_cc1 bw_config_cc1 bw_config_cc1 Input 8


# 
# connection point bw_config_cc2
# 
add_interface bw_config_cc2 conduit end
set_interface_property bw_config_cc2 associatedClock ""
set_interface_property bw_config_cc2 associatedReset ""
set_interface_property bw_config_cc2 ENABLED true
set_interface_property bw_config_cc2 EXPORT_OF ""
set_interface_property bw_config_cc2 PORT_NAME_MAP ""
set_interface_property bw_config_cc2 CMSIS_SVD_VARIABLES ""
set_interface_property bw_config_cc2 SVD_ADDRESS_GROUP ""
set_interface_property bw_config_cc2 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property bw_config_cc2 SV_INTERFACE_TYPE ""
set_interface_property bw_config_cc2 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port bw_config_cc2 bw_config_cc2 bw_config_cc2 Input 8


# 
# connection point radio_config_status
# 
add_interface radio_config_status conduit end
set_interface_property radio_config_status associatedClock ""
set_interface_property radio_config_status associatedReset ""
set_interface_property radio_config_status ENABLED true
set_interface_property radio_config_status EXPORT_OF ""
set_interface_property radio_config_status PORT_NAME_MAP ""
set_interface_property radio_config_status CMSIS_SVD_VARIABLES ""
set_interface_property radio_config_status SVD_ADDRESS_GROUP ""
set_interface_property radio_config_status IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property radio_config_status SV_INTERFACE_TYPE ""
set_interface_property radio_config_status SV_INTERFACE_MODPORT_TYPE ""

add_interface_port radio_config_status radio_config_status radio_config_status Input 56


# 
# connection point short_long_prach_sel
# 
add_interface short_long_prach_sel conduit end
set_interface_property short_long_prach_sel associatedClock ""
set_interface_property short_long_prach_sel associatedReset ""
set_interface_property short_long_prach_sel ENABLED true
set_interface_property short_long_prach_sel EXPORT_OF ""
set_interface_property short_long_prach_sel PORT_NAME_MAP ""
set_interface_property short_long_prach_sel CMSIS_SVD_VARIABLES ""
set_interface_property short_long_prach_sel SVD_ADDRESS_GROUP ""
set_interface_property short_long_prach_sel IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property short_long_prach_sel SV_INTERFACE_TYPE ""
set_interface_property short_long_prach_sel SV_INTERFACE_MODPORT_TYPE ""

add_interface_port short_long_prach_sel short_long_prach_sel short_long_prach_sel Input 1


# 
# connection point bw_config_cc1_dup1
# 
add_interface bw_config_cc1_dup1 conduit end
set_interface_property bw_config_cc1_dup1 associatedClock ""
set_interface_property bw_config_cc1_dup1 associatedReset ""
set_interface_property bw_config_cc1_dup1 ENABLED true
set_interface_property bw_config_cc1_dup1 EXPORT_OF ""
set_interface_property bw_config_cc1_dup1 PORT_NAME_MAP ""
set_interface_property bw_config_cc1_dup1 CMSIS_SVD_VARIABLES ""
set_interface_property bw_config_cc1_dup1 SVD_ADDRESS_GROUP ""
set_interface_property bw_config_cc1_dup1 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property bw_config_cc1_dup1 SV_INTERFACE_TYPE ""
set_interface_property bw_config_cc1_dup1 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port bw_config_cc1_dup1 bw_config_cc1_dup1 bw_config_cc1 Output 8


# 
# connection point bw_config_cc2_dup1
# 
add_interface bw_config_cc2_dup1 conduit end
set_interface_property bw_config_cc2_dup1 associatedClock ""
set_interface_property bw_config_cc2_dup1 associatedReset ""
set_interface_property bw_config_cc2_dup1 ENABLED true
set_interface_property bw_config_cc2_dup1 EXPORT_OF ""
set_interface_property bw_config_cc2_dup1 PORT_NAME_MAP ""
set_interface_property bw_config_cc2_dup1 CMSIS_SVD_VARIABLES ""
set_interface_property bw_config_cc2_dup1 SVD_ADDRESS_GROUP ""
set_interface_property bw_config_cc2_dup1 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property bw_config_cc2_dup1 SV_INTERFACE_TYPE ""
set_interface_property bw_config_cc2_dup1 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port bw_config_cc2_dup1 bw_config_cc2_dup1 bw_config_cc2 Output 8


# 
# connection point radio_config_status_dup1
# 
add_interface radio_config_status_dup1 conduit end
set_interface_property radio_config_status_dup1 associatedClock ""
set_interface_property radio_config_status_dup1 associatedReset ""
set_interface_property radio_config_status_dup1 ENABLED true
set_interface_property radio_config_status_dup1 EXPORT_OF ""
set_interface_property radio_config_status_dup1 PORT_NAME_MAP ""
set_interface_property radio_config_status_dup1 CMSIS_SVD_VARIABLES ""
set_interface_property radio_config_status_dup1 SVD_ADDRESS_GROUP ""
set_interface_property radio_config_status_dup1 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property radio_config_status_dup1 SV_INTERFACE_TYPE ""
set_interface_property radio_config_status_dup1 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port radio_config_status_dup1 radio_config_status_dup1 radio_config_status Output 56


# 
# connection point short_long_prach_sel_dup1
# 
add_interface short_long_prach_sel_dup1 conduit end
set_interface_property short_long_prach_sel_dup1 associatedClock ""
set_interface_property short_long_prach_sel_dup1 associatedReset ""
set_interface_property short_long_prach_sel_dup1 ENABLED true
set_interface_property short_long_prach_sel_dup1 EXPORT_OF ""
set_interface_property short_long_prach_sel_dup1 PORT_NAME_MAP ""
set_interface_property short_long_prach_sel_dup1 CMSIS_SVD_VARIABLES ""
set_interface_property short_long_prach_sel_dup1 SVD_ADDRESS_GROUP ""
set_interface_property short_long_prach_sel_dup1 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property short_long_prach_sel_dup1 SV_INTERFACE_TYPE ""
set_interface_property short_long_prach_sel_dup1 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port short_long_prach_sel_dup1 short_long_prach_sel_dup1 short_long_prach_sel Output 1


# 
# connection point rst_soft_n_dup1
# 
add_interface rst_soft_n_dup1 conduit end
set_interface_property rst_soft_n_dup1 associatedClock ""
set_interface_property rst_soft_n_dup1 associatedReset ""
set_interface_property rst_soft_n_dup1 ENABLED true
set_interface_property rst_soft_n_dup1 EXPORT_OF ""
set_interface_property rst_soft_n_dup1 PORT_NAME_MAP ""
set_interface_property rst_soft_n_dup1 CMSIS_SVD_VARIABLES ""
set_interface_property rst_soft_n_dup1 SVD_ADDRESS_GROUP ""
set_interface_property rst_soft_n_dup1 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst_soft_n_dup1 SV_INTERFACE_TYPE ""
set_interface_property rst_soft_n_dup1 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst_soft_n_dup1 rst_soft_n_dup1 rst_soft_n Output 1


# 
# connection point bw_config_cc1_dup2
# 
add_interface bw_config_cc1_dup2 conduit end
set_interface_property bw_config_cc1_dup2 associatedClock ""
set_interface_property bw_config_cc1_dup2 associatedReset ""
set_interface_property bw_config_cc1_dup2 ENABLED true
set_interface_property bw_config_cc1_dup2 EXPORT_OF ""
set_interface_property bw_config_cc1_dup2 PORT_NAME_MAP ""
set_interface_property bw_config_cc1_dup2 CMSIS_SVD_VARIABLES ""
set_interface_property bw_config_cc1_dup2 SVD_ADDRESS_GROUP ""
set_interface_property bw_config_cc1_dup2 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property bw_config_cc1_dup2 SV_INTERFACE_TYPE ""
set_interface_property bw_config_cc1_dup2 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port bw_config_cc1_dup2 bw_config_cc1_dup2 bw_config_cc1 Output 8


# 
# connection point bw_config_cc2_dup2
# 
add_interface bw_config_cc2_dup2 conduit end
set_interface_property bw_config_cc2_dup2 associatedClock ""
set_interface_property bw_config_cc2_dup2 associatedReset ""
set_interface_property bw_config_cc2_dup2 ENABLED true
set_interface_property bw_config_cc2_dup2 EXPORT_OF ""
set_interface_property bw_config_cc2_dup2 PORT_NAME_MAP ""
set_interface_property bw_config_cc2_dup2 CMSIS_SVD_VARIABLES ""
set_interface_property bw_config_cc2_dup2 SVD_ADDRESS_GROUP ""
set_interface_property bw_config_cc2_dup2 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property bw_config_cc2_dup2 SV_INTERFACE_TYPE ""
set_interface_property bw_config_cc2_dup2 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port bw_config_cc2_dup2 bw_config_cc2_dup2 bw_config_cc2 Output 8


# 
# connection point radio_config_status_dup2
# 
add_interface radio_config_status_dup2 conduit end
set_interface_property radio_config_status_dup2 associatedClock ""
set_interface_property radio_config_status_dup2 associatedReset ""
set_interface_property radio_config_status_dup2 ENABLED true
set_interface_property radio_config_status_dup2 EXPORT_OF ""
set_interface_property radio_config_status_dup2 PORT_NAME_MAP ""
set_interface_property radio_config_status_dup2 CMSIS_SVD_VARIABLES ""
set_interface_property radio_config_status_dup2 SVD_ADDRESS_GROUP ""
set_interface_property radio_config_status_dup2 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property radio_config_status_dup2 SV_INTERFACE_TYPE ""
set_interface_property radio_config_status_dup2 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port radio_config_status_dup2 radio_config_status_dup2 radio_config_status Output 56


# 
# connection point short_long_prach_sel_dup2
# 
add_interface short_long_prach_sel_dup2 conduit end
set_interface_property short_long_prach_sel_dup2 associatedClock ""
set_interface_property short_long_prach_sel_dup2 associatedReset ""
set_interface_property short_long_prach_sel_dup2 ENABLED true
set_interface_property short_long_prach_sel_dup2 EXPORT_OF ""
set_interface_property short_long_prach_sel_dup2 PORT_NAME_MAP ""
set_interface_property short_long_prach_sel_dup2 CMSIS_SVD_VARIABLES ""
set_interface_property short_long_prach_sel_dup2 SVD_ADDRESS_GROUP ""
set_interface_property short_long_prach_sel_dup2 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property short_long_prach_sel_dup2 SV_INTERFACE_TYPE ""
set_interface_property short_long_prach_sel_dup2 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port short_long_prach_sel_dup2 short_long_prach_sel_dup2 short_long_prach_sel Output 1


# 
# connection point rst_soft_n_dup2
# 
add_interface rst_soft_n_dup2 conduit end
set_interface_property rst_soft_n_dup2 associatedClock ""
set_interface_property rst_soft_n_dup2 associatedReset ""
set_interface_property rst_soft_n_dup2 ENABLED true
set_interface_property rst_soft_n_dup2 EXPORT_OF ""
set_interface_property rst_soft_n_dup2 PORT_NAME_MAP ""
set_interface_property rst_soft_n_dup2 CMSIS_SVD_VARIABLES ""
set_interface_property rst_soft_n_dup2 SVD_ADDRESS_GROUP ""
set_interface_property rst_soft_n_dup2 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst_soft_n_dup2 SV_INTERFACE_TYPE ""
set_interface_property rst_soft_n_dup2 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst_soft_n_dup2 rst_soft_n_dup2 rst_soft_n Output 1


# 
# connection point bw_config_cc1_dup3
# 
add_interface bw_config_cc1_dup3 conduit end
set_interface_property bw_config_cc1_dup3 associatedClock ""
set_interface_property bw_config_cc1_dup3 associatedReset ""
set_interface_property bw_config_cc1_dup3 ENABLED true
set_interface_property bw_config_cc1_dup3 EXPORT_OF ""
set_interface_property bw_config_cc1_dup3 PORT_NAME_MAP ""
set_interface_property bw_config_cc1_dup3 CMSIS_SVD_VARIABLES ""
set_interface_property bw_config_cc1_dup3 SVD_ADDRESS_GROUP ""
set_interface_property bw_config_cc1_dup3 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property bw_config_cc1_dup3 SV_INTERFACE_TYPE ""
set_interface_property bw_config_cc1_dup3 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port bw_config_cc1_dup3 bw_config_cc1_dup3 bw_config_cc1 Output 8


# 
# connection point bw_config_cc2_dup3
# 
add_interface bw_config_cc2_dup3 conduit end
set_interface_property bw_config_cc2_dup3 associatedClock ""
set_interface_property bw_config_cc2_dup3 associatedReset ""
set_interface_property bw_config_cc2_dup3 ENABLED true
set_interface_property bw_config_cc2_dup3 EXPORT_OF ""
set_interface_property bw_config_cc2_dup3 PORT_NAME_MAP ""
set_interface_property bw_config_cc2_dup3 CMSIS_SVD_VARIABLES ""
set_interface_property bw_config_cc2_dup3 SVD_ADDRESS_GROUP ""
set_interface_property bw_config_cc2_dup3 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property bw_config_cc2_dup3 SV_INTERFACE_TYPE ""
set_interface_property bw_config_cc2_dup3 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port bw_config_cc2_dup3 bw_config_cc2_dup3 bw_config_cc2 Output 8


# 
# connection point radio_config_status_dup3
# 
add_interface radio_config_status_dup3 conduit end
set_interface_property radio_config_status_dup3 associatedClock ""
set_interface_property radio_config_status_dup3 associatedReset ""
set_interface_property radio_config_status_dup3 ENABLED true
set_interface_property radio_config_status_dup3 EXPORT_OF ""
set_interface_property radio_config_status_dup3 PORT_NAME_MAP ""
set_interface_property radio_config_status_dup3 CMSIS_SVD_VARIABLES ""
set_interface_property radio_config_status_dup3 SVD_ADDRESS_GROUP ""
set_interface_property radio_config_status_dup3 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property radio_config_status_dup3 SV_INTERFACE_TYPE ""
set_interface_property radio_config_status_dup3 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port radio_config_status_dup3 radio_config_status_dup3 data Output 56


# 
# connection point short_long_prach_sel_dup3
# 
add_interface short_long_prach_sel_dup3 conduit end
set_interface_property short_long_prach_sel_dup3 associatedClock ""
set_interface_property short_long_prach_sel_dup3 associatedReset ""
set_interface_property short_long_prach_sel_dup3 ENABLED true
set_interface_property short_long_prach_sel_dup3 EXPORT_OF ""
set_interface_property short_long_prach_sel_dup3 PORT_NAME_MAP ""
set_interface_property short_long_prach_sel_dup3 CMSIS_SVD_VARIABLES ""
set_interface_property short_long_prach_sel_dup3 SVD_ADDRESS_GROUP ""
set_interface_property short_long_prach_sel_dup3 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property short_long_prach_sel_dup3 SV_INTERFACE_TYPE ""
set_interface_property short_long_prach_sel_dup3 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port short_long_prach_sel_dup3 short_long_prach_sel_dup3 short_long_prach_sel Output 1


# 
# connection point rst_soft_n_dup3
# 
add_interface rst_soft_n_dup3 conduit end
set_interface_property rst_soft_n_dup3 associatedClock ""
set_interface_property rst_soft_n_dup3 associatedReset ""
set_interface_property rst_soft_n_dup3 ENABLED true
set_interface_property rst_soft_n_dup3 EXPORT_OF ""
set_interface_property rst_soft_n_dup3 PORT_NAME_MAP ""
set_interface_property rst_soft_n_dup3 CMSIS_SVD_VARIABLES ""
set_interface_property rst_soft_n_dup3 SVD_ADDRESS_GROUP ""
set_interface_property rst_soft_n_dup3 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst_soft_n_dup3 SV_INTERFACE_TYPE ""
set_interface_property rst_soft_n_dup3 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst_soft_n_dup3 rst_soft_n_dup3 rst_soft_n Output 1


# 
# connection point rst_soft_n
# 
add_interface rst_soft_n conduit end
set_interface_property rst_soft_n associatedClock ""
set_interface_property rst_soft_n associatedReset ""
set_interface_property rst_soft_n ENABLED true
set_interface_property rst_soft_n EXPORT_OF ""
set_interface_property rst_soft_n PORT_NAME_MAP ""
set_interface_property rst_soft_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_soft_n SVD_ADDRESS_GROUP ""
set_interface_property rst_soft_n IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst_soft_n SV_INTERFACE_TYPE ""
set_interface_property rst_soft_n SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst_soft_n rst_soft_n rst_soft_n Input 1


# 
# connection point rst_soft_n_dup4
# 
add_interface rst_soft_n_dup4 conduit end
set_interface_property rst_soft_n_dup4 associatedClock ""
set_interface_property rst_soft_n_dup4 associatedReset ""
set_interface_property rst_soft_n_dup4 ENABLED true
set_interface_property rst_soft_n_dup4 EXPORT_OF ""
set_interface_property rst_soft_n_dup4 PORT_NAME_MAP ""
set_interface_property rst_soft_n_dup4 CMSIS_SVD_VARIABLES ""
set_interface_property rst_soft_n_dup4 SVD_ADDRESS_GROUP ""
set_interface_property rst_soft_n_dup4 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst_soft_n_dup4 SV_INTERFACE_TYPE ""
set_interface_property rst_soft_n_dup4 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst_soft_n_dup4 rst_soft_n_dup4 rst_soft_n Output 1


# 
# connection point interface_sel
# 
add_interface interface_sel conduit end
set_interface_property interface_sel associatedClock ""
set_interface_property interface_sel associatedReset ""
set_interface_property interface_sel ENABLED true
set_interface_property interface_sel EXPORT_OF ""
set_interface_property interface_sel PORT_NAME_MAP ""
set_interface_property interface_sel CMSIS_SVD_VARIABLES ""
set_interface_property interface_sel SVD_ADDRESS_GROUP ""
set_interface_property interface_sel IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property interface_sel SV_INTERFACE_TYPE ""
set_interface_property interface_sel SV_INTERFACE_MODPORT_TYPE ""

add_interface_port interface_sel interface_sel data Input 32


# 
# connection point interface_sel_dup1
# 
add_interface interface_sel_dup1 conduit end
set_interface_property interface_sel_dup1 associatedClock ""
set_interface_property interface_sel_dup1 associatedReset ""
set_interface_property interface_sel_dup1 ENABLED true
set_interface_property interface_sel_dup1 EXPORT_OF ""
set_interface_property interface_sel_dup1 PORT_NAME_MAP ""
set_interface_property interface_sel_dup1 CMSIS_SVD_VARIABLES ""
set_interface_property interface_sel_dup1 SVD_ADDRESS_GROUP ""
set_interface_property interface_sel_dup1 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property interface_sel_dup1 SV_INTERFACE_TYPE ""
set_interface_property interface_sel_dup1 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port interface_sel_dup1 interface_sel_dup1 data Output 32


# 
# connection point interface_sel_dup2
# 
add_interface interface_sel_dup2 conduit end
set_interface_property interface_sel_dup2 associatedClock ""
set_interface_property interface_sel_dup2 associatedReset ""
set_interface_property interface_sel_dup2 ENABLED true
set_interface_property interface_sel_dup2 EXPORT_OF ""
set_interface_property interface_sel_dup2 PORT_NAME_MAP ""
set_interface_property interface_sel_dup2 CMSIS_SVD_VARIABLES ""
set_interface_property interface_sel_dup2 SVD_ADDRESS_GROUP ""
set_interface_property interface_sel_dup2 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property interface_sel_dup2 SV_INTERFACE_TYPE ""
set_interface_property interface_sel_dup2 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port interface_sel_dup2 interface_sel_dup2 data Output 32

