// (C) 2001-2024 Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License Subscription 
// Agreement, Intel FPGA IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Intel and sold by 
// Intel or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 2:1 MUX of 1 bit words.  Latency 1.  Select latency 2.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_mux2w1t1s2 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [1:0] din,
    input sel,
    output dout
);

wire [0:0] dout_w;
eth_f_mux2w1t0s2 mx0 (
    .clk(clk),
    .din(din),
    .sel(sel),
    .dout(dout_w)
);
defparam mx0 .SIM_EMULATE = SIM_EMULATE;

reg [0:0] dout_r = 1'b0;
always @(posedge clk) dout_r <= dout_w;
assign dout = dout_r;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "HEQcwkIk4AJUnyybgwol/5f4LNrpC62dnM4HE75Mb8kxROzHwkOVqUjjNakwyQUVn3rWDca7QqKGruQoj2QI6diWrHBuVPm2ePzJYe0opoRKRsrSLsozd6ihfZo7Y4AobDGlA0sx1RWdC2xxmhs6EhsIEYbW0OeABq8z3YlmhZOCNJP7S54htV6uHLAYjjaGmL7pkx5+dyKYUHnNRVlphInbKBlJ9OHWSVdDlWH+1XZ7hk2JxBj0W1Tv4I6GtKBjNfQbidPMD/Le9yoRiS2nKwad9c2doMt8yL36NqrucaX35bgXwUtAvPfjeMZ55RaYF79ND8hJRQa3g8Nn5CSB4+wuVUn8Lh7K+MuqUSgEGhloGW8aBqIjsmGXzEyzu2Ul9Qjqbbx0KbBj+DQZiikrsckmKUlbUoCVCGzKPL9IXssjjG2YAC+CU2GfufKCbTiJ0hcvIbH30BgR5k+p04gy4tcn2Xs0TXJozsq9WAy7YjUssuw2K5DoRRNfgLpVy3UOQ0eGpAj9nCgheM/AOzZSqrBofDQWqZrkZmfGfxpKW8McCYQ/NiVU88fZuh9eJ2udzLOO8xWd1UdD8GXeAFxJoAhUYCXf43Qh5NkLdcgUpL8GL0vckj8MexCmp6oVi57QEOCIqHRdbsAZWI3A+rMvvVO9yOSmiMp+PAPV5RasL3pTIvx/UbTKnmR6fVgauV/4jq6BuXkj0WVnzYlh078VsoFeVTCzz7hIgvNKHar3vLgHJeqPx20VINbq03rNuBCvfUqA+BhI+Ld4NAHby3QK1wvXXq5VTBUXm2n051oHZXgclnv4sJK+jZE2rrKHyzG+ohjPdC4fubfTkjvRKXA1agPVo6Dp1xbZv6Tl4FHXy1kUWVIfbMYMeui4NQCbx8i0uVt+O6KOU+1L1YZ46RKcUJ7WdQBWx7bB1iOaBVIL/jIdo4hfsUz9Q42Vg1BBTets69EjSiwaYpklxTxqjpLSwjJPUHxGOQ8r/FzQhyIVz9lS011Kp9cBN3RkGCk0RK+s"
`endif