// (C) 2001-2024 Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License Subscription 
// Agreement, Intel FPGA IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Intel and sold by 
// Intel or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


`timescale 1ps/1ps

// DESCRIPTION
// 3 input AND gate.  Latency 0.
// Generated by one of Gregg's toys.   Share And Enjoy.

module eth_f_and3t0 #(
    parameter SIM_EMULATE = 1'b0
) (
    input [2:0] din,
    output dout
);

eth_f_lut6 t0 (.din({1'b1,1'b1,1'b1,din}),.dout(dout));
defparam t0 .SIM_EMULATE = SIM_EMULATE;
defparam t0 .MASK = 64'h8000000000000000;

endmodule

`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "HEQcwkIk4AJUnyybgwol/5f4LNrpC62dnM4HE75Mb8kxROzHwkOVqUjjNakwyQUVn3rWDca7QqKGruQoj2QI6diWrHBuVPm2ePzJYe0opoRKRsrSLsozd6ihfZo7Y4AobDGlA0sx1RWdC2xxmhs6EhsIEYbW0OeABq8z3YlmhZOCNJP7S54htV6uHLAYjjaGmL7pkx5+dyKYUHnNRVlphInbKBlJ9OHWSVdDlWH+1XbEFu0zxtzsD6gmHVSDT2M6Xx0YprfQsy8JCX7BvBrKht/5P/wfYEy4PP5CSuOJjlnWpTi8I2mjZXilW3NOyGkhqkVY+837KwXrq+t2AhqY3MWC84TD39sOsz97/EbfaxKvyUVqfjMU9fncoxJ2bT4a5bzQF0oLu2XNHs0vEj1FPHb+2ytvQkHVwPiUWRq+csdy4JhBt9nZPGGQeS0VhLc5yBhkBeuHiP3FV6Q8Sn1Fm3ZZdGj+K3ob20PRjrdpQ2y6U3RaApMZj1lxgsXx3BrV+NHeW0EpTro6/4STzE0bnA7IgR+E3l5Ys07bMVpcyRWOVwUANP87H38RHP73fbrIkdB/x5VMrDoltdMwQS50WKnTi649EBucEipu3VAqdfE3PXznWLyQNj0ypuE8E2QqngNnOBRDpkyrqjq4i/uFeosYsR1jPMNiXd+KB6bLEEcxKgzMbGLCsUrvQ/bAhelbTTSd1/aNA6JtFmyz48vJd09h9FMfTO6pcLcwKEkejWG8x4fdYo44lABS44cSf5cbDcLfvZC7D2D5vsMjz/+foPLBBE3i8FLQbUcod5vKplq+S7TzLhc1E/HqsrYcRACObhszL92g+e0+LwNBtEEWw7RdEYSuoCcJZNYtmdPnHvB5c8SQC9kN6DVsUvrmHYkYyGhVF1J7BggeRjTHVqgvQq8sjS5s5FIjq6P7T4Nm+FxoK0BX35gddvIgtkJHYOOgxpQQIgkAV/duC1EBW5kMB4JHVBHsfy+9w1x2xNqizZeVX+6eq5l5TqTLUI1pXVUa"
`endif