// eth_f_tod_sync_125_to_390p625.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module eth_f_tod_sync_125_to_390p625 #(
		parameter TOD_MODE     = 1,
		parameter SYNC_MODE    = 7,
		parameter SAMPLE_SIZE  = 256,
		parameter PERIOD_NSEC  = 2,
		parameter PERIOD_FNSEC = 36700
	) (
		input  wire        clk_master,      //      clk_master.clk
		input  wire        reset_master,    //    reset_master.reset
		input  wire        clk_slave,       //       clk_slave.clk
		input  wire        reset_slave,     //     reset_slave.reset
		input  wire        clk_sampling,    //    clk_sampling.clk
		input  wire        start_tod_sync,  //  start_tod_sync.data
		input  wire [95:0] tod_master_data, // tod_master_data.data
		output wire [95:0] tod_slave_data,  //  tod_slave_data.data
		output wire        tod_slave_valid  //                .valid
	);

	altera_eth_1588_tod_synchronizer #(
		.TOD_MODE     (TOD_MODE),
		.SYNC_MODE    (SYNC_MODE),
		.SAMPLE_SIZE  (SAMPLE_SIZE),
		.PERIOD_NSEC  (PERIOD_NSEC),
		.PERIOD_FNSEC (PERIOD_FNSEC)
	) eth_f_tod_sync_125_to_390p625 (
		.clk_master      (clk_master),      //   input,   width = 1,      clk_master.clk
		.reset_master    (reset_master),    //   input,   width = 1,    reset_master.reset
		.clk_slave       (clk_slave),       //   input,   width = 1,       clk_slave.clk
		.reset_slave     (reset_slave),     //   input,   width = 1,     reset_slave.reset
		.clk_sampling    (clk_sampling),    //   input,   width = 1,    clk_sampling.clk
		.start_tod_sync  (start_tod_sync),  //   input,   width = 1,  start_tod_sync.data
		.tod_master_data (tod_master_data), //   input,  width = 96, tod_master_data.data
		.tod_slave_data  (tod_slave_data),  //  output,  width = 96,  tod_slave_data.data
		.tod_slave_valid (tod_slave_valid)  //  output,   width = 1,                .valid
	);

endmodule
