// ed_synth_reset_bridge_eth.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module ed_synth_reset_bridge_eth (
		input  wire  clk,         //       clk.clk,     Clock Input
		input  wire  in_reset_n,  //  in_reset.reset_n, Reset Input
		output wire  out_reset_n  // out_reset.reset_n, Reset Output
	);

	assign out_reset_n = in_reset_n;

endmodule
