// dxc_ss_top_duc_model_DUT_0.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module dxc_ss_top_duc_model_DUT_0 (
		input  wire        clk,                  //           clock.clk
		input  wire        areset,               //     clock_reset.reset
		input  wire        bus_clk,              //       bus_clock.clk
		input  wire        bus_areset,           // bus_clock_reset.reset
		input  wire [13:0] busIn_address,        //             bus.address
		input  wire [0:0]  busIn_read,           //                .read
		input  wire [0:0]  busIn_write,          //                .write
		input  wire [31:0] busIn_writedata,      //                .writedata
		output wire [31:0] busOut_readdata,      //                .readdata
		output wire [0:0]  busOut_readdatavalid, //                .readdatavalid
		output wire [0:0]  busOut_waitrequest,   //                .waitrequest
		input  wire [0:0]  DUC_Valid_l1_s,       //             exp.valid_DUC_Valid_l1_s
		input  wire [7:0]  DUC_Chan_l1_s,        //                .channel_DUC_Chan_l1_s
		input  wire [15:0] DUC_Data_l1_im,       //                .data_DUC_Data_l1_im
		input  wire [15:0] DUC_Data_l1_re,       //                .data_DUC_Data_l1_re
		input  wire [0:0]  DUC_NCO_sync_0,       //                .data_DUC_NCO_sync_0
		input  wire [0:0]  DUC_NCO_sync_1,       //                .data_DUC_NCO_sync_1
		input  wire [0:0]  DUC_NCO_sync_2,       //                .data_DUC_NCO_sync_2
		input  wire [0:0]  DUC_NCO_sync_3,       //                .data_DUC_NCO_sync_3
		input  wire [7:0]  BW_Config_CC1_s,      //                .data_BW_Config_CC1_s
		output wire [0:0]  DUC_Valid_Out_s,      //                .valid_DUC_Valid_Out_s
		output wire [7:0]  DUC_Chan_Out_s,       //                .channel_DUC_Chan_Out_s
		output wire [15:0] DUC_Data_Out_0im,     //                .data_DUC_Data_Out_0im
		output wire [15:0] DUC_Data_Out_0re,     //                .data_DUC_Data_Out_0re
		output wire [15:0] DUC_Data_Out_1im,     //                .data_DUC_Data_Out_1im
		output wire [15:0] DUC_Data_Out_1re,     //                .data_DUC_Data_Out_1re
		output wire [15:0] DUC_Data_Out_2im,     //                .data_DUC_Data_Out_2im
		output wire [15:0] DUC_Data_Out_2re,     //                .data_DUC_Data_Out_2re
		output wire [15:0] DUC_Data_Out_3im,     //                .data_DUC_Data_Out_3im
		output wire [15:0] DUC_Data_Out_3re,     //                .data_DUC_Data_Out_3re
		output wire [0:0]  duc_l1_vout_s,        //                .valid_duc_l1_vout_s
		output wire [7:0]  duc_l1_cout_s,        //                .channel_duc_l1_cout_s
		output wire [15:0] duc_l1_dout_0im,      //                .data_duc_l1_dout_0im
		output wire [15:0] duc_l1_dout_0re,      //                .data_duc_l1_dout_0re
		output wire [15:0] duc_l1_dout_1im,      //                .data_duc_l1_dout_1im
		output wire [15:0] duc_l1_dout_1re,      //                .data_duc_l1_dout_1re
		output wire [15:0] duc_l1_dout_2im,      //                .data_duc_l1_dout_2im
		output wire [15:0] duc_l1_dout_2re,      //                .data_duc_l1_dout_2re
		output wire [15:0] duc_l1_dout_3im,      //                .data_duc_l1_dout_3im
		output wire [15:0] duc_l1_dout_3re       //                .data_duc_l1_dout_3re
	);

	duc_model_DUT duc_model_dut_0 (
		.clk                  (clk),                  //   input,   width = 1,           clock.clk
		.areset               (areset),               //   input,   width = 1,     clock_reset.reset
		.bus_clk              (bus_clk),              //   input,   width = 1,       bus_clock.clk
		.bus_areset           (bus_areset),           //   input,   width = 1, bus_clock_reset.reset
		.busIn_address        (busIn_address),        //   input,  width = 14,             bus.address
		.busIn_read           (busIn_read),           //   input,   width = 1,                .read
		.busIn_write          (busIn_write),          //   input,   width = 1,                .write
		.busIn_writedata      (busIn_writedata),      //   input,  width = 32,                .writedata
		.busOut_readdata      (busOut_readdata),      //  output,  width = 32,                .readdata
		.busOut_readdatavalid (busOut_readdatavalid), //  output,   width = 1,                .readdatavalid
		.busOut_waitrequest   (busOut_waitrequest),   //  output,   width = 1,                .waitrequest
		.DUC_Valid_l1_s       (DUC_Valid_l1_s),       //   input,   width = 1,             exp.valid_DUC_Valid_l1_s
		.DUC_Chan_l1_s        (DUC_Chan_l1_s),        //   input,   width = 8,                .channel_DUC_Chan_l1_s
		.DUC_Data_l1_im       (DUC_Data_l1_im),       //   input,  width = 16,                .data_DUC_Data_l1_im
		.DUC_Data_l1_re       (DUC_Data_l1_re),       //   input,  width = 16,                .data_DUC_Data_l1_re
		.DUC_NCO_sync_0       (DUC_NCO_sync_0),       //   input,   width = 1,                .data_DUC_NCO_sync_0
		.DUC_NCO_sync_1       (DUC_NCO_sync_1),       //   input,   width = 1,                .data_DUC_NCO_sync_1
		.DUC_NCO_sync_2       (DUC_NCO_sync_2),       //   input,   width = 1,                .data_DUC_NCO_sync_2
		.DUC_NCO_sync_3       (DUC_NCO_sync_3),       //   input,   width = 1,                .data_DUC_NCO_sync_3
		.BW_Config_CC1_s      (BW_Config_CC1_s),      //   input,   width = 8,                .data_BW_Config_CC1_s
		.DUC_Valid_Out_s      (DUC_Valid_Out_s),      //  output,   width = 1,                .valid_DUC_Valid_Out_s
		.DUC_Chan_Out_s       (DUC_Chan_Out_s),       //  output,   width = 8,                .channel_DUC_Chan_Out_s
		.DUC_Data_Out_0im     (DUC_Data_Out_0im),     //  output,  width = 16,                .data_DUC_Data_Out_0im
		.DUC_Data_Out_0re     (DUC_Data_Out_0re),     //  output,  width = 16,                .data_DUC_Data_Out_0re
		.DUC_Data_Out_1im     (DUC_Data_Out_1im),     //  output,  width = 16,                .data_DUC_Data_Out_1im
		.DUC_Data_Out_1re     (DUC_Data_Out_1re),     //  output,  width = 16,                .data_DUC_Data_Out_1re
		.DUC_Data_Out_2im     (DUC_Data_Out_2im),     //  output,  width = 16,                .data_DUC_Data_Out_2im
		.DUC_Data_Out_2re     (DUC_Data_Out_2re),     //  output,  width = 16,                .data_DUC_Data_Out_2re
		.DUC_Data_Out_3im     (DUC_Data_Out_3im),     //  output,  width = 16,                .data_DUC_Data_Out_3im
		.DUC_Data_Out_3re     (DUC_Data_Out_3re),     //  output,  width = 16,                .data_DUC_Data_Out_3re
		.duc_l1_vout_s        (duc_l1_vout_s),        //  output,   width = 1,                .valid_duc_l1_vout_s
		.duc_l1_cout_s        (duc_l1_cout_s),        //  output,   width = 8,                .channel_duc_l1_cout_s
		.duc_l1_dout_0im      (duc_l1_dout_0im),      //  output,  width = 16,                .data_duc_l1_dout_0im
		.duc_l1_dout_0re      (duc_l1_dout_0re),      //  output,  width = 16,                .data_duc_l1_dout_0re
		.duc_l1_dout_1im      (duc_l1_dout_1im),      //  output,  width = 16,                .data_duc_l1_dout_1im
		.duc_l1_dout_1re      (duc_l1_dout_1re),      //  output,  width = 16,                .data_duc_l1_dout_1re
		.duc_l1_dout_2im      (duc_l1_dout_2im),      //  output,  width = 16,                .data_duc_l1_dout_2im
		.duc_l1_dout_2re      (duc_l1_dout_2re),      //  output,  width = 16,                .data_duc_l1_dout_2re
		.duc_l1_dout_3im      (duc_l1_dout_3im),      //  output,  width = 16,                .data_duc_l1_dout_3im
		.duc_l1_dout_3re      (duc_l1_dout_3re)       //  output,  width = 16,                .data_duc_l1_dout_3re
	);

endmodule
