# (C) 2016-2020 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.

# TCL File Generated by Component Editor 13.1
# Tue Aug 12 18:48:11 CEST 2014
# DO NOT MODIFY


#
# ICON_GEN_ST "ICON_GEN_ST" v2014.8
#  2014.08.12.18:48:11
#
#

#
# request TCL package from ACDS 13.1
#
package require -exact qsys 13.1


#
# module ICON_GEN_ST
#
set_module_property DESCRIPTION ""
set_module_property NAME ICON_GEN_ST
set_module_property VERSION 19.1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Intel Corporation"
set_module_property GROUP "Example Designs/DSP/Video and Image Processing"
set_module_property DISPLAY_NAME "Icon Generator (Intel)"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false

#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ICON_GEN_ST
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ICON_GEN_ST.vhd VHDL PATH ICON_GEN_ST.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ICON_GEN_ST
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ICON_GEN_ST.vhd VHDL PATH ICON_GEN_ST.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL ICON_GEN_ST
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ICON_GEN_ST.vhd VHDL PATH ICON_GEN_ST.vhd


#
# display items
#

#
# connection point avalon_st_clock
#
add_interface avalon_st_clock clock end
set_interface_property avalon_st_clock clockRate 0
set_interface_property avalon_st_clock ENABLED true
set_interface_property avalon_st_clock EXPORT_OF ""
set_interface_property avalon_st_clock PORT_NAME_MAP ""
set_interface_property avalon_st_clock CMSIS_SVD_VARIABLES ""
set_interface_property avalon_st_clock SVD_ADDRESS_GROUP ""

add_interface_port avalon_st_clock VID_CLK clk Input 1

#
# connection point avalon_st_reset
#
add_interface avalon_st_reset reset end
set_interface_property avalon_st_reset associatedClock avalon_st_clock
set_interface_property avalon_st_reset synchronousEdges DEASSERT
set_interface_property avalon_st_reset ENABLED true
set_interface_property avalon_st_reset EXPORT_OF ""
set_interface_property avalon_st_reset PORT_NAME_MAP ""
set_interface_property avalon_st_reset CMSIS_SVD_VARIABLES ""
set_interface_property avalon_st_reset SVD_ADDRESS_GROUP ""

add_interface_port avalon_st_reset VID_RST reset Input 1

#
# connection point avalon_streaming_source
#
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock avalon_st_clock
set_interface_property avalon_streaming_source associatedReset avalon_st_reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 10
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 1
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source VID_RDY ready Input 1
add_interface_port avalon_streaming_source VID_SOP startofpacket Output 1
add_interface_port avalon_streaming_source VID_DAV valid Output 1
add_interface_port avalon_streaming_source VID_DATA data Output 30*2
add_interface_port avalon_streaming_source VID_EOP endofpacket Output 1
