// tod_subsys_tod_timestamp_96b_0.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module tod_subsys_tod_timestamp_96b_0 (
		input  wire         clk_tod,                          //                    clk_tod.clk
		input  wire         rst_clk_tod_n,                    //              rst_clk_tod_n.reset_n
		input  wire         clk_100,                          //                    clk_100.clk
		input  wire         system_reset_n,                   //             system_reset_n.reset_n
		input  wire         pps_in,                           //                     pps_in.pps_in
		output wire         irq_delay_pulse,                  //            irq_delay_pulse.irq
		input  wire [95:0]  eth_tod_master_96b_tx,            //      eth_tod_master_96b_tx.data
		output wire [95:0]  eth_tod_master_96b_tx_load_data,  // eth_tod_master_96b_tx_load.data
		output wire         eth_tod_master_96b_tx_load_valid, //                           .valid
		output wire         rfp_sync_pul,                     //               rfp_sync_pul.data
		output wire         rfp_sync_pul_cpri,                //          rfp_sync_pul_cpri.cpri_aux_rx_rfp_l1_cpri
		input  wire [4:0]   csr_address,                      //      tod_timestamp_96b_csr.address
		input  wire         csr_write,                        //                           .write
		input  wire         csr_read,                         //                           .read
		input  wire [31:0]  csr_writedata,                    //                           .writedata
		output wire [31:0]  csr_readdata,                     //                           .readdata
		output wire         csr_waitrequest,                  //                           .waitrequest
		output wire         csr_readdatavalid,                //                           .readdatavalid
		input  wire         ram_read,                         //          tod_timestamp_mem.read
		output wire [127:0] ram_q,                            //                           .readdata
		output wire         rfp_sync_pul_dup                  //           rfp_sync_pul_dup.data
	);

	tod_timestamp_96b tod_timestamp_96b_0 (
		.clk_tod                          (clk_tod),                          //   input,    width = 1,                    clk_tod.clk
		.rst_clk_tod_n                    (rst_clk_tod_n),                    //   input,    width = 1,              rst_clk_tod_n.reset_n
		.clk_100                          (clk_100),                          //   input,    width = 1,                    clk_100.clk
		.system_reset_n                   (system_reset_n),                   //   input,    width = 1,             system_reset_n.reset_n
		.pps_in                           (pps_in),                           //   input,    width = 1,                     pps_in.pps_in
		.irq_delay_pulse                  (irq_delay_pulse),                  //  output,    width = 1,            irq_delay_pulse.irq
		.eth_tod_master_96b_tx            (eth_tod_master_96b_tx),            //   input,   width = 96,      eth_tod_master_96b_tx.data
		.eth_tod_master_96b_tx_load_data  (eth_tod_master_96b_tx_load_data),  //  output,   width = 96, eth_tod_master_96b_tx_load.data
		.eth_tod_master_96b_tx_load_valid (eth_tod_master_96b_tx_load_valid), //  output,    width = 1,                           .valid
		.rfp_sync_pul                     (rfp_sync_pul),                     //  output,    width = 1,               rfp_sync_pul.data
		.rfp_sync_pul_cpri                (rfp_sync_pul_cpri),                //  output,    width = 1,          rfp_sync_pul_cpri.cpri_aux_rx_rfp_l1_cpri
		.csr_address                      (csr_address),                      //   input,    width = 5,      tod_timestamp_96b_csr.address
		.csr_write                        (csr_write),                        //   input,    width = 1,                           .write
		.csr_read                         (csr_read),                         //   input,    width = 1,                           .read
		.csr_writedata                    (csr_writedata),                    //   input,   width = 32,                           .writedata
		.csr_readdata                     (csr_readdata),                     //  output,   width = 32,                           .readdata
		.csr_waitrequest                  (csr_waitrequest),                  //  output,    width = 1,                           .waitrequest
		.csr_readdatavalid                (csr_readdatavalid),                //  output,    width = 1,                           .readdatavalid
		.ram_read                         (ram_read),                         //   input,    width = 1,          tod_timestamp_mem.read
		.ram_q                            (ram_q),                            //  output,  width = 128,                           .readdata
		.rfp_sync_pul_dup                 (rfp_sync_pul_dup)                  //  output,    width = 1,           rfp_sync_pul_dup.data
	);

endmodule
