// hssi_ss_1_altera_mm_interconnect_1920_ukl2fly.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module hssi_ss_1_altera_mm_interconnect_1920_ukl2fly (
		input  wire [21:0] elane_avalon_anti_slave_0_address,         //         elane_avalon_anti_slave_0.address
		output wire        elane_avalon_anti_slave_0_waitrequest,     //                                  .waitrequest
		input  wire        elane_avalon_anti_slave_0_read,            //                                  .read
		output wire [31:0] elane_avalon_anti_slave_0_readdata,        //                                  .readdata
		output wire        elane_avalon_anti_slave_0_readdatavalid,   //                                  .readdatavalid
		input  wire        elane_avalon_anti_slave_0_write,           //                                  .write
		input  wire [31:0] elane_avalon_anti_slave_0_writedata,       //                                  .writedata
		input  wire [21:0] xcvr_avalon_anti_slave_0_address,          //          xcvr_avalon_anti_slave_0.address
		output wire        xcvr_avalon_anti_slave_0_waitrequest,      //                                  .waitrequest
		input  wire [3:0]  xcvr_avalon_anti_slave_0_byteenable,       //                                  .byteenable
		input  wire        xcvr_avalon_anti_slave_0_begintransfer,    //                                  .begintransfer
		input  wire        xcvr_avalon_anti_slave_0_read,             //                                  .read
		output wire [31:0] xcvr_avalon_anti_slave_0_readdata,         //                                  .readdata
		output wire        xcvr_avalon_anti_slave_0_readdatavalid,    //                                  .readdatavalid
		input  wire        xcvr_avalon_anti_slave_0_write,            //                                  .write
		input  wire [31:0] xcvr_avalon_anti_slave_0_writedata,        //                                  .writedata
		output wire [21:0] master_avalon_anti_master_0_address,       //       master_avalon_anti_master_0.address
		output wire        master_avalon_anti_master_0_write,         //                                  .write
		output wire        master_avalon_anti_master_0_read,          //                                  .read
		input  wire [31:0] master_avalon_anti_master_0_readdata,      //                                  .readdata
		output wire [31:0] master_avalon_anti_master_0_writedata,     //                                  .writedata
		input  wire        master_avalon_anti_master_0_readdatavalid, //                                  .readdatavalid
		input  wire        master_avalon_anti_master_0_waitrequest,   //                                  .waitrequest
		input  wire        elane_reset_reset_bridge_in_reset_reset,   // elane_reset_reset_bridge_in_reset.reset,        Reset Input
		input  wire        clock_in_out_clk_clk                       //                  clock_in_out_clk.clk,          Clock Input
	);

	wire          elane_avalon_anti_slave_0_translator_avalon_universal_master_0_waitrequest;   // elane_avalon_anti_slave_0_agent:av_waitrequest -> elane_avalon_anti_slave_0_translator:uav_waitrequest
	wire   [31:0] elane_avalon_anti_slave_0_translator_avalon_universal_master_0_readdata;      // elane_avalon_anti_slave_0_agent:av_readdata -> elane_avalon_anti_slave_0_translator:uav_readdata
	wire          elane_avalon_anti_slave_0_translator_avalon_universal_master_0_debugaccess;   // elane_avalon_anti_slave_0_translator:uav_debugaccess -> elane_avalon_anti_slave_0_agent:av_debugaccess
	wire   [23:0] elane_avalon_anti_slave_0_translator_avalon_universal_master_0_address;       // elane_avalon_anti_slave_0_translator:uav_address -> elane_avalon_anti_slave_0_agent:av_address
	wire          elane_avalon_anti_slave_0_translator_avalon_universal_master_0_read;          // elane_avalon_anti_slave_0_translator:uav_read -> elane_avalon_anti_slave_0_agent:av_read
	wire    [3:0] elane_avalon_anti_slave_0_translator_avalon_universal_master_0_byteenable;    // elane_avalon_anti_slave_0_translator:uav_byteenable -> elane_avalon_anti_slave_0_agent:av_byteenable
	wire          elane_avalon_anti_slave_0_translator_avalon_universal_master_0_readdatavalid; // elane_avalon_anti_slave_0_agent:av_readdatavalid -> elane_avalon_anti_slave_0_translator:uav_readdatavalid
	wire          elane_avalon_anti_slave_0_translator_avalon_universal_master_0_lock;          // elane_avalon_anti_slave_0_translator:uav_lock -> elane_avalon_anti_slave_0_agent:av_lock
	wire          elane_avalon_anti_slave_0_translator_avalon_universal_master_0_write;         // elane_avalon_anti_slave_0_translator:uav_write -> elane_avalon_anti_slave_0_agent:av_write
	wire   [31:0] elane_avalon_anti_slave_0_translator_avalon_universal_master_0_writedata;     // elane_avalon_anti_slave_0_translator:uav_writedata -> elane_avalon_anti_slave_0_agent:av_writedata
	wire    [2:0] elane_avalon_anti_slave_0_translator_avalon_universal_master_0_burstcount;    // elane_avalon_anti_slave_0_translator:uav_burstcount -> elane_avalon_anti_slave_0_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                            // rsp_mux:src_valid -> elane_avalon_anti_slave_0_agent:rp_valid
	wire  [117:0] rsp_mux_src_data;                                                             // rsp_mux:src_data -> elane_avalon_anti_slave_0_agent:rp_data
	wire          rsp_mux_src_ready;                                                            // elane_avalon_anti_slave_0_agent:rp_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                                          // rsp_mux:src_channel -> elane_avalon_anti_slave_0_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                                    // rsp_mux:src_startofpacket -> elane_avalon_anti_slave_0_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                      // rsp_mux:src_endofpacket -> elane_avalon_anti_slave_0_agent:rp_endofpacket
	wire          xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_waitrequest;    // xcvr_avalon_anti_slave_0_agent:av_waitrequest -> xcvr_avalon_anti_slave_0_translator:uav_waitrequest
	wire   [31:0] xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_readdata;       // xcvr_avalon_anti_slave_0_agent:av_readdata -> xcvr_avalon_anti_slave_0_translator:uav_readdata
	wire          xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_debugaccess;    // xcvr_avalon_anti_slave_0_translator:uav_debugaccess -> xcvr_avalon_anti_slave_0_agent:av_debugaccess
	wire   [23:0] xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_address;        // xcvr_avalon_anti_slave_0_translator:uav_address -> xcvr_avalon_anti_slave_0_agent:av_address
	wire          xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_read;           // xcvr_avalon_anti_slave_0_translator:uav_read -> xcvr_avalon_anti_slave_0_agent:av_read
	wire    [3:0] xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_byteenable;     // xcvr_avalon_anti_slave_0_translator:uav_byteenable -> xcvr_avalon_anti_slave_0_agent:av_byteenable
	wire          xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_readdatavalid;  // xcvr_avalon_anti_slave_0_agent:av_readdatavalid -> xcvr_avalon_anti_slave_0_translator:uav_readdatavalid
	wire          xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_lock;           // xcvr_avalon_anti_slave_0_translator:uav_lock -> xcvr_avalon_anti_slave_0_agent:av_lock
	wire          xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_write;          // xcvr_avalon_anti_slave_0_translator:uav_write -> xcvr_avalon_anti_slave_0_agent:av_write
	wire   [31:0] xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_writedata;      // xcvr_avalon_anti_slave_0_translator:uav_writedata -> xcvr_avalon_anti_slave_0_agent:av_writedata
	wire    [2:0] xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_burstcount;     // xcvr_avalon_anti_slave_0_translator:uav_burstcount -> xcvr_avalon_anti_slave_0_agent:av_burstcount
	wire          rsp_mux_001_src_valid;                                                        // rsp_mux_001:src_valid -> xcvr_avalon_anti_slave_0_agent:rp_valid
	wire  [117:0] rsp_mux_001_src_data;                                                         // rsp_mux_001:src_data -> xcvr_avalon_anti_slave_0_agent:rp_data
	wire          rsp_mux_001_src_ready;                                                        // xcvr_avalon_anti_slave_0_agent:rp_ready -> rsp_mux_001:src_ready
	wire    [1:0] rsp_mux_001_src_channel;                                                      // rsp_mux_001:src_channel -> xcvr_avalon_anti_slave_0_agent:rp_channel
	wire          rsp_mux_001_src_startofpacket;                                                // rsp_mux_001:src_startofpacket -> xcvr_avalon_anti_slave_0_agent:rp_startofpacket
	wire          rsp_mux_001_src_endofpacket;                                                  // rsp_mux_001:src_endofpacket -> xcvr_avalon_anti_slave_0_agent:rp_endofpacket
	wire   [31:0] master_avalon_anti_master_0_agent_m0_readdata;                                // master_avalon_anti_master_0_translator:uav_readdata -> master_avalon_anti_master_0_agent:m0_readdata
	wire          master_avalon_anti_master_0_agent_m0_waitrequest;                             // master_avalon_anti_master_0_translator:uav_waitrequest -> master_avalon_anti_master_0_agent:m0_waitrequest
	wire          master_avalon_anti_master_0_agent_m0_debugaccess;                             // master_avalon_anti_master_0_agent:m0_debugaccess -> master_avalon_anti_master_0_translator:uav_debugaccess
	wire   [23:0] master_avalon_anti_master_0_agent_m0_address;                                 // master_avalon_anti_master_0_agent:m0_address -> master_avalon_anti_master_0_translator:uav_address
	wire    [3:0] master_avalon_anti_master_0_agent_m0_byteenable;                              // master_avalon_anti_master_0_agent:m0_byteenable -> master_avalon_anti_master_0_translator:uav_byteenable
	wire          master_avalon_anti_master_0_agent_m0_read;                                    // master_avalon_anti_master_0_agent:m0_read -> master_avalon_anti_master_0_translator:uav_read
	wire          master_avalon_anti_master_0_agent_m0_readdatavalid;                           // master_avalon_anti_master_0_translator:uav_readdatavalid -> master_avalon_anti_master_0_agent:m0_readdatavalid
	wire          master_avalon_anti_master_0_agent_m0_lock;                                    // master_avalon_anti_master_0_agent:m0_lock -> master_avalon_anti_master_0_translator:uav_lock
	wire   [31:0] master_avalon_anti_master_0_agent_m0_writedata;                               // master_avalon_anti_master_0_agent:m0_writedata -> master_avalon_anti_master_0_translator:uav_writedata
	wire          master_avalon_anti_master_0_agent_m0_write;                                   // master_avalon_anti_master_0_agent:m0_write -> master_avalon_anti_master_0_translator:uav_write
	wire    [2:0] master_avalon_anti_master_0_agent_m0_burstcount;                              // master_avalon_anti_master_0_agent:m0_burstcount -> master_avalon_anti_master_0_translator:uav_burstcount
	wire          master_avalon_anti_master_0_agent_rf_source_valid;                            // master_avalon_anti_master_0_agent:rf_source_valid -> master_avalon_anti_master_0_agent_rsp_fifo:in_valid
	wire  [118:0] master_avalon_anti_master_0_agent_rf_source_data;                             // master_avalon_anti_master_0_agent:rf_source_data -> master_avalon_anti_master_0_agent_rsp_fifo:in_data
	wire          master_avalon_anti_master_0_agent_rf_source_ready;                            // master_avalon_anti_master_0_agent_rsp_fifo:in_ready -> master_avalon_anti_master_0_agent:rf_source_ready
	wire          master_avalon_anti_master_0_agent_rf_source_startofpacket;                    // master_avalon_anti_master_0_agent:rf_source_startofpacket -> master_avalon_anti_master_0_agent_rsp_fifo:in_startofpacket
	wire          master_avalon_anti_master_0_agent_rf_source_endofpacket;                      // master_avalon_anti_master_0_agent:rf_source_endofpacket -> master_avalon_anti_master_0_agent_rsp_fifo:in_endofpacket
	wire          master_avalon_anti_master_0_agent_rsp_fifo_out_valid;                         // master_avalon_anti_master_0_agent_rsp_fifo:out_valid -> master_avalon_anti_master_0_agent:rf_sink_valid
	wire  [118:0] master_avalon_anti_master_0_agent_rsp_fifo_out_data;                          // master_avalon_anti_master_0_agent_rsp_fifo:out_data -> master_avalon_anti_master_0_agent:rf_sink_data
	wire          master_avalon_anti_master_0_agent_rsp_fifo_out_ready;                         // master_avalon_anti_master_0_agent:rf_sink_ready -> master_avalon_anti_master_0_agent_rsp_fifo:out_ready
	wire          master_avalon_anti_master_0_agent_rsp_fifo_out_startofpacket;                 // master_avalon_anti_master_0_agent_rsp_fifo:out_startofpacket -> master_avalon_anti_master_0_agent:rf_sink_startofpacket
	wire          master_avalon_anti_master_0_agent_rsp_fifo_out_endofpacket;                   // master_avalon_anti_master_0_agent_rsp_fifo:out_endofpacket -> master_avalon_anti_master_0_agent:rf_sink_endofpacket
	wire          master_avalon_anti_master_0_agent_rdata_fifo_src_valid;                       // master_avalon_anti_master_0_agent:rdata_fifo_src_valid -> master_avalon_anti_master_0_agent:rdata_fifo_sink_valid
	wire   [33:0] master_avalon_anti_master_0_agent_rdata_fifo_src_data;                        // master_avalon_anti_master_0_agent:rdata_fifo_src_data -> master_avalon_anti_master_0_agent:rdata_fifo_sink_data
	wire          master_avalon_anti_master_0_agent_rdata_fifo_src_ready;                       // master_avalon_anti_master_0_agent:rdata_fifo_sink_ready -> master_avalon_anti_master_0_agent:rdata_fifo_src_ready
	wire          cmd_mux_src_valid;                                                            // cmd_mux:src_valid -> master_avalon_anti_master_0_agent:cp_valid
	wire  [117:0] cmd_mux_src_data;                                                             // cmd_mux:src_data -> master_avalon_anti_master_0_agent:cp_data
	wire          cmd_mux_src_ready;                                                            // master_avalon_anti_master_0_agent:cp_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                                          // cmd_mux:src_channel -> master_avalon_anti_master_0_agent:cp_channel
	wire          cmd_mux_src_startofpacket;                                                    // cmd_mux:src_startofpacket -> master_avalon_anti_master_0_agent:cp_startofpacket
	wire          cmd_mux_src_endofpacket;                                                      // cmd_mux:src_endofpacket -> master_avalon_anti_master_0_agent:cp_endofpacket
	wire          elane_avalon_anti_slave_0_agent_cp_valid;                                     // elane_avalon_anti_slave_0_agent:cp_valid -> router:sink_valid
	wire  [117:0] elane_avalon_anti_slave_0_agent_cp_data;                                      // elane_avalon_anti_slave_0_agent:cp_data -> router:sink_data
	wire          elane_avalon_anti_slave_0_agent_cp_ready;                                     // router:sink_ready -> elane_avalon_anti_slave_0_agent:cp_ready
	wire          elane_avalon_anti_slave_0_agent_cp_startofpacket;                             // elane_avalon_anti_slave_0_agent:cp_startofpacket -> router:sink_startofpacket
	wire          elane_avalon_anti_slave_0_agent_cp_endofpacket;                               // elane_avalon_anti_slave_0_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                             // router:src_valid -> cmd_demux:sink_valid
	wire  [117:0] router_src_data;                                                              // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                             // cmd_demux:sink_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                                           // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                     // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                       // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          xcvr_avalon_anti_slave_0_agent_cp_valid;                                      // xcvr_avalon_anti_slave_0_agent:cp_valid -> router_001:sink_valid
	wire  [117:0] xcvr_avalon_anti_slave_0_agent_cp_data;                                       // xcvr_avalon_anti_slave_0_agent:cp_data -> router_001:sink_data
	wire          xcvr_avalon_anti_slave_0_agent_cp_ready;                                      // router_001:sink_ready -> xcvr_avalon_anti_slave_0_agent:cp_ready
	wire          xcvr_avalon_anti_slave_0_agent_cp_startofpacket;                              // xcvr_avalon_anti_slave_0_agent:cp_startofpacket -> router_001:sink_startofpacket
	wire          xcvr_avalon_anti_slave_0_agent_cp_endofpacket;                                // xcvr_avalon_anti_slave_0_agent:cp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                                         // router_001:src_valid -> cmd_demux_001:sink_valid
	wire  [117:0] router_001_src_data;                                                          // router_001:src_data -> cmd_demux_001:sink_data
	wire          router_001_src_ready;                                                         // cmd_demux_001:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                                                       // router_001:src_channel -> cmd_demux_001:sink_channel
	wire          router_001_src_startofpacket;                                                 // router_001:src_startofpacket -> cmd_demux_001:sink_startofpacket
	wire          router_001_src_endofpacket;                                                   // router_001:src_endofpacket -> cmd_demux_001:sink_endofpacket
	wire          master_avalon_anti_master_0_agent_rp_valid;                                   // master_avalon_anti_master_0_agent:rp_valid -> router_002:sink_valid
	wire  [117:0] master_avalon_anti_master_0_agent_rp_data;                                    // master_avalon_anti_master_0_agent:rp_data -> router_002:sink_data
	wire          master_avalon_anti_master_0_agent_rp_ready;                                   // router_002:sink_ready -> master_avalon_anti_master_0_agent:rp_ready
	wire          master_avalon_anti_master_0_agent_rp_startofpacket;                           // master_avalon_anti_master_0_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire          master_avalon_anti_master_0_agent_rp_endofpacket;                             // master_avalon_anti_master_0_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire          router_002_src_valid;                                                         // router_002:src_valid -> rsp_demux:sink_valid
	wire  [117:0] router_002_src_data;                                                          // router_002:src_data -> rsp_demux:sink_data
	wire          router_002_src_ready;                                                         // rsp_demux:sink_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                                                       // router_002:src_channel -> rsp_demux:sink_channel
	wire          router_002_src_startofpacket;                                                 // router_002:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_002_src_endofpacket;                                                   // router_002:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_demux_src0_valid;                                                         // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [117:0] cmd_demux_src0_data;                                                          // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                         // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                                                       // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                                 // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                   // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_001_src0_valid;                                                     // cmd_demux_001:src0_valid -> cmd_mux:sink1_valid
	wire  [117:0] cmd_demux_001_src0_data;                                                      // cmd_demux_001:src0_data -> cmd_mux:sink1_data
	wire          cmd_demux_001_src0_ready;                                                     // cmd_mux:sink1_ready -> cmd_demux_001:src0_ready
	wire    [1:0] cmd_demux_001_src0_channel;                                                   // cmd_demux_001:src0_channel -> cmd_mux:sink1_channel
	wire          cmd_demux_001_src0_startofpacket;                                             // cmd_demux_001:src0_startofpacket -> cmd_mux:sink1_startofpacket
	wire          cmd_demux_001_src0_endofpacket;                                               // cmd_demux_001:src0_endofpacket -> cmd_mux:sink1_endofpacket
	wire          rsp_demux_src0_valid;                                                         // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [117:0] rsp_demux_src0_data;                                                          // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                         // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                                                       // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                                 // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                   // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_src1_valid;                                                         // rsp_demux:src1_valid -> rsp_mux_001:sink0_valid
	wire  [117:0] rsp_demux_src1_data;                                                          // rsp_demux:src1_data -> rsp_mux_001:sink0_data
	wire          rsp_demux_src1_ready;                                                         // rsp_mux_001:sink0_ready -> rsp_demux:src1_ready
	wire    [1:0] rsp_demux_src1_channel;                                                       // rsp_demux:src1_channel -> rsp_mux_001:sink0_channel
	wire          rsp_demux_src1_startofpacket;                                                 // rsp_demux:src1_startofpacket -> rsp_mux_001:sink0_startofpacket
	wire          rsp_demux_src1_endofpacket;                                                   // rsp_demux:src1_endofpacket -> rsp_mux_001:sink0_endofpacket

	hssi_ss_1_altera_merlin_master_translator_192_lykd4la #(
		.AV_ADDRESS_W                (22),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (24),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (1),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (0),
		.WAITREQUEST_ALLOWANCE       (0),
		.USE_OUTPUTENABLE            (0)
	) elane_avalon_anti_slave_0_translator (
		.clk                    (clock_in_out_clk_clk),                                                         //   input,   width = 1,                       clk.clk
		.reset                  (elane_reset_reset_bridge_in_reset_reset),                                      //   input,   width = 1,                     reset.reset
		.uav_address            (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_address),       //  output,  width = 24, avalon_universal_master_0.address
		.uav_burstcount         (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_burstcount),    //  output,   width = 3,                          .burstcount
		.uav_read               (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write              (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest        (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata           (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata          (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock               (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess        (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.av_address             (elane_avalon_anti_slave_0_address),                                            //   input,  width = 22,      avalon_anti_master_0.address
		.av_waitrequest         (elane_avalon_anti_slave_0_waitrequest),                                        //  output,   width = 1,                          .waitrequest
		.av_read                (elane_avalon_anti_slave_0_read),                                               //   input,   width = 1,                          .read
		.av_readdata            (elane_avalon_anti_slave_0_readdata),                                           //  output,  width = 32,                          .readdata
		.av_readdatavalid       (elane_avalon_anti_slave_0_readdatavalid),                                      //  output,   width = 1,                          .readdatavalid
		.av_write               (elane_avalon_anti_slave_0_write),                                              //   input,   width = 1,                          .write
		.av_writedata           (elane_avalon_anti_slave_0_writedata),                                          //   input,  width = 32,                          .writedata
		.av_burstcount          (1'b1),                                                                         // (terminated),                                        
		.av_byteenable          (4'b1111),                                                                      // (terminated),                                        
		.av_beginbursttransfer  (1'b0),                                                                         // (terminated),                                        
		.av_begintransfer       (1'b0),                                                                         // (terminated),                                        
		.av_chipselect          (1'b0),                                                                         // (terminated),                                        
		.av_lock                (1'b0),                                                                         // (terminated),                                        
		.av_debugaccess         (1'b0),                                                                         // (terminated),                                        
		.uav_outputenable       (1'b0),                                                                         // (terminated),                                        
		.uav_clken              (),                                                                             // (terminated),                                        
		.av_clken               (1'b1),                                                                         // (terminated),                                        
		.uav_response           (2'b00),                                                                        // (terminated),                                        
		.av_response            (),                                                                             // (terminated),                                        
		.uav_writeresponsevalid (1'b0),                                                                         // (terminated),                                        
		.av_writeresponsevalid  ()                                                                              // (terminated),                                        
	);

	hssi_ss_1_altera_merlin_master_translator_192_lykd4la #(
		.AV_ADDRESS_W                (22),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (24),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (1),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (1),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (0),
		.WAITREQUEST_ALLOWANCE       (0),
		.USE_OUTPUTENABLE            (0)
	) xcvr_avalon_anti_slave_0_translator (
		.clk                    (clock_in_out_clk_clk),                                                        //   input,   width = 1,                       clk.clk
		.reset                  (elane_reset_reset_bridge_in_reset_reset),                                     //   input,   width = 1,                     reset.reset
		.uav_address            (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_address),       //  output,  width = 24, avalon_universal_master_0.address
		.uav_burstcount         (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_burstcount),    //  output,   width = 3,                          .burstcount
		.uav_read               (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write              (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest        (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata           (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata          (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock               (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess        (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.av_address             (xcvr_avalon_anti_slave_0_address),                                            //   input,  width = 22,      avalon_anti_master_0.address
		.av_waitrequest         (xcvr_avalon_anti_slave_0_waitrequest),                                        //  output,   width = 1,                          .waitrequest
		.av_byteenable          (xcvr_avalon_anti_slave_0_byteenable),                                         //   input,   width = 4,                          .byteenable
		.av_begintransfer       (xcvr_avalon_anti_slave_0_begintransfer),                                      //   input,   width = 1,                          .begintransfer
		.av_read                (xcvr_avalon_anti_slave_0_read),                                               //   input,   width = 1,                          .read
		.av_readdata            (xcvr_avalon_anti_slave_0_readdata),                                           //  output,  width = 32,                          .readdata
		.av_readdatavalid       (xcvr_avalon_anti_slave_0_readdatavalid),                                      //  output,   width = 1,                          .readdatavalid
		.av_write               (xcvr_avalon_anti_slave_0_write),                                              //   input,   width = 1,                          .write
		.av_writedata           (xcvr_avalon_anti_slave_0_writedata),                                          //   input,  width = 32,                          .writedata
		.av_burstcount          (1'b1),                                                                        // (terminated),                                        
		.av_beginbursttransfer  (1'b0),                                                                        // (terminated),                                        
		.av_chipselect          (1'b0),                                                                        // (terminated),                                        
		.av_lock                (1'b0),                                                                        // (terminated),                                        
		.av_debugaccess         (1'b0),                                                                        // (terminated),                                        
		.uav_outputenable       (1'b0),                                                                        // (terminated),                                        
		.uav_clken              (),                                                                            // (terminated),                                        
		.av_clken               (1'b1),                                                                        // (terminated),                                        
		.uav_response           (2'b00),                                                                       // (terminated),                                        
		.av_response            (),                                                                            // (terminated),                                        
		.uav_writeresponsevalid (1'b0),                                                                        // (terminated),                                        
		.av_writeresponsevalid  ()                                                                             // (terminated),                                        
	);

	hssi_ss_1_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (22),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (24),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (1),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (0)
	) master_avalon_anti_master_0_translator (
		.clk                    (clock_in_out_clk_clk),                               //   input,   width = 1,                      clk.clk
		.reset                  (elane_reset_reset_bridge_in_reset_reset),            //   input,   width = 1,                    reset.reset
		.uav_address            (master_avalon_anti_master_0_agent_m0_address),       //   input,  width = 24, avalon_universal_slave_0.address
		.uav_burstcount         (master_avalon_anti_master_0_agent_m0_burstcount),    //   input,   width = 3,                         .burstcount
		.uav_read               (master_avalon_anti_master_0_agent_m0_read),          //   input,   width = 1,                         .read
		.uav_write              (master_avalon_anti_master_0_agent_m0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest        (master_avalon_anti_master_0_agent_m0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (master_avalon_anti_master_0_agent_m0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (master_avalon_anti_master_0_agent_m0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata           (master_avalon_anti_master_0_agent_m0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata          (master_avalon_anti_master_0_agent_m0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock               (master_avalon_anti_master_0_agent_m0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess        (master_avalon_anti_master_0_agent_m0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.av_address             (master_avalon_anti_master_0_address),                //  output,  width = 22,      avalon_anti_slave_0.address
		.av_write               (master_avalon_anti_master_0_write),                  //  output,   width = 1,                         .write
		.av_read                (master_avalon_anti_master_0_read),                   //  output,   width = 1,                         .read
		.av_readdata            (master_avalon_anti_master_0_readdata),               //   input,  width = 32,                         .readdata
		.av_writedata           (master_avalon_anti_master_0_writedata),              //  output,  width = 32,                         .writedata
		.av_readdatavalid       (master_avalon_anti_master_0_readdatavalid),          //   input,   width = 1,                         .readdatavalid
		.av_waitrequest         (master_avalon_anti_master_0_waitrequest),            //   input,   width = 1,                         .waitrequest
		.av_begintransfer       (),                                                   // (terminated),                                       
		.av_beginbursttransfer  (),                                                   // (terminated),                                       
		.av_burstcount          (),                                                   // (terminated),                                       
		.av_byteenable          (),                                                   // (terminated),                                       
		.av_writebyteenable     (),                                                   // (terminated),                                       
		.av_lock                (),                                                   // (terminated),                                       
		.av_chipselect          (),                                                   // (terminated),                                       
		.av_clken               (),                                                   // (terminated),                                       
		.uav_clken              (1'b0),                                               // (terminated),                                       
		.av_debugaccess         (),                                                   // (terminated),                                       
		.av_outputenable        (),                                                   // (terminated),                                       
		.uav_response           (),                                                   // (terminated),                                       
		.av_response            (2'b00),                                              // (terminated),                                       
		.uav_writeresponsevalid (),                                                   // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                                // (terminated),                                       
	);

	hssi_ss_1_altera_merlin_master_agent_1922_fy3n5ti #(
		.PKT_WUNIQUE               (102),
		.PKT_DOMAIN_H              (101),
		.PKT_DOMAIN_L              (100),
		.PKT_SNOOP_H               (99),
		.PKT_SNOOP_L               (96),
		.PKT_BARRIER_H             (95),
		.PKT_BARRIER_L             (94),
		.PKT_ORI_BURST_SIZE_H      (93),
		.PKT_ORI_BURST_SIZE_L      (91),
		.PKT_RESPONSE_STATUS_H     (90),
		.PKT_RESPONSE_STATUS_L     (89),
		.PKT_QOS_H                 (78),
		.PKT_QOS_L                 (78),
		.PKT_DATA_SIDEBAND_H       (76),
		.PKT_DATA_SIDEBAND_L       (76),
		.PKT_ADDR_SIDEBAND_H       (75),
		.PKT_ADDR_SIDEBAND_L       (75),
		.PKT_BURST_TYPE_H          (74),
		.PKT_BURST_TYPE_L          (73),
		.PKT_CACHE_H               (88),
		.PKT_CACHE_L               (85),
		.PKT_THREAD_ID_H           (81),
		.PKT_THREAD_ID_L           (81),
		.PKT_BURST_SIZE_H          (72),
		.PKT_BURST_SIZE_L          (70),
		.PKT_TRANS_EXCLUSIVE       (65),
		.PKT_TRANS_LOCK            (64),
		.PKT_BEGIN_BURST           (77),
		.PKT_PROTECTION_H          (84),
		.PKT_PROTECTION_L          (82),
		.PKT_BURSTWRAP_H           (69),
		.PKT_BURSTWRAP_L           (69),
		.PKT_BYTE_CNT_H            (68),
		.PKT_BYTE_CNT_L            (66),
		.PKT_ADDR_H                (59),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (60),
		.PKT_TRANS_POSTED          (61),
		.PKT_TRANS_WRITE           (62),
		.PKT_TRANS_READ            (63),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (79),
		.PKT_SRC_ID_L              (79),
		.PKT_DEST_ID_H             (80),
		.PKT_DEST_ID_L             (80),
		.PKT_POISON_H              (103),
		.PKT_POISON_L              (103),
		.PKT_DATACHK_H             (104),
		.PKT_DATACHK_L             (104),
		.PKT_ADDRCHK_H             (107),
		.PKT_ADDRCHK_L             (106),
		.PKT_SAI_H                 (108),
		.PKT_SAI_L                 (108),
		.PKT_USER_DATA_H           (105),
		.PKT_USER_DATA_L           (105),
		.ST_DATA_W                 (118),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.DOMAIN_VALUE              (3),
		.BARRIER_VALUE             (0),
		.SNOOP_VALUE               (0),
		.WUNIQUE_VALUE             (0),
		.SYNC_RESET                (0),
		.USE_PKT_DATACHK           (0),
		.USE_PKT_ADDRCHK           (0),
		.ROLE_BASED_USER           (0)
	) elane_avalon_anti_slave_0_agent (
		.clk                   (clock_in_out_clk_clk),                                                         //   input,    width = 1,       clk.clk
		.reset                 (elane_reset_reset_bridge_in_reset_reset),                                      //   input,    width = 1, clk_reset.reset
		.av_address            (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_address),       //   input,   width = 24,        av.address
		.av_write              (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_write),         //   input,    width = 1,          .write
		.av_read               (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_read),          //   input,    width = 1,          .read
		.av_writedata          (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_writedata),     //   input,   width = 32,          .writedata
		.av_readdata           (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_readdata),      //  output,   width = 32,          .readdata
		.av_waitrequest        (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_waitrequest),   //  output,    width = 1,          .waitrequest
		.av_readdatavalid      (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_readdatavalid), //  output,    width = 1,          .readdatavalid
		.av_byteenable         (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_byteenable),    //   input,    width = 4,          .byteenable
		.av_burstcount         (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_burstcount),    //   input,    width = 3,          .burstcount
		.av_debugaccess        (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_debugaccess),   //   input,    width = 1,          .debugaccess
		.av_lock               (elane_avalon_anti_slave_0_translator_avalon_universal_master_0_lock),          //   input,    width = 1,          .lock
		.cp_valid              (elane_avalon_anti_slave_0_agent_cp_valid),                                     //  output,    width = 1,        cp.valid
		.cp_data               (elane_avalon_anti_slave_0_agent_cp_data),                                      //  output,  width = 118,          .data
		.cp_startofpacket      (elane_avalon_anti_slave_0_agent_cp_startofpacket),                             //  output,    width = 1,          .startofpacket
		.cp_endofpacket        (elane_avalon_anti_slave_0_agent_cp_endofpacket),                               //  output,    width = 1,          .endofpacket
		.cp_ready              (elane_avalon_anti_slave_0_agent_cp_ready),                                     //   input,    width = 1,          .ready
		.rp_valid              (rsp_mux_src_valid),                                                            //   input,    width = 1,        rp.valid
		.rp_data               (rsp_mux_src_data),                                                             //   input,  width = 118,          .data
		.rp_channel            (rsp_mux_src_channel),                                                          //   input,    width = 2,          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                    //   input,    width = 1,          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                      //   input,    width = 1,          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                            //  output,    width = 1,          .ready
		.av_response           (),                                                                             // (terminated),                         
		.av_writeresponsevalid ()                                                                              // (terminated),                         
	);

	hssi_ss_1_altera_merlin_master_agent_1922_fy3n5ti #(
		.PKT_WUNIQUE               (102),
		.PKT_DOMAIN_H              (101),
		.PKT_DOMAIN_L              (100),
		.PKT_SNOOP_H               (99),
		.PKT_SNOOP_L               (96),
		.PKT_BARRIER_H             (95),
		.PKT_BARRIER_L             (94),
		.PKT_ORI_BURST_SIZE_H      (93),
		.PKT_ORI_BURST_SIZE_L      (91),
		.PKT_RESPONSE_STATUS_H     (90),
		.PKT_RESPONSE_STATUS_L     (89),
		.PKT_QOS_H                 (78),
		.PKT_QOS_L                 (78),
		.PKT_DATA_SIDEBAND_H       (76),
		.PKT_DATA_SIDEBAND_L       (76),
		.PKT_ADDR_SIDEBAND_H       (75),
		.PKT_ADDR_SIDEBAND_L       (75),
		.PKT_BURST_TYPE_H          (74),
		.PKT_BURST_TYPE_L          (73),
		.PKT_CACHE_H               (88),
		.PKT_CACHE_L               (85),
		.PKT_THREAD_ID_H           (81),
		.PKT_THREAD_ID_L           (81),
		.PKT_BURST_SIZE_H          (72),
		.PKT_BURST_SIZE_L          (70),
		.PKT_TRANS_EXCLUSIVE       (65),
		.PKT_TRANS_LOCK            (64),
		.PKT_BEGIN_BURST           (77),
		.PKT_PROTECTION_H          (84),
		.PKT_PROTECTION_L          (82),
		.PKT_BURSTWRAP_H           (69),
		.PKT_BURSTWRAP_L           (69),
		.PKT_BYTE_CNT_H            (68),
		.PKT_BYTE_CNT_L            (66),
		.PKT_ADDR_H                (59),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (60),
		.PKT_TRANS_POSTED          (61),
		.PKT_TRANS_WRITE           (62),
		.PKT_TRANS_READ            (63),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (79),
		.PKT_SRC_ID_L              (79),
		.PKT_DEST_ID_H             (80),
		.PKT_DEST_ID_L             (80),
		.PKT_POISON_H              (103),
		.PKT_POISON_L              (103),
		.PKT_DATACHK_H             (104),
		.PKT_DATACHK_L             (104),
		.PKT_ADDRCHK_H             (107),
		.PKT_ADDRCHK_L             (106),
		.PKT_SAI_H                 (108),
		.PKT_SAI_L                 (108),
		.PKT_USER_DATA_H           (105),
		.PKT_USER_DATA_L           (105),
		.ST_DATA_W                 (118),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (1),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.DOMAIN_VALUE              (3),
		.BARRIER_VALUE             (0),
		.SNOOP_VALUE               (0),
		.WUNIQUE_VALUE             (0),
		.SYNC_RESET                (0),
		.USE_PKT_DATACHK           (0),
		.USE_PKT_ADDRCHK           (0),
		.ROLE_BASED_USER           (0)
	) xcvr_avalon_anti_slave_0_agent (
		.clk                   (clock_in_out_clk_clk),                                                        //   input,    width = 1,       clk.clk
		.reset                 (elane_reset_reset_bridge_in_reset_reset),                                     //   input,    width = 1, clk_reset.reset
		.av_address            (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_address),       //   input,   width = 24,        av.address
		.av_write              (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_write),         //   input,    width = 1,          .write
		.av_read               (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_read),          //   input,    width = 1,          .read
		.av_writedata          (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_writedata),     //   input,   width = 32,          .writedata
		.av_readdata           (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_readdata),      //  output,   width = 32,          .readdata
		.av_waitrequest        (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_waitrequest),   //  output,    width = 1,          .waitrequest
		.av_readdatavalid      (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_readdatavalid), //  output,    width = 1,          .readdatavalid
		.av_byteenable         (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_byteenable),    //   input,    width = 4,          .byteenable
		.av_burstcount         (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_burstcount),    //   input,    width = 3,          .burstcount
		.av_debugaccess        (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_debugaccess),   //   input,    width = 1,          .debugaccess
		.av_lock               (xcvr_avalon_anti_slave_0_translator_avalon_universal_master_0_lock),          //   input,    width = 1,          .lock
		.cp_valid              (xcvr_avalon_anti_slave_0_agent_cp_valid),                                     //  output,    width = 1,        cp.valid
		.cp_data               (xcvr_avalon_anti_slave_0_agent_cp_data),                                      //  output,  width = 118,          .data
		.cp_startofpacket      (xcvr_avalon_anti_slave_0_agent_cp_startofpacket),                             //  output,    width = 1,          .startofpacket
		.cp_endofpacket        (xcvr_avalon_anti_slave_0_agent_cp_endofpacket),                               //  output,    width = 1,          .endofpacket
		.cp_ready              (xcvr_avalon_anti_slave_0_agent_cp_ready),                                     //   input,    width = 1,          .ready
		.rp_valid              (rsp_mux_001_src_valid),                                                       //   input,    width = 1,        rp.valid
		.rp_data               (rsp_mux_001_src_data),                                                        //   input,  width = 118,          .data
		.rp_channel            (rsp_mux_001_src_channel),                                                     //   input,    width = 2,          .channel
		.rp_startofpacket      (rsp_mux_001_src_startofpacket),                                               //   input,    width = 1,          .startofpacket
		.rp_endofpacket        (rsp_mux_001_src_endofpacket),                                                 //   input,    width = 1,          .endofpacket
		.rp_ready              (rsp_mux_001_src_ready),                                                       //  output,    width = 1,          .ready
		.av_response           (),                                                                            // (terminated),                         
		.av_writeresponsevalid ()                                                                             // (terminated),                         
	);

	hssi_ss_1_altera_merlin_slave_agent_1921_b6r3djy #(
		.PKT_ORI_BURST_SIZE_H      (93),
		.PKT_ORI_BURST_SIZE_L      (91),
		.PKT_RESPONSE_STATUS_H     (90),
		.PKT_RESPONSE_STATUS_L     (89),
		.PKT_BURST_SIZE_H          (72),
		.PKT_BURST_SIZE_L          (70),
		.PKT_TRANS_LOCK            (64),
		.PKT_BEGIN_BURST           (77),
		.PKT_PROTECTION_H          (84),
		.PKT_PROTECTION_L          (82),
		.PKT_BURSTWRAP_H           (69),
		.PKT_BURSTWRAP_L           (69),
		.PKT_BYTE_CNT_H            (68),
		.PKT_BYTE_CNT_L            (66),
		.PKT_ADDR_H                (59),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (60),
		.PKT_TRANS_POSTED          (61),
		.PKT_TRANS_WRITE           (62),
		.PKT_TRANS_READ            (63),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (79),
		.PKT_SRC_ID_L              (79),
		.PKT_DEST_ID_H             (80),
		.PKT_DEST_ID_L             (80),
		.PKT_POISON_H              (103),
		.PKT_POISON_L              (103),
		.PKT_DATACHK_H             (104),
		.PKT_DATACHK_L             (104),
		.PKT_SAI_H                 (108),
		.PKT_SAI_L                 (108),
		.PKT_ADDRCHK_H             (107),
		.PKT_ADDRCHK_L             (106),
		.PKT_USER_DATA_H           (105),
		.PKT_USER_DATA_L           (105),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (118),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.USE_MEMORY_BLOCKS         (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0),
		.SYNC_RESET                (0),
		.USE_PKT_DATACHK           (0),
		.ROLE_BASED_USER           (0)
	) master_avalon_anti_master_0_agent (
		.clk                     (clock_in_out_clk_clk),                                         //   input,    width = 1,             clk.clk
		.reset                   (elane_reset_reset_bridge_in_reset_reset),                      //   input,    width = 1,       clk_reset.reset
		.m0_address              (master_avalon_anti_master_0_agent_m0_address),                 //  output,   width = 24,              m0.address
		.m0_burstcount           (master_avalon_anti_master_0_agent_m0_burstcount),              //  output,    width = 3,                .burstcount
		.m0_byteenable           (master_avalon_anti_master_0_agent_m0_byteenable),              //  output,    width = 4,                .byteenable
		.m0_debugaccess          (master_avalon_anti_master_0_agent_m0_debugaccess),             //  output,    width = 1,                .debugaccess
		.m0_lock                 (master_avalon_anti_master_0_agent_m0_lock),                    //  output,    width = 1,                .lock
		.m0_readdata             (master_avalon_anti_master_0_agent_m0_readdata),                //   input,   width = 32,                .readdata
		.m0_readdatavalid        (master_avalon_anti_master_0_agent_m0_readdatavalid),           //   input,    width = 1,                .readdatavalid
		.m0_read                 (master_avalon_anti_master_0_agent_m0_read),                    //  output,    width = 1,                .read
		.m0_waitrequest          (master_avalon_anti_master_0_agent_m0_waitrequest),             //   input,    width = 1,                .waitrequest
		.m0_writedata            (master_avalon_anti_master_0_agent_m0_writedata),               //  output,   width = 32,                .writedata
		.m0_write                (master_avalon_anti_master_0_agent_m0_write),                   //  output,    width = 1,                .write
		.rp_endofpacket          (master_avalon_anti_master_0_agent_rp_endofpacket),             //  output,    width = 1,              rp.endofpacket
		.rp_ready                (master_avalon_anti_master_0_agent_rp_ready),                   //   input,    width = 1,                .ready
		.rp_valid                (master_avalon_anti_master_0_agent_rp_valid),                   //  output,    width = 1,                .valid
		.rp_data                 (master_avalon_anti_master_0_agent_rp_data),                    //  output,  width = 118,                .data
		.rp_startofpacket        (master_avalon_anti_master_0_agent_rp_startofpacket),           //  output,    width = 1,                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                                            //  output,    width = 1,              cp.ready
		.cp_valid                (cmd_mux_src_valid),                                            //   input,    width = 1,                .valid
		.cp_data                 (cmd_mux_src_data),                                             //   input,  width = 118,                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                                    //   input,    width = 1,                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                                      //   input,    width = 1,                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                                          //   input,    width = 2,                .channel
		.rf_sink_ready           (master_avalon_anti_master_0_agent_rsp_fifo_out_ready),         //  output,    width = 1,         rf_sink.ready
		.rf_sink_valid           (master_avalon_anti_master_0_agent_rsp_fifo_out_valid),         //   input,    width = 1,                .valid
		.rf_sink_startofpacket   (master_avalon_anti_master_0_agent_rsp_fifo_out_startofpacket), //   input,    width = 1,                .startofpacket
		.rf_sink_endofpacket     (master_avalon_anti_master_0_agent_rsp_fifo_out_endofpacket),   //   input,    width = 1,                .endofpacket
		.rf_sink_data            (master_avalon_anti_master_0_agent_rsp_fifo_out_data),          //   input,  width = 119,                .data
		.rf_source_ready         (master_avalon_anti_master_0_agent_rf_source_ready),            //   input,    width = 1,       rf_source.ready
		.rf_source_valid         (master_avalon_anti_master_0_agent_rf_source_valid),            //  output,    width = 1,                .valid
		.rf_source_startofpacket (master_avalon_anti_master_0_agent_rf_source_startofpacket),    //  output,    width = 1,                .startofpacket
		.rf_source_endofpacket   (master_avalon_anti_master_0_agent_rf_source_endofpacket),      //  output,    width = 1,                .endofpacket
		.rf_source_data          (master_avalon_anti_master_0_agent_rf_source_data),             //  output,  width = 119,                .data
		.rdata_fifo_sink_ready   (master_avalon_anti_master_0_agent_rdata_fifo_src_ready),       //  output,    width = 1, rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (master_avalon_anti_master_0_agent_rdata_fifo_src_valid),       //   input,    width = 1,                .valid
		.rdata_fifo_sink_data    (master_avalon_anti_master_0_agent_rdata_fifo_src_data),        //   input,   width = 34,                .data
		.rdata_fifo_src_ready    (master_avalon_anti_master_0_agent_rdata_fifo_src_ready),       //   input,    width = 1,  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (master_avalon_anti_master_0_agent_rdata_fifo_src_valid),       //  output,    width = 1,                .valid
		.rdata_fifo_src_data     (master_avalon_anti_master_0_agent_rdata_fifo_src_data),        //  output,   width = 34,                .data
		.m0_response             (2'b00),                                                        // (terminated),                               
		.m0_writeresponsevalid   (1'b0),                                                         // (terminated),                               
		.rdata_fifo_sink_error   (1'b0)                                                          // (terminated),                               
	);

	hssi_ss_1_altera_avalon_sc_fifo_1932_5j7ufsq #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (119),
		.FIFO_DEPTH          (65),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0),
		.EMPTY_WIDTH         (1),
		.MEM_TYPE            ("M20K"),
		.SYNC_RESET          (0)
	) master_avalon_anti_master_0_agent_rsp_fifo (
		.clk               (clock_in_out_clk_clk),                                         //   input,    width = 1,       clk.clk
		.reset             (elane_reset_reset_bridge_in_reset_reset),                      //   input,    width = 1, clk_reset.reset
		.in_data           (master_avalon_anti_master_0_agent_rf_source_data),             //   input,  width = 119,        in.data
		.in_valid          (master_avalon_anti_master_0_agent_rf_source_valid),            //   input,    width = 1,          .valid
		.in_ready          (master_avalon_anti_master_0_agent_rf_source_ready),            //  output,    width = 1,          .ready
		.in_startofpacket  (master_avalon_anti_master_0_agent_rf_source_startofpacket),    //   input,    width = 1,          .startofpacket
		.in_endofpacket    (master_avalon_anti_master_0_agent_rf_source_endofpacket),      //   input,    width = 1,          .endofpacket
		.out_data          (master_avalon_anti_master_0_agent_rsp_fifo_out_data),          //  output,  width = 119,       out.data
		.out_valid         (master_avalon_anti_master_0_agent_rsp_fifo_out_valid),         //  output,    width = 1,          .valid
		.out_ready         (master_avalon_anti_master_0_agent_rsp_fifo_out_ready),         //   input,    width = 1,          .ready
		.out_startofpacket (master_avalon_anti_master_0_agent_rsp_fifo_out_startofpacket), //  output,    width = 1,          .startofpacket
		.out_endofpacket   (master_avalon_anti_master_0_agent_rsp_fifo_out_endofpacket),   //  output,    width = 1,          .endofpacket
		.csr_address       (2'b00),                                                        // (terminated),                         
		.csr_read          (1'b0),                                                         // (terminated),                         
		.csr_write         (1'b0),                                                         // (terminated),                         
		.csr_readdata      (),                                                             // (terminated),                         
		.csr_writedata     (32'b00000000000000000000000000000000),                         // (terminated),                         
		.almost_full_data  (),                                                             // (terminated),                         
		.almost_empty_data (),                                                             // (terminated),                         
		.in_empty          (1'b0),                                                         // (terminated),                         
		.out_empty         (),                                                             // (terminated),                         
		.in_error          (1'b0),                                                         // (terminated),                         
		.out_error         (),                                                             // (terminated),                         
		.in_channel        (1'b0),                                                         // (terminated),                         
		.out_channel       ()                                                              // (terminated),                         
	);

	hssi_ss_1_altera_merlin_router_1921_yazz2ji router (
		.sink_ready         (elane_avalon_anti_slave_0_agent_cp_ready),         //  output,    width = 1,      sink.ready
		.sink_valid         (elane_avalon_anti_slave_0_agent_cp_valid),         //   input,    width = 1,          .valid
		.sink_data          (elane_avalon_anti_slave_0_agent_cp_data),          //   input,  width = 118,          .data
		.sink_startofpacket (elane_avalon_anti_slave_0_agent_cp_startofpacket), //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (elane_avalon_anti_slave_0_agent_cp_endofpacket),   //   input,    width = 1,          .endofpacket
		.clk                (clock_in_out_clk_clk),                             //   input,    width = 1,       clk.clk
		.reset              (elane_reset_reset_bridge_in_reset_reset),          //   input,    width = 1, clk_reset.reset
		.src_ready          (router_src_ready),                                 //   input,    width = 1,       src.ready
		.src_valid          (router_src_valid),                                 //  output,    width = 1,          .valid
		.src_data           (router_src_data),                                  //  output,  width = 118,          .data
		.src_channel        (router_src_channel),                               //  output,    width = 2,          .channel
		.src_startofpacket  (router_src_startofpacket),                         //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                            //  output,    width = 1,          .endofpacket
	);

	hssi_ss_1_altera_merlin_router_1921_yazz2ji router_001 (
		.sink_ready         (xcvr_avalon_anti_slave_0_agent_cp_ready),         //  output,    width = 1,      sink.ready
		.sink_valid         (xcvr_avalon_anti_slave_0_agent_cp_valid),         //   input,    width = 1,          .valid
		.sink_data          (xcvr_avalon_anti_slave_0_agent_cp_data),          //   input,  width = 118,          .data
		.sink_startofpacket (xcvr_avalon_anti_slave_0_agent_cp_startofpacket), //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (xcvr_avalon_anti_slave_0_agent_cp_endofpacket),   //   input,    width = 1,          .endofpacket
		.clk                (clock_in_out_clk_clk),                            //   input,    width = 1,       clk.clk
		.reset              (elane_reset_reset_bridge_in_reset_reset),         //   input,    width = 1, clk_reset.reset
		.src_ready          (router_001_src_ready),                            //   input,    width = 1,       src.ready
		.src_valid          (router_001_src_valid),                            //  output,    width = 1,          .valid
		.src_data           (router_001_src_data),                             //  output,  width = 118,          .data
		.src_channel        (router_001_src_channel),                          //  output,    width = 2,          .channel
		.src_startofpacket  (router_001_src_startofpacket),                    //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                       //  output,    width = 1,          .endofpacket
	);

	hssi_ss_1_altera_merlin_router_1921_4lcrnay router_002 (
		.sink_ready         (master_avalon_anti_master_0_agent_rp_ready),         //  output,    width = 1,      sink.ready
		.sink_valid         (master_avalon_anti_master_0_agent_rp_valid),         //   input,    width = 1,          .valid
		.sink_data          (master_avalon_anti_master_0_agent_rp_data),          //   input,  width = 118,          .data
		.sink_startofpacket (master_avalon_anti_master_0_agent_rp_startofpacket), //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (master_avalon_anti_master_0_agent_rp_endofpacket),   //   input,    width = 1,          .endofpacket
		.clk                (clock_in_out_clk_clk),                               //   input,    width = 1,       clk.clk
		.reset              (elane_reset_reset_bridge_in_reset_reset),            //   input,    width = 1, clk_reset.reset
		.src_ready          (router_002_src_ready),                               //   input,    width = 1,       src.ready
		.src_valid          (router_002_src_valid),                               //  output,    width = 1,          .valid
		.src_data           (router_002_src_data),                                //  output,  width = 118,          .data
		.src_channel        (router_002_src_channel),                             //  output,    width = 2,          .channel
		.src_startofpacket  (router_002_src_startofpacket),                       //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                          //  output,    width = 1,          .endofpacket
	);

	hssi_ss_1_altera_merlin_demultiplexer_1921_qdvqwaa cmd_demux (
		.clk                (clock_in_out_clk_clk),                    //   input,    width = 1,       clk.clk
		.reset              (elane_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_src_ready),                        //  output,    width = 1,      sink.ready
		.sink_channel       (router_src_channel),                      //   input,    width = 2,          .channel
		.sink_data          (router_src_data),                         //   input,  width = 118,          .data
		.sink_startofpacket (router_src_startofpacket),                //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                  //   input,    width = 1,          .endofpacket
		.sink_valid         (router_src_valid),                        //   input,    width = 1,          .valid
		.src0_ready         (cmd_demux_src0_ready),                    //   input,    width = 1,      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                    //  output,    width = 1,          .valid
		.src0_data          (cmd_demux_src0_data),                     //  output,  width = 118,          .data
		.src0_channel       (cmd_demux_src0_channel),                  //  output,    width = 2,          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),            //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)               //  output,    width = 1,          .endofpacket
	);

	hssi_ss_1_altera_merlin_demultiplexer_1921_qdvqwaa cmd_demux_001 (
		.clk                (clock_in_out_clk_clk),                    //   input,    width = 1,       clk.clk
		.reset              (elane_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_001_src_ready),                    //  output,    width = 1,      sink.ready
		.sink_channel       (router_001_src_channel),                  //   input,    width = 2,          .channel
		.sink_data          (router_001_src_data),                     //   input,  width = 118,          .data
		.sink_startofpacket (router_001_src_startofpacket),            //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),              //   input,    width = 1,          .endofpacket
		.sink_valid         (router_001_src_valid),                    //   input,    width = 1,          .valid
		.src0_ready         (cmd_demux_001_src0_ready),                //   input,    width = 1,      src0.ready
		.src0_valid         (cmd_demux_001_src0_valid),                //  output,    width = 1,          .valid
		.src0_data          (cmd_demux_001_src0_data),                 //  output,  width = 118,          .data
		.src0_channel       (cmd_demux_001_src0_channel),              //  output,    width = 2,          .channel
		.src0_startofpacket (cmd_demux_001_src0_startofpacket),        //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (cmd_demux_001_src0_endofpacket)           //  output,    width = 1,          .endofpacket
	);

	hssi_ss_1_altera_merlin_multiplexer_1922_fgcjcqq cmd_mux (
		.clk                 (clock_in_out_clk_clk),                    //   input,    width = 1,       clk.clk
		.reset               (elane_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                       //   input,    width = 1,       src.ready
		.src_valid           (cmd_mux_src_valid),                       //  output,    width = 1,          .valid
		.src_data            (cmd_mux_src_data),                        //  output,  width = 118,          .data
		.src_channel         (cmd_mux_src_channel),                     //  output,    width = 2,          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),               //  output,    width = 1,          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                 //  output,    width = 1,          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                    //  output,    width = 1,     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                    //   input,    width = 1,          .valid
		.sink0_channel       (cmd_demux_src0_channel),                  //   input,    width = 2,          .channel
		.sink0_data          (cmd_demux_src0_data),                     //   input,  width = 118,          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),            //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket),              //   input,    width = 1,          .endofpacket
		.sink1_ready         (cmd_demux_001_src0_ready),                //  output,    width = 1,     sink1.ready
		.sink1_valid         (cmd_demux_001_src0_valid),                //   input,    width = 1,          .valid
		.sink1_channel       (cmd_demux_001_src0_channel),              //   input,    width = 2,          .channel
		.sink1_data          (cmd_demux_001_src0_data),                 //   input,  width = 118,          .data
		.sink1_startofpacket (cmd_demux_001_src0_startofpacket),        //   input,    width = 1,          .startofpacket
		.sink1_endofpacket   (cmd_demux_001_src0_endofpacket)           //   input,    width = 1,          .endofpacket
	);

	hssi_ss_1_altera_merlin_demultiplexer_1921_uzs3tbq rsp_demux (
		.clk                (clock_in_out_clk_clk),                    //   input,    width = 1,       clk.clk
		.reset              (elane_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_002_src_ready),                    //  output,    width = 1,      sink.ready
		.sink_channel       (router_002_src_channel),                  //   input,    width = 2,          .channel
		.sink_data          (router_002_src_data),                     //   input,  width = 118,          .data
		.sink_startofpacket (router_002_src_startofpacket),            //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),              //   input,    width = 1,          .endofpacket
		.sink_valid         (router_002_src_valid),                    //   input,    width = 1,          .valid
		.src0_ready         (rsp_demux_src0_ready),                    //   input,    width = 1,      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                    //  output,    width = 1,          .valid
		.src0_data          (rsp_demux_src0_data),                     //  output,  width = 118,          .data
		.src0_channel       (rsp_demux_src0_channel),                  //  output,    width = 2,          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),            //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket),              //  output,    width = 1,          .endofpacket
		.src1_ready         (rsp_demux_src1_ready),                    //   input,    width = 1,      src1.ready
		.src1_valid         (rsp_demux_src1_valid),                    //  output,    width = 1,          .valid
		.src1_data          (rsp_demux_src1_data),                     //  output,  width = 118,          .data
		.src1_channel       (rsp_demux_src1_channel),                  //  output,    width = 2,          .channel
		.src1_startofpacket (rsp_demux_src1_startofpacket),            //  output,    width = 1,          .startofpacket
		.src1_endofpacket   (rsp_demux_src1_endofpacket)               //  output,    width = 1,          .endofpacket
	);

	hssi_ss_1_altera_merlin_multiplexer_1922_fiaihyq rsp_mux (
		.clk                 (clock_in_out_clk_clk),                    //   input,    width = 1,       clk.clk
		.reset               (elane_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                       //   input,    width = 1,       src.ready
		.src_valid           (rsp_mux_src_valid),                       //  output,    width = 1,          .valid
		.src_data            (rsp_mux_src_data),                        //  output,  width = 118,          .data
		.src_channel         (rsp_mux_src_channel),                     //  output,    width = 2,          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),               //  output,    width = 1,          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                 //  output,    width = 1,          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                    //  output,    width = 1,     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                    //   input,    width = 1,          .valid
		.sink0_channel       (rsp_demux_src0_channel),                  //   input,    width = 2,          .channel
		.sink0_data          (rsp_demux_src0_data),                     //   input,  width = 118,          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),            //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)               //   input,    width = 1,          .endofpacket
	);

	hssi_ss_1_altera_merlin_multiplexer_1922_fiaihyq rsp_mux_001 (
		.clk                 (clock_in_out_clk_clk),                    //   input,    width = 1,       clk.clk
		.reset               (elane_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (rsp_mux_001_src_ready),                   //   input,    width = 1,       src.ready
		.src_valid           (rsp_mux_001_src_valid),                   //  output,    width = 1,          .valid
		.src_data            (rsp_mux_001_src_data),                    //  output,  width = 118,          .data
		.src_channel         (rsp_mux_001_src_channel),                 //  output,    width = 2,          .channel
		.src_startofpacket   (rsp_mux_001_src_startofpacket),           //  output,    width = 1,          .startofpacket
		.src_endofpacket     (rsp_mux_001_src_endofpacket),             //  output,    width = 1,          .endofpacket
		.sink0_ready         (rsp_demux_src1_ready),                    //  output,    width = 1,     sink0.ready
		.sink0_valid         (rsp_demux_src1_valid),                    //   input,    width = 1,          .valid
		.sink0_channel       (rsp_demux_src1_channel),                  //   input,    width = 2,          .channel
		.sink0_data          (rsp_demux_src1_data),                     //   input,  width = 118,          .data
		.sink0_startofpacket (rsp_demux_src1_startofpacket),            //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (rsp_demux_src1_endofpacket)               //   input,    width = 1,          .endofpacket
	);

endmodule
