
namespace eval dxc_ss_top_ddc_model_DUT_0 {
  proc get_design_libraries {} {
    set libraries [dict create]
    dict set libraries ddc_model_DUT_10           1
    dict set libraries dxc_ss_top_ddc_model_DUT_0 1
    return $libraries
  }
  
  proc get_memory_files {QSYS_SIMDIR} {
    set memory_files [list]
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_rm.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm0.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm1.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm2.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm3.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm4.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm5.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm6.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm7.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm8.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm9.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm10.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm11.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm12.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm13.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm14.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm15.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm16.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm17.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm18.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm19.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm20.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm21.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm22.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm23.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm24.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm25.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm26.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm27.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm28.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm29.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm30.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm31.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm32.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm33.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm34.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm35.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm36.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm37.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm38.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm39.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm40.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm41.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm42.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm43.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm44.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm45.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm46.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm47.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm48.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm49.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm50.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm51.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm52.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm53.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm54.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm55.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm56.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm57.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm58.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm59.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm60.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm61.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm62.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm63.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm64.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm65.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm66.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm67.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm68.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm69.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm70.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm71.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm72.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm73.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm74.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm75.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm76.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm77.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm78.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm79.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm80.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm81.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm82.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm83.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm84.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm85.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm86.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm87.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm88.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm89.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm90.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm91.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm92.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm93.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm94.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm95.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm96.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm97.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm98.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm99.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm100.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm101.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm102.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm103.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm104.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm105.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm106.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm107.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm108.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm109.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm110.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm111.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm112.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm113.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm114.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm115.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm116.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm117.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm118.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm119.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm120.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm121.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm122.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm123.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm124.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm125.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm126.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm127.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm128.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm129.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm130.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm131.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm132.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm133.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm134.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm135.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm136.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm137.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm138.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm139.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm140.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm141.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm142.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm143.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm144.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm145.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm146.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm147.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm148.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm149.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm150.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm151.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm152.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm153.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm154.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im_u0_m0_wo0_cm155.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_rm.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm0.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm1.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm2.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm3.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm4.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm5.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm6.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm7.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm8.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm9.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm10.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm11.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm12.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm13.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm14.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm15.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm16.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm17.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm18.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm19.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm20.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm21.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm22.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm23.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm24.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm25.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm26.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm27.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm28.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm29.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm30.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm31.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm32.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm33.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm34.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm35.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm36.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm37.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm38.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm39.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm40.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm41.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm42.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm43.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm44.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm45.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm46.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm47.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm48.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm49.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm50.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm51.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm52.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm53.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm54.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm55.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm56.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm57.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm58.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm59.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm60.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm61.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm62.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm63.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm64.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm65.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm66.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm67.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm68.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm69.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm70.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm71.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm72.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm73.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm74.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm75.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm76.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm77.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm78.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm79.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm80.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm81.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm82.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm83.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm84.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm85.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm86.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm87.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm88.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm89.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm90.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm91.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm92.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm93.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm94.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm95.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm96.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm97.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm98.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm99.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm100.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm101.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm102.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm103.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm104.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm105.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm106.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm107.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm108.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm109.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm110.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm111.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm112.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm113.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm114.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm115.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm116.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm117.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm118.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm119.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm120.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm121.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm122.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm123.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm124.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm125.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm126.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm127.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm128.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm129.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm130.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm131.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm132.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm133.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm134.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm135.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm136.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm137.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm138.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm139.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm140.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm141.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm142.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm143.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm144.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm145.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm146.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm147.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm148.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm149.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm150.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm151.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm152.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm153.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm154.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re_u0_m0_wo0_cm155.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Filter_Reconfig_Lut_lutmem.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_Complex_NCO_readbackMem.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_Complex_NCO_u0_sinTable.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_Complex_NCO_u0_cosTable.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_Complex_NCO_u1_sinTable.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_Complex_NCO_u1_cosTable.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_Complex_NCO_u2_sinTable.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_Complex_NCO_u2_cosTable.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_Complex_NCO_u3_sinTable.hex"]"
    lappend memory_files "[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_Complex_NCO_u3_cosTable.hex"]"
    return $memory_files
  }
  
  proc get_common_design_files {USER_DEFINED_COMPILE_OPTIONS USER_DEFINED_VERILOG_COMPILE_OPTIONS USER_DEFINED_VHDL_COMPILE_OPTIONS QSYS_SIMDIR} {
    set design_files [dict create]
    return $design_files
  }
  
  proc get_design_files {USER_DEFINED_COMPILE_OPTIONS USER_DEFINED_VERILOG_COMPILE_OPTIONS USER_DEFINED_VHDL_COMPILE_OPTIONS QSYS_SIMDIR} {
    set design_files [list]
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/dspba_library_ver.sv"]\"  -work ddc_model_DUT_10"                                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_safe_path_flat_ver.sv"]\"  -work ddc_model_DUT_10"                                 
    lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_safe_path_flat.vhd"]\"  -work ddc_model_DUT_10"                                           
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT.sv"]\"  -work ddc_model_DUT_10"                                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/busFabric_ddc_model_DUT_2ouiflr06j68696x6u0qu5xajz.sv"]\"  -work ddc_model_DUT_10"               
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT.sv"]\"  -work ddc_model_DUT_10"                                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1.sv"]\"  -work ddc_model_DUT_10"                                 
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter.sv"]\"  -work ddc_model_DUT_10"                     
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_Scale_re.sv"]\"  -work ddc_model_DUT_10"
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_Scaleim.sv"]\"  -work ddc_model_DUT_10" 
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_im.sv"]\"  -work ddc_model_DUT_10"      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_chan_filter_re.sv"]\"  -work ddc_model_DUT_10"      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_routing_reg_chan_re.sv"]\"  -work ddc_model_DUT_10" 
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Chan_Filter_routing_reg_chan_re1.sv"]\"  -work ddc_model_DUT_10"
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Chan_Filter_l1_Filter_Reconfig.sv"]\"  -work ddc_model_DUT_10"                 
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_routing_reg_hb72chan_l1.sv"]\"  -work ddc_model_DUT_10"                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1.sv"]\"  -work ddc_model_DUT_10"                                 
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_ComplexMixer.sv"]\"  -work ddc_model_DUT_10"                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_ComplexMixer_Scale.sv"]\"  -work ddc_model_DUT_10"              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_COMPLEX_MIXER1_Complex_NCO.sv"]\"  -work ddc_model_DUT_10"                     
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_Const_sel.sv"]\"  -work ddc_model_DUT_10"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x.sv"]\"  -work ddc_model_DUT_10"                                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_HB1.sv"]\"  -work ddc_model_DUT_10"                                   
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_HB1_HB1_im.sv"]\"  -work ddc_model_DUT_10"                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_HB1_HB1_re.sv"]\"  -work ddc_model_DUT_10"                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_HB1_scale_HB1_im.sv"]\"  -work ddc_model_DUT_10"                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_HB1_scale_HB1_re.sv"]\"  -work ddc_model_DUT_10"                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_HB2.sv"]\"  -work ddc_model_DUT_10"                                   
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_HB2_HB2_im.sv"]\"  -work ddc_model_DUT_10"                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_HB2_HB2_re.sv"]\"  -work ddc_model_DUT_10"                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_HB2_scale_HB2_im.sv"]\"  -work ddc_model_DUT_10"                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_HB2_scale_HB2_re.sv"]\"  -work ddc_model_DUT_10"                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../ddc_model_DUT_10/sim/ddc_model_DUT_DUT_DDC_l1_x_routing_reg_hb62hb7.sv"]\"  -work ddc_model_DUT_10"                   
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/dxc_ss_top_ddc_model_DUT_0.v"]\"  -work dxc_ss_top_ddc_model_DUT_0"                                                          
    return $design_files
  }
  
  proc get_non_duplicate_elab_option {ELAB_OPTIONS NEW_ELAB_OPTION} {
    set IS_DUPLICATE [string first $NEW_ELAB_OPTION $ELAB_OPTIONS]
    if {$IS_DUPLICATE == -1} {
      return $NEW_ELAB_OPTION
    } else {
      return ""
    }
  }
  
  
  proc get_elab_options {SIMULATOR_TOOL_BITNESS} {
    set ELAB_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    append ELAB_OPTIONS { -t fs}
    return $ELAB_OPTIONS
  }
  
  
  proc get_sim_options {SIMULATOR_TOOL_BITNESS} {
    set SIM_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $SIM_OPTIONS
  }
  
  
  proc get_env_variables {SIMULATOR_TOOL_BITNESS} {
    set ENV_VARIABLES [dict create]
    set LD_LIBRARY_PATH [dict create]
    dict set ENV_VARIABLES "LD_LIBRARY_PATH" $LD_LIBRARY_PATH
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $ENV_VARIABLES
  }
  
  
  proc normalize_path {FILEPATH} {
      if {[catch { package require fileutil } err]} { 
          return $FILEPATH 
      } 
      set path [fileutil::lexnormalize [file join [pwd] $FILEPATH]]  
      if {[file pathtype $FILEPATH] eq "relative"} { 
          set path [fileutil::relative [pwd] $path] 
      } 
      return $path 
  } 
  proc get_dpi_libraries {QSYS_SIMDIR} {
    set libraries [dict create]
    
    return $libraries
  }
  
}
