// ecpri_oran_top_reset_bridge_csr.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module ecpri_oran_top_reset_bridge_csr (
		input  wire  clk,       //       clk.clk,   Clock Input
		input  wire  in_reset,  //  in_reset.reset, Reset Input
		output wire  out_reset  // out_reset.reset, Reset Output
	);

	assign out_reset = in_reset;

endmodule
