// -----------------------------------------------------------------------------
//  Generated by Magillem, from Arteris IPD division
//  Version: 5.16.0 (20230705092541_5.16.0)
//  Date   : 2024-11-03 20:44:23
// -----------------------------------------------------------------------------
//  Verilog Register Bank
// -----------------------------------------------------------------------------
//  Component Name: Oran_SS_Registers
//  File Ref      : /nfs/site/disks/ceg_user_bkhantwa/ipxact/new/csrgen_output/_workspace_mrv_gen_py_/xmlProject/_local_copy_Vendor_Library_Oran_SS_Registers_1.0.xml
//  Protocol      : AVALON
//  Wait State    : WS1_OUTPUT
// -----------------------------------------------------------------------------

module Oran_SS_Registers(

   // ecpri_ip_version.ecpri_ip_version
   input wire [31:0] ecpri_ip_version_ecpri_ip_version_i,
   // oran_ip_version.oran_ip_version
   input wire [31:0] oran_ip_version_oran_ip_version_i,
   
   input wire [31:0] coupling_statistics_register ,
   // fh_comp_ip_version.fh_comp_ip_version
   input wire [31:0] fh_comp_ip_version_fh_comp_ip_version_i,
   // coupling_version.coupling_version
   input wire [31:0] coupling_version_coupling_version_i,
   // dl_eaxc_id0.dl_eaxc_id0
   output reg [15:0] dl_eaxc_id0_dl_eaxc_id0,
   // dl_eaxc_id1.dl_eaxc_id1
   output reg [15:0] dl_eaxc_id1_dl_eaxc_id1,
   // dl_eaxc_id2.dl_eaxc_id2
   output reg [15:0] dl_eaxc_id2_dl_eaxc_id2,
   // dl_eaxc_id3.dl_eaxc_id3
   output reg [15:0] dl_eaxc_id3_dl_eaxc_id3,
   // dl_eaxc_id4.dl_eaxc_id4
   output reg [15:0] dl_eaxc_id4_dl_eaxc_id4,
   // dl_eaxc_id5.dl_eaxc_id5
   output reg [15:0] dl_eaxc_id5_dl_eaxc_id5,
   // dl_eaxc_id6.dl_eaxc_id6
   output reg [15:0] dl_eaxc_id6_dl_eaxc_id6,
   // dl_eaxc_id7.dl_eaxc_id7
   output reg [15:0] dl_eaxc_id7_dl_eaxc_id7,
   // ul_eaxc_id0.ul_eaxc_id0
   output reg [15:0] ul_eaxc_id0_ul_eaxc_id0,
   // ul_eaxc_id1.ul_eaxc_id1
   output reg [15:0] ul_eaxc_id1_ul_eaxc_id1,
   // ul_eaxc_id2.ul_eaxc_id2
   output reg [15:0] ul_eaxc_id2_ul_eaxc_id2,
   // ul_eaxc_id3.ul_eaxc_id3
   output reg [15:0] ul_eaxc_id3_ul_eaxc_id3,
   // ul_eaxc_id4.ul_eaxc_id4
   output reg [15:0] ul_eaxc_id4_ul_eaxc_id4,
   // ul_eaxc_id5.ul_eaxc_id5
   output reg [15:0] ul_eaxc_id5_ul_eaxc_id5,
   // ul_eaxc_id6.ul_eaxc_id6
   output reg [15:0] ul_eaxc_id6_ul_eaxc_id6,
   // ul_eaxc_id7.ul_eaxc_id7
   output reg [15:0] ul_eaxc_id7_ul_eaxc_id7,
   // ul_eaxc_id8.ul_eaxc_id8
   output reg [15:0] ul_eaxc_id8_ul_eaxc_id8,
   // ul_eaxc_id9.ul_eaxc_id9
   output reg [15:0] ul_eaxc_id9_ul_eaxc_id9,
   // ul_eaxc_id10.ul_eaxc_id10
   output reg [15:0] ul_eaxc_id10_ul_eaxc_id10,
   // ul_eaxc_id11.ul_eaxc_id11
   output reg [15:0] ul_eaxc_id11_ul_eaxc_id11,
   // ul_eaxc_id12.ul_eaxc_id12
   output reg [15:0] ul_eaxc_id12_ul_eaxc_id12,
   // ul_eaxc_id13.ul_eaxc_id13
   output reg [15:0] ul_eaxc_id13_ul_eaxc_id13,
   // ul_eaxc_id14.ul_eaxc_id14
   output reg [15:0] ul_eaxc_id14_ul_eaxc_id14,
   // ul_eaxc_id15.ul_eaxc_id15
   output reg [15:0] ul_eaxc_id15_ul_eaxc_id15,
   // intr_clear.intr_clear_cplane
   output reg intr_clear_intr_clear_cplane,
   // intr_clear.intr_clear_uplane
   output reg intr_clear_intr_clear_uplane,
   // intr_clear.fifo_full_intr_clear
   output reg intr_clear_fifo_full_intr_clear,
   // intr_mask.intr_mask_cplane
   output reg intr_mask_intr_mask_cplane,
   // intr_mask.intr_mask_uplane
   output reg intr_mask_intr_mask_uplane,
   // intr_mask.fifo_full_intr_mask
   output reg intr_mask_fifo_full_intr_mask,
   // intr_idle_ms.intr_idle_time_ms
   output reg [11:0] intr_idle_ms_intr_idle_time_ms,
   // intr_register.timeout_cntr_intr_cplane
   input wire intr_register_timeout_cntr_intr_cplane_i,
   // intr_register.timeout_cntr_intr_uplane
   input wire intr_register_timeout_cntr_intr_uplane_i,
   // intr_register.fifo_full_intr
   input wire intr_register_fifo_full_intr_i,
   // coupling_err_clear.coupling_err_clear
   output reg coupling_err_clear_coupling_err_clear,
   // pusch_coupling_status.pusch_state
   input wire [3:0] pusch_coupling_status_pusch_state_i,
   // pusch_coupling_status.pusch_first_cplane_detect
   input wire pusch_coupling_status_pusch_first_cplane_detect_i,
   // pusch_coupling_status.pusch_sf_slot_match
   input wire pusch_coupling_status_pusch_sf_slot_match_i,
   // pusch_coupling_status.pusch_wr_memory_location
   input wire pusch_coupling_status_pusch_wr_memory_location_i,
   // pusch_coupling_status.pusch_rd_memory_location
   input wire pusch_coupling_status_pusch_rd_memory_location_i,
   // pusch_coupling_status.invalid_PUSCH_eAxC
   input wire pusch_coupling_status_invalid_PUSCH_eAxC_i,
   // pusch_coupling_status.PUSCH_data_arrived_eth
   input wire pusch_coupling_status_PUSCH_data_arrived_eth_i,
   // pusch_coupling_status.PUSCH_data_processed
   input wire pusch_coupling_status_PUSCH_data_processed_i,
   // pusch_coupling_status.pusch_fifo_full
   input wire pusch_coupling_status_pusch_fifo_full_i,
   // pusch_coupling_status.pusch_eAxC_Flag
   input wire pusch_coupling_status_pusch_eAxC_Flag_i,
   // pusch_coupling_status.pusch_avst_source_ready
   input wire pusch_coupling_status_pusch_avst_source_ready_i,
   // pusch_coupling_status.pusch_ram_rd_valid
   input wire pusch_coupling_status_pusch_ram_rd_valid_i,
   // pusch_coupling_status.pusch_ram_rdready_all
   input wire pusch_coupling_status_pusch_ram_rdready_all_i,
   // pusch_coupling_status.cc1_enable
   input wire pusch_coupling_status_cc1_enable_i,
   // pusch_coupling_status.cc2_enable
   input wire pusch_coupling_status_cc2_enable_i,
   // pusch_coupling_status.prb_state
   input wire [2:0] pusch_coupling_status_prb_state_i,
   // fifo_full_flag.cu_plane_coupling_pusch_ram_write_full
   input wire fifo_full_flag_cu_plane_coupling_pusch_ram_write_full_i,
   // fifo_full_flag.cu_plane_coupling_prach_ram_write_full
   input wire fifo_full_flag_cu_plane_coupling_prach_ram_write_full_i,
   // fifo_full_flag.ul_arb_out_fifo_full
   input wire fifo_full_flag_ul_arb_out_fifo_full_i,
   // decomp_fsoffset.decomp_fsoffset
   output reg [3:0] decomp_fsoffset_decomp_fsoffset,
   // comp_fsoffset.comp_fsoffset
   output reg [3:0] comp_fsoffset_comp_fsoffset,
   // control_xran_timestamp.capture_start
   output reg control_xran_timestamp_capture_start,
   // profiling_status.ram_rdusedw
   input wire [12:0] profiling_status_ram_rdusedw_i,
   // profiling_status.rdempty
   input wire profiling_status_rdempty_i,
   // timestamp_mux.timestamp_mux
   output reg timestamp_mux_timestamp_mux,
   // prach_coupling_status.prach_state
   input wire [3:0] prach_coupling_status_prach_state_i,
   // prach_coupling_status.prach_first_cplane_detect
   input wire prach_coupling_status_prach_first_cplane_detect_i,
   // prach_coupling_status.prach_first_uplane_detect
   input wire prach_coupling_status_prach_first_uplane_detect_i,
   // prach_coupling_status.prach_wr_memory_location
   input wire prach_coupling_status_prach_wr_memory_location_i,
   // prach_coupling_status.prach_rd_memory_location
   input wire prach_coupling_status_prach_rd_memory_location_i,
   // prach_coupling_status.invalid_PRACH_eaxc
   input wire prach_coupling_status_invalid_PRACH_eaxc_i,
   // prach_coupling_status.prach_invalid_num_of_cplane
   input wire prach_coupling_status_prach_invalid_num_of_cplane_i,
   // prach_coupling_status.ul_start_2d
   input wire prach_coupling_status_ul_start_2d_i,
   // prach_coupling_status.prach_data_received
   input wire prach_coupling_status_prach_data_received_i,
   // prach_coupling_status.prach_data_processed
   input wire prach_coupling_status_prach_data_processed_i,
   // prach_coupling_status.prach_fifo_full
   input wire prach_coupling_status_prach_fifo_full_i,
   // prach_coupling_status.prach_eAxC_Flag
   input wire prach_coupling_status_prach_eAxC_Flag_i,
   // prach_coupling_status.prach_avst_source_ready
   input wire prach_coupling_status_prach_avst_source_ready_i,
   // arbiter_cfg.ctrl
   output reg arbiter_cfg_ctrl,
   // arbiter_cfg.ready
   input wire arbiter_cfg_ready_i,
   // arbiter_prio1.pusch_priority
   output reg [1:0] arbiter_prio1_pusch_priority,
   // arbiter_prio1.prach_priority
   output reg [1:0] arbiter_prio1_prach_priority,

   // Bus interface
   input wire clk,
   input wire reset,
   input wire [31:0] writedata,
   input wire read,
   input wire write,
   input wire [3:0] byteenable,
   output reg [31:0] readdata,
   output reg readdatavalid,
   input wire [8:0] address
);

wire reset_n = !reset;

// -----------------------------------------------------------------------------
// Protocol management
// -----------------------------------------------------------------------------

reg [31:0] rdata_comb;
always @(negedge reset_n, posedge clk)
   if (!reset_n) readdata[31:0] <= 32'h00000000; else readdata[31:0] <= rdata_comb[31:0];

// Read data is always valid the cycle after read transaction is asserted
always @(negedge reset_n, posedge clk)
   if (!reset_n) readdatavalid <= 1'b0; else readdatavalid <= read;

wire we = write;
wire re = read;
wire [8:0] addr = address[8:0];
wire [31:0] din = writedata[31:0];

// -----------------------------------------------------------------------------
// Write byte enables
// -----------------------------------------------------------------------------

// Register dl_eaxc_id0
wire [1:0] we_dl_eaxc_id0 = we & (addr[8:0] == 9'h010) ? byteenable[1:0] : {2{1'b0}};
// Register dl_eaxc_id1
wire [1:0] we_dl_eaxc_id1 = we & (addr[8:0] == 9'h014) ? byteenable[1:0] : {2{1'b0}};
// Register dl_eaxc_id2
wire [1:0] we_dl_eaxc_id2 = we & (addr[8:0] == 9'h018) ? byteenable[1:0] : {2{1'b0}};
// Register dl_eaxc_id3
wire [1:0] we_dl_eaxc_id3 = we & (addr[8:0] == 9'h01c) ? byteenable[1:0] : {2{1'b0}};
// Register dl_eaxc_id4
wire [1:0] we_dl_eaxc_id4 = we & (addr[8:0] == 9'h020) ? byteenable[1:0] : {2{1'b0}};
// Register dl_eaxc_id5
wire [1:0] we_dl_eaxc_id5 = we & (addr[8:0] == 9'h024) ? byteenable[1:0] : {2{1'b0}};
// Register dl_eaxc_id6
wire [1:0] we_dl_eaxc_id6 = we & (addr[8:0] == 9'h028) ? byteenable[1:0] : {2{1'b0}};
// Register dl_eaxc_id7
wire [1:0] we_dl_eaxc_id7 = we & (addr[8:0] == 9'h02c) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id0
wire [1:0] we_ul_eaxc_id0 = we & (addr[8:0] == 9'h030) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id1
wire [1:0] we_ul_eaxc_id1 = we & (addr[8:0] == 9'h034) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id2
wire [1:0] we_ul_eaxc_id2 = we & (addr[8:0] == 9'h038) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id3
wire [1:0] we_ul_eaxc_id3 = we & (addr[8:0] == 9'h03c) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id4
wire [1:0] we_ul_eaxc_id4 = we & (addr[8:0] == 9'h040) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id5
wire [1:0] we_ul_eaxc_id5 = we & (addr[8:0] == 9'h044) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id6
wire [1:0] we_ul_eaxc_id6 = we & (addr[8:0] == 9'h048) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id7
wire [1:0] we_ul_eaxc_id7 = we & (addr[8:0] == 9'h04c) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id8
wire [1:0] we_ul_eaxc_id8 = we & (addr[8:0] == 9'h050) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id9
wire [1:0] we_ul_eaxc_id9 = we & (addr[8:0] == 9'h054) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id10
wire [1:0] we_ul_eaxc_id10 = we & (addr[8:0] == 9'h058) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id11
wire [1:0] we_ul_eaxc_id11 = we & (addr[8:0] == 9'h05c) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id12
wire [1:0] we_ul_eaxc_id12 = we & (addr[8:0] == 9'h060) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id13
wire [1:0] we_ul_eaxc_id13 = we & (addr[8:0] == 9'h064) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id14
wire [1:0] we_ul_eaxc_id14 = we & (addr[8:0] == 9'h068) ? byteenable[1:0] : {2{1'b0}};
// Register ul_eaxc_id15
wire [1:0] we_ul_eaxc_id15 = we & (addr[8:0] == 9'h06c) ? byteenable[1:0] : {2{1'b0}};
// Register intr_clear
wire we_intr_clear = we & (addr[8:0] == 9'h070) ? byteenable[0] : 1'b0;
// Register intr_mask
wire we_intr_mask = we & (addr[8:0] == 9'h074) ? byteenable[0] : 1'b0;
// Register intr_idle_ms
wire [1:0] we_intr_idle_ms = we & (addr[8:0] == 9'h078) ? byteenable[1:0] : {2{1'b0}};
// Register coupling_err_clear
wire we_coupling_err_clear = we & (addr[8:0] == 9'h080) ? byteenable[0] : 1'b0;
// Register decomp_fsoffset
wire we_decomp_fsoffset = we & (addr[8:0] == 9'h08c) ? byteenable[0] : 1'b0;
// Register comp_fsoffset
wire we_comp_fsoffset = we & (addr[8:0] == 9'h090) ? byteenable[0] : 1'b0;
// Register control_xran_timestamp
wire we_control_xran_timestamp = we & (addr[8:0] == 9'h094) ? byteenable[0] : 1'b0;
// Register timestamp_mux
wire we_timestamp_mux = we & (addr[8:0] == 9'h09c) ? byteenable[0] : 1'b0;
// Register arbiter_cfg
wire we_arbiter_cfg = we & (addr[8:0] == 9'h100) ? byteenable[0] : 1'b0;
// Register arbiter_prio1
wire we_arbiter_prio1 = we & (addr[8:0] == 9'h104) ? byteenable[0] : 1'b0;

// -----------------------------------------------------------------------------
// Read byte enables
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Register ecpri_ip_version implementation
// -----------------------------------------------------------------------------

// ecpri_ip_version_ecpri_ip_version
//    bitfield description: Ecpri Ip Version
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 32'h00000000
//    inputPort           : ecpri_ip_version_ecpri_ip_version_i
//
// No register generated

// -----------------------------------------------------------------------------
// Register oran_ip_version implementation
// -----------------------------------------------------------------------------

// oran_ip_version_oran_ip_version
//    bitfield description: oRAN IP Version
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 32'h00000000
//    inputPort           : oran_ip_version_oran_ip_version_i
//
// No register generated

// -----------------------------------------------------------------------------
// Register fh_comp_ip_version implementation
// -----------------------------------------------------------------------------

// fh_comp_ip_version_fh_comp_ip_version
//    bitfield description: FH Compression IP Version
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 32'h00000000
//    inputPort           : fh_comp_ip_version_fh_comp_ip_version_i
//
// No register generated

// -----------------------------------------------------------------------------
// Register coupling_version implementation
// -----------------------------------------------------------------------------

// coupling_version_coupling_version
//    bitfield description: Coupling version
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 32'h00000000
//    inputPort           : coupling_version_coupling_version_i
//
// No register generated

// -----------------------------------------------------------------------------
// Register dl_eaxc_id0 implementation
// -----------------------------------------------------------------------------

// dl_eaxc_id0_dl_eaxc_id0
//    bitfield description: Bits [15:0] - DL AxC Configure id0
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0000

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      dl_eaxc_id0_dl_eaxc_id0 <= 16'h0000;
   end
   else begin
      if (we_dl_eaxc_id0[0]) begin
         dl_eaxc_id0_dl_eaxc_id0[7:0] <= din[7:0];
      end
      if (we_dl_eaxc_id0[1]) begin
         dl_eaxc_id0_dl_eaxc_id0[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register dl_eaxc_id1 implementation
// -----------------------------------------------------------------------------

// dl_eaxc_id1_dl_eaxc_id1
//    bitfield description: Bits [15:0] - DL AxC Configure id1
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0001

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      dl_eaxc_id1_dl_eaxc_id1 <= 16'h0001;
   end
   else begin
      if (we_dl_eaxc_id1[0]) begin
         dl_eaxc_id1_dl_eaxc_id1[7:0] <= din[7:0];
      end
      if (we_dl_eaxc_id1[1]) begin
         dl_eaxc_id1_dl_eaxc_id1[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register dl_eaxc_id2 implementation
// -----------------------------------------------------------------------------

// dl_eaxc_id2_dl_eaxc_id2
//    bitfield description: Bits [15:0] - DL AxC Configure id2
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0002

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      dl_eaxc_id2_dl_eaxc_id2 <= 16'h0002;
   end
   else begin
      if (we_dl_eaxc_id2[0]) begin
         dl_eaxc_id2_dl_eaxc_id2[7:0] <= din[7:0];
      end
      if (we_dl_eaxc_id2[1]) begin
         dl_eaxc_id2_dl_eaxc_id2[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register dl_eaxc_id3 implementation
// -----------------------------------------------------------------------------

// dl_eaxc_id3_dl_eaxc_id3
//    bitfield description: Bits [15:0] - DL AxC Configure id3
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0003

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      dl_eaxc_id3_dl_eaxc_id3 <= 16'h0003;
   end
   else begin
      if (we_dl_eaxc_id3[0]) begin
         dl_eaxc_id3_dl_eaxc_id3[7:0] <= din[7:0];
      end
      if (we_dl_eaxc_id3[1]) begin
         dl_eaxc_id3_dl_eaxc_id3[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register dl_eaxc_id4 implementation
// -----------------------------------------------------------------------------

// dl_eaxc_id4_dl_eaxc_id4
//    bitfield description: Bits [15:0] - DL AxC Configure id4
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0004

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      dl_eaxc_id4_dl_eaxc_id4 <= 16'h0004;
   end
   else begin
      if (we_dl_eaxc_id4[0]) begin
         dl_eaxc_id4_dl_eaxc_id4[7:0] <= din[7:0];
      end
      if (we_dl_eaxc_id4[1]) begin
         dl_eaxc_id4_dl_eaxc_id4[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register dl_eaxc_id5 implementation
// -----------------------------------------------------------------------------

// dl_eaxc_id5_dl_eaxc_id5
//    bitfield description: Bits [15:0] - DL AxC Configure id5
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0005

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      dl_eaxc_id5_dl_eaxc_id5 <= 16'h0005;
   end
   else begin
      if (we_dl_eaxc_id5[0]) begin
         dl_eaxc_id5_dl_eaxc_id5[7:0] <= din[7:0];
      end
      if (we_dl_eaxc_id5[1]) begin
         dl_eaxc_id5_dl_eaxc_id5[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register dl_eaxc_id6 implementation
// -----------------------------------------------------------------------------

// dl_eaxc_id6_dl_eaxc_id6
//    bitfield description: Bits [15:0] - DL AxC Configure id6
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0006

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      dl_eaxc_id6_dl_eaxc_id6 <= 16'h0006;
   end
   else begin
      if (we_dl_eaxc_id6[0]) begin
         dl_eaxc_id6_dl_eaxc_id6[7:0] <= din[7:0];
      end
      if (we_dl_eaxc_id6[1]) begin
         dl_eaxc_id6_dl_eaxc_id6[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register dl_eaxc_id7 implementation
// -----------------------------------------------------------------------------

// dl_eaxc_id7_dl_eaxc_id7
//    bitfield description: Bits [15:0] - DL AxC Configure id7
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0007

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      dl_eaxc_id7_dl_eaxc_id7 <= 16'h0007;
   end
   else begin
      if (we_dl_eaxc_id7[0]) begin
         dl_eaxc_id7_dl_eaxc_id7[7:0] <= din[7:0];
      end
      if (we_dl_eaxc_id7[1]) begin
         dl_eaxc_id7_dl_eaxc_id7[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id0 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id0_ul_eaxc_id0
//    bitfield description: Bits [15:0] - UL AxC Configure id0
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0000

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id0_ul_eaxc_id0 <= 16'h0000;
   end
   else begin
      if (we_ul_eaxc_id0[0]) begin
         ul_eaxc_id0_ul_eaxc_id0[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id0[1]) begin
         ul_eaxc_id0_ul_eaxc_id0[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id1 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id1_ul_eaxc_id1
//    bitfield description: Bits [15:0] - UL AxC Configure id1
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0001

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id1_ul_eaxc_id1 <= 16'h0001;
   end
   else begin
      if (we_ul_eaxc_id1[0]) begin
         ul_eaxc_id1_ul_eaxc_id1[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id1[1]) begin
         ul_eaxc_id1_ul_eaxc_id1[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id2 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id2_ul_eaxc_id2
//    bitfield description: Bits [15:0] - UL AxC Configure id2
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0002

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id2_ul_eaxc_id2 <= 16'h0002;
   end
   else begin
      if (we_ul_eaxc_id2[0]) begin
         ul_eaxc_id2_ul_eaxc_id2[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id2[1]) begin
         ul_eaxc_id2_ul_eaxc_id2[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id3 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id3_ul_eaxc_id3
//    bitfield description: Bits [15:0] - UL AxC Configure id3
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0003

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id3_ul_eaxc_id3 <= 16'h0003;
   end
   else begin
      if (we_ul_eaxc_id3[0]) begin
         ul_eaxc_id3_ul_eaxc_id3[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id3[1]) begin
         ul_eaxc_id3_ul_eaxc_id3[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id4 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id4_ul_eaxc_id4
//    bitfield description: Bits [15:0] - UL AxC Configure id4
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0004

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id4_ul_eaxc_id4 <= 16'h0004;
   end
   else begin
      if (we_ul_eaxc_id4[0]) begin
         ul_eaxc_id4_ul_eaxc_id4[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id4[1]) begin
         ul_eaxc_id4_ul_eaxc_id4[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id5 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id5_ul_eaxc_id5
//    bitfield description: Bits [15:0] - UL AxC Configure id5
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0005

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id5_ul_eaxc_id5 <= 16'h0005;
   end
   else begin
      if (we_ul_eaxc_id5[0]) begin
         ul_eaxc_id5_ul_eaxc_id5[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id5[1]) begin
         ul_eaxc_id5_ul_eaxc_id5[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id6 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id6_ul_eaxc_id6
//    bitfield description: Bits [15:0] - UL AxC Configure id6
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0006

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id6_ul_eaxc_id6 <= 16'h0006;
   end
   else begin
      if (we_ul_eaxc_id6[0]) begin
         ul_eaxc_id6_ul_eaxc_id6[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id6[1]) begin
         ul_eaxc_id6_ul_eaxc_id6[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id7 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id7_ul_eaxc_id7
//    bitfield description: Bits [15:0] - UL AxC Configure id7
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0007

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id7_ul_eaxc_id7 <= 16'h0007;
   end
   else begin
      if (we_ul_eaxc_id7[0]) begin
         ul_eaxc_id7_ul_eaxc_id7[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id7[1]) begin
         ul_eaxc_id7_ul_eaxc_id7[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id8 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id8_ul_eaxc_id8
//    bitfield description: Bits [15:0] - UL AxC Configure id8
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0008

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id8_ul_eaxc_id8 <= 16'h0008;
   end
   else begin
      if (we_ul_eaxc_id8[0]) begin
         ul_eaxc_id8_ul_eaxc_id8[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id8[1]) begin
         ul_eaxc_id8_ul_eaxc_id8[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id9 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id9_ul_eaxc_id9
//    bitfield description: Bits [15:0] - UL AxC Configure id9
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0009

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id9_ul_eaxc_id9 <= 16'h0009;
   end
   else begin
      if (we_ul_eaxc_id9[0]) begin
         ul_eaxc_id9_ul_eaxc_id9[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id9[1]) begin
         ul_eaxc_id9_ul_eaxc_id9[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id10 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id10_ul_eaxc_id10
//    bitfield description: Bits [15:0] - UL AxC Configure id10
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h000a

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id10_ul_eaxc_id10 <= 16'h000a;
   end
   else begin
      if (we_ul_eaxc_id10[0]) begin
         ul_eaxc_id10_ul_eaxc_id10[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id10[1]) begin
         ul_eaxc_id10_ul_eaxc_id10[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id11 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id11_ul_eaxc_id11
//    bitfield description: Bits [15:0] - UL AxC Configure id11
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h000b

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id11_ul_eaxc_id11 <= 16'h000b;
   end
   else begin
      if (we_ul_eaxc_id11[0]) begin
         ul_eaxc_id11_ul_eaxc_id11[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id11[1]) begin
         ul_eaxc_id11_ul_eaxc_id11[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id12 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id12_ul_eaxc_id12
//    bitfield description: Bits [15:0] - UL AxC Configure id12
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h000c

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id12_ul_eaxc_id12 <= 16'h000c;
   end
   else begin
      if (we_ul_eaxc_id12[0]) begin
         ul_eaxc_id12_ul_eaxc_id12[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id12[1]) begin
         ul_eaxc_id12_ul_eaxc_id12[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id13 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id13_ul_eaxc_id13
//    bitfield description: Bits [15:0] - UL AxC Configure id13
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h000d

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id13_ul_eaxc_id13 <= 16'h000d;
   end
   else begin
      if (we_ul_eaxc_id13[0]) begin
         ul_eaxc_id13_ul_eaxc_id13[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id13[1]) begin
         ul_eaxc_id13_ul_eaxc_id13[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id14 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id14_ul_eaxc_id14
//    bitfield description: Bits [15:0] - UL AxC Configure id14
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h000e

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id14_ul_eaxc_id14 <= 16'h000e;
   end
   else begin
      if (we_ul_eaxc_id14[0]) begin
         ul_eaxc_id14_ul_eaxc_id14[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id14[1]) begin
         ul_eaxc_id14_ul_eaxc_id14[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register ul_eaxc_id15 implementation
// -----------------------------------------------------------------------------

// ul_eaxc_id15_ul_eaxc_id15
//    bitfield description: Bits [15:0] - UL AxC Configure id15
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h000f

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      ul_eaxc_id15_ul_eaxc_id15 <= 16'h000f;
   end
   else begin
      if (we_ul_eaxc_id15[0]) begin
         ul_eaxc_id15_ul_eaxc_id15[7:0] <= din[7:0];
      end
      if (we_ul_eaxc_id15[1]) begin
         ul_eaxc_id15_ul_eaxc_id15[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register intr_clear implementation
// -----------------------------------------------------------------------------

// intr_clear_intr_clear_cplane
//    bitfield description: clear/unclear cplane timeout intr
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 1'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      intr_clear_intr_clear_cplane <= 1'h0;
   end
   else begin
      if (we_intr_clear) begin
         intr_clear_intr_clear_cplane <= din[0];
      end
   end

// intr_clear_intr_clear_uplane
//    bitfield description: clear/unclear uplane timeout intr
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 1'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      intr_clear_intr_clear_uplane <= 1'h0;
   end
   else begin
      if (we_intr_clear) begin
         intr_clear_intr_clear_uplane <= din[1];
      end
   end

// intr_clear_fifo_full_intr_clear
//    bitfield description: clear/unclear fifo full intr
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 1'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      intr_clear_fifo_full_intr_clear <= 1'h0;
   end
   else begin
      if (we_intr_clear) begin
         intr_clear_fifo_full_intr_clear <= din[2];
      end
   end

// -----------------------------------------------------------------------------
// Register intr_mask implementation
// -----------------------------------------------------------------------------

// intr_mask_intr_mask_cplane
//    bitfield description: mask/unmask cplane timeout intr
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 1'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      intr_mask_intr_mask_cplane <= 1'h0;
   end
   else begin
      if (we_intr_mask) begin
         intr_mask_intr_mask_cplane <= din[0];
      end
   end

// intr_mask_intr_mask_uplane
//    bitfield description: mask/unmask uplane timeout intr
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 1'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      intr_mask_intr_mask_uplane <= 1'h0;
   end
   else begin
      if (we_intr_mask) begin
         intr_mask_intr_mask_uplane <= din[1];
      end
   end

// intr_mask_fifo_full_intr_mask
//    bitfield description: mask/unmask fifo full intr
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 1'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      intr_mask_fifo_full_intr_mask <= 1'h0;
   end
   else begin
      if (we_intr_mask) begin
         intr_mask_fifo_full_intr_mask <= din[2];
      end
   end

// -----------------------------------------------------------------------------
// Register intr_idle_ms implementation
// -----------------------------------------------------------------------------

// intr_idle_ms_intr_idle_time_ms
//    bitfield description: timeout cntr intr_idle_time_in_ms
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 12'h0a0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      intr_idle_ms_intr_idle_time_ms <= 12'h0a0;
   end
   else begin
      if (we_intr_idle_ms[0]) begin
         intr_idle_ms_intr_idle_time_ms[7:0] <= din[7:0];
      end
      if (we_intr_idle_ms[1]) begin
         intr_idle_ms_intr_idle_time_ms[11:8] <= din[11:8];
      end
   end

// -----------------------------------------------------------------------------
// Register intr_register implementation
// -----------------------------------------------------------------------------

// intr_register_timeout_cntr_intr_cplane
//    bitfield description: timeout cntr intr for cplane pkt
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : intr_register_timeout_cntr_intr_cplane_i
//
// No register generated

// intr_register_timeout_cntr_intr_uplane
//    bitfield description: timeout cntr intr for u plane pk
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : intr_register_timeout_cntr_intr_uplane_i
//
// No register generated

// intr_register_fifo_full_intr
//    bitfield description: fifo full intr
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : intr_register_fifo_full_intr_i
//
// No register generated

// -----------------------------------------------------------------------------
// Register coupling_err_clear implementation
// -----------------------------------------------------------------------------

// coupling_err_clear_coupling_err_clear
//    bitfield description: Clears Coupling Errors
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 1'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      coupling_err_clear_coupling_err_clear <= 1'h0;
   end
   else begin
      if (we_coupling_err_clear) begin
         coupling_err_clear_coupling_err_clear <= din[0];
      end
   end

// -----------------------------------------------------------------------------
// Register pusch_coupling_status implementation
// -----------------------------------------------------------------------------

// pusch_coupling_status_pusch_state
//    bitfield description: Bit [3:0] - pusch_state
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 4'h1
//    inputPort           : pusch_coupling_status_pusch_state_i
//
// No register generated

// pusch_coupling_status_pusch_first_cplane_detect
//    bitfield description: Bit [4] - pusch_first_cplane_detect
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_pusch_first_cplane_detect_i
//
// No register generated

// pusch_coupling_status_pusch_sf_slot_match
//    bitfield description: Bit [5] - pusch_sf_slot_match
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_pusch_sf_slot_match_i
//
// No register generated

// pusch_coupling_status_pusch_wr_memory_location
//    bitfield description: Bit [6] - pusch_wr_memory_location
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_pusch_wr_memory_location_i
//
// No register generated

// pusch_coupling_status_pusch_rd_memory_location
//    bitfield description: Bits [7] - pusch_rd_memory_location
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_pusch_rd_memory_location_i
//
// No register generated

// pusch_coupling_status_invalid_PUSCH_eAxC
//    bitfield description: Bit [8] - invalid_PUSCH_eAxC
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_invalid_PUSCH_eAxC_i
//
// No register generated

// pusch_coupling_status_PUSCH_data_arrived_eth
//    bitfield description: Bit [9] - PUSCH_data_arrived_ethl
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_PUSCH_data_arrived_eth_i
//
// No register generated

// pusch_coupling_status_PUSCH_data_processed
//    bitfield description: Bit [10] - PUSCH_data_processed
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_PUSCH_data_processed_i
//
// No register generated

// pusch_coupling_status_pusch_fifo_full
//    bitfield description: Bit [11] - pusch_fifo_full
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_pusch_fifo_full_i
//
// No register generated

// pusch_coupling_status_pusch_eAxC_Flag
//    bitfield description: Bit [12] - pusch_eAxC_Flag
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_pusch_eAxC_Flag_i
//
// No register generated

// pusch_coupling_status_pusch_avst_source_ready
//    bitfield description: Bit [13] - pusch_avst_source_ready
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_pusch_avst_source_ready_i
//
// No register generated

// pusch_coupling_status_pusch_ram_rd_valid
//    bitfield description: Bit [14] - pusch_ram_rd_valid
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_pusch_ram_rd_valid_i
//
// No register generated

// pusch_coupling_status_pusch_ram_rdready_all
//    bitfield description: Bit [15] - pusch_ram_rdready_all
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : pusch_coupling_status_pusch_ram_rdready_all_i
//
// No register generated

// pusch_coupling_status_cc1_enable
//    bitfield description: Bit [16] - cc1_enable
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h1
//    inputPort           : pusch_coupling_status_cc1_enable_i
//
// No register generated

// pusch_coupling_status_cc2_enable
//    bitfield description: Bit [17] - cc2_enable
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h1
//    inputPort           : pusch_coupling_status_cc2_enable_i
//
// No register generated

// pusch_coupling_status_prb_state
//    bitfield description: Bit[20:18]- prb_state_machine, Bit [31:21] - reserved
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 3'h0
//    inputPort           : pusch_coupling_status_prb_state_i
//
// No register generated

// -----------------------------------------------------------------------------
// Register fifo_full_flag implementation
// -----------------------------------------------------------------------------

// fifo_full_flag_cu_plane_coupling_pusch_ram_write_full
//    bitfield description: Bit [0] -cu_plane_coupling_pusch_ram_write_full
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : fifo_full_flag_cu_plane_coupling_pusch_ram_write_full_i
//
// No register generated

// fifo_full_flag_cu_plane_coupling_prach_ram_write_full
//    bitfield description: Bit [1] -cu_plane_coupling_prach_ram_write_full
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : fifo_full_flag_cu_plane_coupling_prach_ram_write_full_i
//
// No register generated

// fifo_full_flag_ul_arb_out_fifo_full
//    bitfield description: Bit [2] - ul_arb_out_fifo_full
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : fifo_full_flag_ul_arb_out_fifo_full_i
//
// No register generated

// -----------------------------------------------------------------------------
// Register decomp_fsoffset implementation
// -----------------------------------------------------------------------------

// decomp_fsoffset_decomp_fsoffset
//    bitfield description: decomp fsoffset Value
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 4'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      decomp_fsoffset_decomp_fsoffset <= 4'h0;
   end
   else begin
      if (we_decomp_fsoffset) begin
         decomp_fsoffset_decomp_fsoffset[3:0] <= din[3:0];
      end
   end

// -----------------------------------------------------------------------------
// Register comp_fsoffset implementation
// -----------------------------------------------------------------------------

// comp_fsoffset_comp_fsoffset
//    bitfield description: comp fsoffset Value
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 4'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      comp_fsoffset_comp_fsoffset <= 4'h0;
   end
   else begin
      if (we_comp_fsoffset) begin
         comp_fsoffset_comp_fsoffset[3:0] <= din[3:0];
      end
   end

// -----------------------------------------------------------------------------
// Register control_xran_timestamp implementation
// -----------------------------------------------------------------------------

// control_xran_timestamp_capture_start
//    bitfield description: Profiling - Header Logging - Start
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 1'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      control_xran_timestamp_capture_start <= 1'h0;
   end
   else begin
      if (we_control_xran_timestamp) begin
         control_xran_timestamp_capture_start <= din[0];
      end
   end

// -----------------------------------------------------------------------------
// Register profiling_status implementation
// -----------------------------------------------------------------------------

// profiling_status_ram_rdusedw
//    bitfield description: RAM Used Word
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 13'h0000
//    inputPort           : profiling_status_ram_rdusedw_i
//
// No register generated

// profiling_status_rdempty
//    bitfield description: RAM Read Empty
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h1
//    inputPort           : profiling_status_rdempty_i
//
// No register generated

// -----------------------------------------------------------------------------
// Register timestamp_mux implementation
// -----------------------------------------------------------------------------

// timestamp_mux_timestamp_mux
//    bitfield description: Timestamp MUX Selection
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 1'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      timestamp_mux_timestamp_mux <= 1'h0;
   end
   else begin
      if (we_timestamp_mux) begin
         timestamp_mux_timestamp_mux <= din[0];
      end
   end

// -----------------------------------------------------------------------------
// Register prach_coupling_status implementation
// -----------------------------------------------------------------------------

// prach_coupling_status_prach_state
//    bitfield description: Bit [3:0] - prach_state
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 4'h1
//    inputPort           : prach_coupling_status_prach_state_i
//
// No register generated

// prach_coupling_status_prach_first_cplane_detect
//    bitfield description: Bit [4] - prach_first_cplane_detect
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_prach_first_cplane_detect_i
//
// No register generated

// prach_coupling_status_prach_first_uplane_detect
//    bitfield description: Bit [5] - prach_first_uplane_detect
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_prach_first_uplane_detect_i
//
// No register generated

// prach_coupling_status_prach_wr_memory_location
//    bitfield description: Bit [6] - prach_wr_memory_location
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_prach_wr_memory_location_i
//
// No register generated

// prach_coupling_status_prach_rd_memory_location
//    bitfield description: Bit [7] - prach_rd_memory_location
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_prach_rd_memory_location_i
//
// No register generated

// prach_coupling_status_invalid_PRACH_eaxc
//    bitfield description: Bit [8] - invalid_PRACH_eaxc
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_invalid_PRACH_eaxc_i
//
// No register generated

// prach_coupling_status_prach_invalid_num_of_cplane
//    bitfield description: Bit [9] - prach_invalid_num_of_cplane
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_prach_invalid_num_of_cplane_i
//
// No register generated

// prach_coupling_status_ul_start_2d
//    bitfield description: Bit [10] - ul_start_2d
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h1
//    inputPort           : prach_coupling_status_ul_start_2d_i
//
// No register generated

// prach_coupling_status_prach_data_received
//    bitfield description: Bit [11] - prach_data_received
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_prach_data_received_i
//
// No register generated

// prach_coupling_status_prach_data_processed
//    bitfield description: Bit [12] - prach_data_processed
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_prach_data_processed_i
//
// No register generated

// prach_coupling_status_prach_fifo_full
//    bitfield description: Bit [13] - prach_fifo_full
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_prach_fifo_full_i
//
// No register generated

// prach_coupling_status_prach_eAxC_Flag
//    bitfield description: Bit [14] - prach_eAxC_Flag
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_prach_eAxC_Flag_i
//
// No register generated

// prach_coupling_status_prach_avst_source_ready
//    bitfield description: Bit [15] - prach_avst_source_ready, Bit [31:16] - reserved
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : prach_coupling_status_prach_avst_source_ready_i
//
// No register generated

// -----------------------------------------------------------------------------
// Register arbiter_cfg implementation
// -----------------------------------------------------------------------------

// arbiter_cfg_ctrl
//    bitfield description: Bit[0] - Ctrl
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 1'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      arbiter_cfg_ctrl <= 1'h0;
   end
   else begin
      if (we_arbiter_cfg) begin
         arbiter_cfg_ctrl <= din[0];
      end
   end

// arbiter_cfg_ready
//    bitfield description: Bit[1] - Ready
//    customType          : RO
//    hwAccess            : WO
//    reset value         : 1'h0
//    inputPort           : arbiter_cfg_ready_i
//
// No register generated

// -----------------------------------------------------------------------------
// Register arbiter_prio1 implementation
// -----------------------------------------------------------------------------

// arbiter_prio1_pusch_priority
//    bitfield description: Bit[1:0] - PUSCH Priority
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 2'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      arbiter_prio1_pusch_priority <= 2'h0;
   end
   else begin
      if (we_arbiter_prio1) begin
         arbiter_prio1_pusch_priority[1:0] <= din[1:0];
      end
   end

// arbiter_prio1_prach_priority
//    bitfield description: Bit[3:2] - PRACH Priority
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 2'h0

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      arbiter_prio1_prach_priority <= 2'h0;
   end
   else begin
      if (we_arbiter_prio1) begin
         arbiter_prio1_prach_priority[1:0] <= din[3:2];
      end
   end

// -----------------------------------------------------------------------------
// Data read management
// -----------------------------------------------------------------------------

always @(*)
begin
   rdata_comb = 32'h00000000;
   if (re) begin
      case (addr)
         // Register ecpri_ip_version: ecpri_ip_version_ecpri_ip_version (RO)
         9'h000: begin
            rdata_comb[31:0] = ecpri_ip_version_ecpri_ip_version_i[31:0];
         end
         // Register oran_ip_version: oran_ip_version_oran_ip_version (RO)
         9'h004: begin
            rdata_comb[31:0] = oran_ip_version_oran_ip_version_i[31:0];
         end
         // Register fh_comp_ip_version: fh_comp_ip_version_fh_comp_ip_version (RO)
         9'h008: begin
            rdata_comb[31:0] = fh_comp_ip_version_fh_comp_ip_version_i[31:0];
         end
         // Register coupling_version: coupling_version_coupling_version (RO)
         9'h00c: begin
            rdata_comb[31:0] = coupling_version_coupling_version_i[31:0];
         end
         // Register dl_eaxc_id0: dl_eaxc_id0_dl_eaxc_id0 (RW)
         9'h010: begin
            rdata_comb[15:0] = dl_eaxc_id0_dl_eaxc_id0[15:0];
         end
         // Register dl_eaxc_id1: dl_eaxc_id1_dl_eaxc_id1 (RW)
         9'h014: begin
            rdata_comb[15:0] = dl_eaxc_id1_dl_eaxc_id1[15:0];
         end
         // Register dl_eaxc_id2: dl_eaxc_id2_dl_eaxc_id2 (RW)
         9'h018: begin
            rdata_comb[15:0] = dl_eaxc_id2_dl_eaxc_id2[15:0];
         end
         // Register dl_eaxc_id3: dl_eaxc_id3_dl_eaxc_id3 (RW)
         9'h01c: begin
            rdata_comb[15:0] = dl_eaxc_id3_dl_eaxc_id3[15:0];
         end
         // Register dl_eaxc_id4: dl_eaxc_id4_dl_eaxc_id4 (RW)
         9'h020: begin
            rdata_comb[15:0] = dl_eaxc_id4_dl_eaxc_id4[15:0];
         end
         // Register dl_eaxc_id5: dl_eaxc_id5_dl_eaxc_id5 (RW)
         9'h024: begin
            rdata_comb[15:0] = dl_eaxc_id5_dl_eaxc_id5[15:0];
         end
         // Register dl_eaxc_id6: dl_eaxc_id6_dl_eaxc_id6 (RW)
         9'h028: begin
            rdata_comb[15:0] = dl_eaxc_id6_dl_eaxc_id6[15:0];
         end
         // Register dl_eaxc_id7: dl_eaxc_id7_dl_eaxc_id7 (RW)
         9'h02c: begin
            rdata_comb[15:0] = dl_eaxc_id7_dl_eaxc_id7[15:0];
         end
         // Register ul_eaxc_id0: ul_eaxc_id0_ul_eaxc_id0 (RW)
         9'h030: begin
            rdata_comb[15:0] = ul_eaxc_id0_ul_eaxc_id0[15:0];
         end
         // Register ul_eaxc_id1: ul_eaxc_id1_ul_eaxc_id1 (RW)
         9'h034: begin
            rdata_comb[15:0] = ul_eaxc_id1_ul_eaxc_id1[15:0];
         end
         // Register ul_eaxc_id2: ul_eaxc_id2_ul_eaxc_id2 (RW)
         9'h038: begin
            rdata_comb[15:0] = ul_eaxc_id2_ul_eaxc_id2[15:0];
         end
         // Register ul_eaxc_id3: ul_eaxc_id3_ul_eaxc_id3 (RW)
         9'h03c: begin
            rdata_comb[15:0] = ul_eaxc_id3_ul_eaxc_id3[15:0];
         end
         // Register ul_eaxc_id4: ul_eaxc_id4_ul_eaxc_id4 (RW)
         9'h040: begin
            rdata_comb[15:0] = ul_eaxc_id4_ul_eaxc_id4[15:0];
         end
         // Register ul_eaxc_id5: ul_eaxc_id5_ul_eaxc_id5 (RW)
         9'h044: begin
            rdata_comb[15:0] = ul_eaxc_id5_ul_eaxc_id5[15:0];
         end
         // Register ul_eaxc_id6: ul_eaxc_id6_ul_eaxc_id6 (RW)
         9'h048: begin
            rdata_comb[15:0] = ul_eaxc_id6_ul_eaxc_id6[15:0];
         end
         // Register ul_eaxc_id7: ul_eaxc_id7_ul_eaxc_id7 (RW)
         9'h04c: begin
            rdata_comb[15:0] = ul_eaxc_id7_ul_eaxc_id7[15:0];
         end
         // Register ul_eaxc_id8: ul_eaxc_id8_ul_eaxc_id8 (RW)
         9'h050: begin
            rdata_comb[15:0] = ul_eaxc_id8_ul_eaxc_id8[15:0];
         end
         // Register ul_eaxc_id9: ul_eaxc_id9_ul_eaxc_id9 (RW)
         9'h054: begin
            rdata_comb[15:0] = ul_eaxc_id9_ul_eaxc_id9[15:0];
         end
         // Register ul_eaxc_id10: ul_eaxc_id10_ul_eaxc_id10 (RW)
         9'h058: begin
            rdata_comb[15:0] = ul_eaxc_id10_ul_eaxc_id10[15:0];
         end
         // Register ul_eaxc_id11: ul_eaxc_id11_ul_eaxc_id11 (RW)
         9'h05c: begin
            rdata_comb[15:0] = ul_eaxc_id11_ul_eaxc_id11[15:0];
         end
         // Register ul_eaxc_id12: ul_eaxc_id12_ul_eaxc_id12 (RW)
         9'h060: begin
            rdata_comb[15:0] = ul_eaxc_id12_ul_eaxc_id12[15:0];
         end
         // Register ul_eaxc_id13: ul_eaxc_id13_ul_eaxc_id13 (RW)
         9'h064: begin
            rdata_comb[15:0] = ul_eaxc_id13_ul_eaxc_id13[15:0];
         end
         // Register ul_eaxc_id14: ul_eaxc_id14_ul_eaxc_id14 (RW)
         9'h068: begin
            rdata_comb[15:0] = ul_eaxc_id14_ul_eaxc_id14[15:0];
         end
         // Register ul_eaxc_id15: ul_eaxc_id15_ul_eaxc_id15 (RW)
         9'h06c: begin
            rdata_comb[15:0] = ul_eaxc_id15_ul_eaxc_id15[15:0];
         end
         // Register intr_clear: intr_clear_intr_clear_cplane (RW)
         //                      intr_clear_intr_clear_uplane (RW)
         //                      intr_clear_fifo_full_intr_clear (RW)
         9'h070: begin
            rdata_comb[0] = intr_clear_intr_clear_cplane;
            rdata_comb[1] = intr_clear_intr_clear_uplane;
            rdata_comb[2] = intr_clear_fifo_full_intr_clear;
         end
         // Register intr_mask: intr_mask_intr_mask_cplane (RW)
         //                     intr_mask_intr_mask_uplane (RW)
         //                     intr_mask_fifo_full_intr_mask (RW)
         9'h074: begin
            rdata_comb[0] = intr_mask_intr_mask_cplane;
            rdata_comb[1] = intr_mask_intr_mask_uplane;
            rdata_comb[2] = intr_mask_fifo_full_intr_mask;
         end
         // Register intr_idle_ms: intr_idle_ms_intr_idle_time_ms (RW)
         9'h078: begin
            rdata_comb[11:0] = intr_idle_ms_intr_idle_time_ms[11:0];
         end
         // Register intr_register: intr_register_timeout_cntr_intr_cplane (RO)
         //                         intr_register_timeout_cntr_intr_uplane (RO)
         //                         intr_register_fifo_full_intr (RO)
         9'h07c: begin
            rdata_comb[0] = intr_register_timeout_cntr_intr_cplane_i;
            rdata_comb[1] = intr_register_timeout_cntr_intr_uplane_i;
            rdata_comb[2] = intr_register_fifo_full_intr_i;
         end
         // Register coupling_err_clear: coupling_err_clear_coupling_err_clear (RW)
         9'h080: begin
            rdata_comb[0] = coupling_err_clear_coupling_err_clear;
         end
         // Register pusch_coupling_status: pusch_coupling_status_pusch_state (RO)
         //                                 pusch_coupling_status_pusch_first_cplane_detect (RO)
         //                                 pusch_coupling_status_pusch_sf_slot_match (RO)
         //                                 pusch_coupling_status_pusch_wr_memory_location (RO)
         //                                 pusch_coupling_status_pusch_rd_memory_location (RO)
         //                                 pusch_coupling_status_invalid_PUSCH_eAxC (RO)
         //                                 pusch_coupling_status_PUSCH_data_arrived_eth (RO)
         //                                 pusch_coupling_status_PUSCH_data_processed (RO)
         //                                 pusch_coupling_status_pusch_fifo_full (RO)
         //                                 pusch_coupling_status_pusch_eAxC_Flag (RO)
         //                                 pusch_coupling_status_pusch_avst_source_ready (RO)
         //                                 pusch_coupling_status_pusch_ram_rd_valid (RO)
         //                                 pusch_coupling_status_pusch_ram_rdready_all (RO)
         //                                 pusch_coupling_status_cc1_enable (RO)
         //                                 pusch_coupling_status_cc2_enable (RO)
         //                                 pusch_coupling_status_prb_state (RO)
         9'h084: begin
            rdata_comb[3:0] = pusch_coupling_status_pusch_state_i[3:0];
            rdata_comb[4] = pusch_coupling_status_pusch_first_cplane_detect_i;
            rdata_comb[5] = pusch_coupling_status_pusch_sf_slot_match_i;
            rdata_comb[6] = pusch_coupling_status_pusch_wr_memory_location_i;
            rdata_comb[7] = pusch_coupling_status_pusch_rd_memory_location_i;
            rdata_comb[8] = pusch_coupling_status_invalid_PUSCH_eAxC_i;
            rdata_comb[9] = pusch_coupling_status_PUSCH_data_arrived_eth_i;
            rdata_comb[10] = pusch_coupling_status_PUSCH_data_processed_i;
            rdata_comb[11] = pusch_coupling_status_pusch_fifo_full_i;
            rdata_comb[12] = pusch_coupling_status_pusch_eAxC_Flag_i;
            rdata_comb[13] = pusch_coupling_status_pusch_avst_source_ready_i;
            rdata_comb[14] = pusch_coupling_status_pusch_ram_rd_valid_i;
            rdata_comb[15] = pusch_coupling_status_pusch_ram_rdready_all_i;
            rdata_comb[16] = pusch_coupling_status_cc1_enable_i;
            rdata_comb[17] = pusch_coupling_status_cc2_enable_i;
            rdata_comb[20:18] = pusch_coupling_status_prb_state_i[2:0];
         end
         // Register fifo_full_flag: fifo_full_flag_cu_plane_coupling_pusch_ram_write_full (RO)
         //                          fifo_full_flag_cu_plane_coupling_prach_ram_write_full (RO)
         //                          fifo_full_flag_ul_arb_out_fifo_full (RO)
         9'h088: begin
            rdata_comb[0] = fifo_full_flag_cu_plane_coupling_pusch_ram_write_full_i;
            rdata_comb[1] = fifo_full_flag_cu_plane_coupling_prach_ram_write_full_i;
            rdata_comb[2] = fifo_full_flag_ul_arb_out_fifo_full_i;
         end
         // Register decomp_fsoffset: decomp_fsoffset_decomp_fsoffset (RW)
         9'h08c: begin
            rdata_comb[3:0] = decomp_fsoffset_decomp_fsoffset[3:0];
         end
         // Register comp_fsoffset: comp_fsoffset_comp_fsoffset (RW)
         9'h090: begin
            rdata_comb[3:0] = comp_fsoffset_comp_fsoffset[3:0];
         end
         // Register control_xran_timestamp: control_xran_timestamp_capture_start (RW)
         9'h094: begin
            rdata_comb[0] = control_xran_timestamp_capture_start;
         end
         // Register profiling_status: profiling_status_ram_rdusedw (RO)
         //                            profiling_status_rdempty (RO)
         9'h098: begin
            rdata_comb[12:0] = profiling_status_ram_rdusedw_i[12:0];
            rdata_comb[13] = profiling_status_rdempty_i;
         end
         // Register timestamp_mux: timestamp_mux_timestamp_mux (RW)
         9'h09c: begin
            rdata_comb[0] = timestamp_mux_timestamp_mux;
         end
         // Register prach_coupling_status: prach_coupling_status_prach_state (RO)
         //                                 prach_coupling_status_prach_first_cplane_detect (RO)
         //                                 prach_coupling_status_prach_first_uplane_detect (RO)
         //                                 prach_coupling_status_prach_wr_memory_location (RO)
         //                                 prach_coupling_status_prach_rd_memory_location (RO)
         //                                 prach_coupling_status_invalid_PRACH_eaxc (RO)
         //                                 prach_coupling_status_prach_invalid_num_of_cplane (RO)
         //                                 prach_coupling_status_ul_start_2d (RO)
         //                                 prach_coupling_status_prach_data_received (RO)
         //                                 prach_coupling_status_prach_data_processed (RO)
         //                                 prach_coupling_status_prach_fifo_full (RO)
         //                                 prach_coupling_status_prach_eAxC_Flag (RO)
         //                                 prach_coupling_status_prach_avst_source_ready (RO)
         9'h0a0: begin
            rdata_comb[3:0] = prach_coupling_status_prach_state_i[3:0];
            rdata_comb[4] = prach_coupling_status_prach_first_cplane_detect_i;
            rdata_comb[5] = prach_coupling_status_prach_first_uplane_detect_i;
            rdata_comb[6] = prach_coupling_status_prach_wr_memory_location_i;
            rdata_comb[7] = prach_coupling_status_prach_rd_memory_location_i;
            rdata_comb[8] = prach_coupling_status_invalid_PRACH_eaxc_i;
            rdata_comb[9] = prach_coupling_status_prach_invalid_num_of_cplane_i;
            rdata_comb[10] = prach_coupling_status_ul_start_2d_i;
            rdata_comb[11] = prach_coupling_status_prach_data_received_i;
            rdata_comb[12] = prach_coupling_status_prach_data_processed_i;
            rdata_comb[13] = prach_coupling_status_prach_fifo_full_i;
            rdata_comb[14] = prach_coupling_status_prach_eAxC_Flag_i;
            rdata_comb[15] = prach_coupling_status_prach_avst_source_ready_i;
         end
         // Register arbiter_cfg: arbiter_cfg_ctrl (RW)
         //                       arbiter_cfg_ready (RO)
         9'h100: begin
            rdata_comb[0] = arbiter_cfg_ctrl;
            rdata_comb[1] = arbiter_cfg_ready_i;
         end
         // Register arbiter_prio1: arbiter_prio1_pusch_priority (RW)
         //                         arbiter_prio1_prach_priority (RW)
         9'h104: begin
            rdata_comb[1:0] = arbiter_prio1_pusch_priority[1:0];
            rdata_comb[3:2] = arbiter_prio1_prach_priority[1:0];
         end
		 9'h108: begin
            rdata_comb[31:0] = coupling_statistics_register[31:0];
			end
         default: begin
            rdata_comb = 32'h00000000;
         end
      endcase
   end
end

endmodule