// hssi_ss_f_dr_cpu.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module hssi_ss_f_dr_cpu (
		input  wire        clk_clk,                      //                   clk.clk,          Clock Input
		input  wire [15:0] cpu_cmd_type_export,          //          cpu_cmd_type.export
		input  wire [31:0] cpu_cmd_export,               //               cpu_cmd.export
		input  wire [31:0] cpu_wr_data_export,           //           cpu_wr_data.export
		input  wire        cpu_cmd_start_export,         //         cpu_cmd_start.export
		output wire [3:0]  cpu_cmd_complete_export,      //      cpu_cmd_complete.export
		output wire [31:0] cpu_rd_data_export,           //           cpu_rd_data.export
		output wire [25:0] cpu_reconfig_address,         //          cpu_reconfig.address
		output wire [0:0]  cpu_reconfig_burstcount,      //                      .burstcount
		output wire        cpu_reconfig_read,            //                      .read
		output wire        cpu_reconfig_write,           //                      .write
		input  wire        cpu_reconfig_waitrequest,     //                      .waitrequest
		input  wire        cpu_reconfig_readdatavalid,   //                      .readdatavalid
		output wire [3:0]  cpu_reconfig_byteenable,      //                      .byteenable
		input  wire [31:0] cpu_reconfig_readdata,        //                      .readdata
		output wire [31:0] cpu_reconfig_writedata,       //                      .writedata
		output wire        cpu_reconfig_lock,            //                      .lock
		output wire        cpu_reconfig_debugaccess,     //                      .debugaccess
		input  wire        reset_reset,                  //                 reset.reset,        Reset Input
		output wire [3:0]  cpu_p0_reset_pio_export,      //      cpu_p0_reset_pio.export
		input  wire [3:0]  cpu_p0_reset_pio_ack_export,  //  cpu_p0_reset_pio_ack.export
		input  wire [19:0] cpu_p0_port_params_export,    //    cpu_p0_port_params.export
		output wire [3:0]  cpu_p1_reset_pio_export,      //      cpu_p1_reset_pio.export
		input  wire [3:0]  cpu_p1_reset_pio_ack_export,  //  cpu_p1_reset_pio_ack.export
		input  wire [19:0] cpu_p1_port_params_export,    //    cpu_p1_port_params.export
		output wire [3:0]  cpu_p2_reset_pio_export,      //      cpu_p2_reset_pio.export
		input  wire [3:0]  cpu_p2_reset_pio_ack_export,  //  cpu_p2_reset_pio_ack.export
		input  wire [19:0] cpu_p2_port_params_export,    //    cpu_p2_port_params.export
		output wire [3:0]  cpu_p3_reset_pio_export,      //      cpu_p3_reset_pio.export
		input  wire [3:0]  cpu_p3_reset_pio_ack_export,  //  cpu_p3_reset_pio_ack.export
		input  wire [19:0] cpu_p3_port_params_export,    //    cpu_p3_port_params.export
		output wire [3:0]  cpu_p4_reset_pio_export,      //      cpu_p4_reset_pio.export
		input  wire [3:0]  cpu_p4_reset_pio_ack_export,  //  cpu_p4_reset_pio_ack.export
		input  wire [19:0] cpu_p4_port_params_export,    //    cpu_p4_port_params.export
		output wire [3:0]  cpu_p5_reset_pio_export,      //      cpu_p5_reset_pio.export
		input  wire [3:0]  cpu_p5_reset_pio_ack_export,  //  cpu_p5_reset_pio_ack.export
		input  wire [19:0] cpu_p5_port_params_export,    //    cpu_p5_port_params.export
		output wire [3:0]  cpu_p6_reset_pio_export,      //      cpu_p6_reset_pio.export
		input  wire [3:0]  cpu_p6_reset_pio_ack_export,  //  cpu_p6_reset_pio_ack.export
		input  wire [19:0] cpu_p6_port_params_export,    //    cpu_p6_port_params.export
		output wire [3:0]  cpu_p7_reset_pio_export,      //      cpu_p7_reset_pio.export
		input  wire [3:0]  cpu_p7_reset_pio_ack_export,  //  cpu_p7_reset_pio_ack.export
		input  wire [19:0] cpu_p7_port_params_export,    //    cpu_p7_port_params.export
		output wire [3:0]  cpu_p8_reset_pio_export,      //      cpu_p8_reset_pio.export
		input  wire [3:0]  cpu_p8_reset_pio_ack_export,  //  cpu_p8_reset_pio_ack.export
		input  wire [19:0] cpu_p8_port_params_export,    //    cpu_p8_port_params.export
		output wire [3:0]  cpu_p9_reset_pio_export,      //      cpu_p9_reset_pio.export
		input  wire [3:0]  cpu_p9_reset_pio_ack_export,  //  cpu_p9_reset_pio_ack.export
		input  wire [19:0] cpu_p9_port_params_export,    //    cpu_p9_port_params.export
		output wire [3:0]  cpu_p10_reset_pio_export,     //     cpu_p10_reset_pio.export
		input  wire [3:0]  cpu_p10_reset_pio_ack_export, // cpu_p10_reset_pio_ack.export
		input  wire [19:0] cpu_p10_port_params_export,   //   cpu_p10_port_params.export
		output wire [3:0]  cpu_p11_reset_pio_export,     //     cpu_p11_reset_pio.export
		input  wire [3:0]  cpu_p11_reset_pio_ack_export, // cpu_p11_reset_pio_ack.export
		input  wire [19:0] cpu_p11_port_params_export,   //   cpu_p11_port_params.export
		output wire [3:0]  cpu_p12_reset_pio_export,     //     cpu_p12_reset_pio.export
		input  wire [3:0]  cpu_p12_reset_pio_ack_export, // cpu_p12_reset_pio_ack.export
		input  wire [19:0] cpu_p12_port_params_export,   //   cpu_p12_port_params.export
		output wire [3:0]  cpu_p13_reset_pio_export,     //     cpu_p13_reset_pio.export
		input  wire [3:0]  cpu_p13_reset_pio_ack_export, // cpu_p13_reset_pio_ack.export
		input  wire [19:0] cpu_p13_port_params_export,   //   cpu_p13_port_params.export
		output wire [3:0]  cpu_p14_reset_pio_export,     //     cpu_p14_reset_pio.export
		input  wire [3:0]  cpu_p14_reset_pio_ack_export, // cpu_p14_reset_pio_ack.export
		input  wire [19:0] cpu_p14_port_params_export,   //   cpu_p14_port_params.export
		output wire [3:0]  cpu_p15_reset_pio_export,     //     cpu_p15_reset_pio.export
		input  wire [3:0]  cpu_p15_reset_pio_ack_export, // cpu_p15_reset_pio_ack.export
		input  wire [19:0] cpu_p15_port_params_export,   //   cpu_p15_port_params.export
		output wire [3:0]  cpu_p16_reset_pio_export,     //     cpu_p16_reset_pio.export
		input  wire [3:0]  cpu_p16_reset_pio_ack_export, // cpu_p16_reset_pio_ack.export
		input  wire [19:0] cpu_p16_port_params_export,   //   cpu_p16_port_params.export
		output wire [3:0]  cpu_p17_reset_pio_export,     //     cpu_p17_reset_pio.export
		input  wire [3:0]  cpu_p17_reset_pio_ack_export, // cpu_p17_reset_pio_ack.export
		input  wire [19:0] cpu_p17_port_params_export,   //   cpu_p17_port_params.export
		output wire [3:0]  cpu_p18_reset_pio_export,     //     cpu_p18_reset_pio.export
		input  wire [3:0]  cpu_p18_reset_pio_ack_export, // cpu_p18_reset_pio_ack.export
		input  wire [19:0] cpu_p18_port_params_export,   //   cpu_p18_port_params.export
		output wire [3:0]  cpu_p19_reset_pio_export,     //     cpu_p19_reset_pio.export
		input  wire [3:0]  cpu_p19_reset_pio_ack_export, // cpu_p19_reset_pio_ack.export
		input  wire [19:0] cpu_p19_port_params_export    //   cpu_p19_port_params.export
	);

	hssi_ss_1_hssi_ss_dr_cpu_191_niad63y hssi_ss_f_dr_cpu (
		.clk_clk                      (clk_clk),                      //   input,   width = 1,                   clk.clk
		.cpu_cmd_type_export          (cpu_cmd_type_export),          //   input,  width = 16,          cpu_cmd_type.export
		.cpu_cmd_export               (cpu_cmd_export),               //   input,  width = 32,               cpu_cmd.export
		.cpu_wr_data_export           (cpu_wr_data_export),           //   input,  width = 32,           cpu_wr_data.export
		.cpu_cmd_start_export         (cpu_cmd_start_export),         //   input,   width = 1,         cpu_cmd_start.export
		.cpu_cmd_complete_export      (cpu_cmd_complete_export),      //  output,   width = 4,      cpu_cmd_complete.export
		.cpu_rd_data_export           (cpu_rd_data_export),           //  output,  width = 32,           cpu_rd_data.export
		.cpu_reconfig_address         (cpu_reconfig_address),         //  output,  width = 26,          cpu_reconfig.address
		.cpu_reconfig_burstcount      (cpu_reconfig_burstcount),      //  output,   width = 1,                      .burstcount
		.cpu_reconfig_read            (cpu_reconfig_read),            //  output,   width = 1,                      .read
		.cpu_reconfig_write           (cpu_reconfig_write),           //  output,   width = 1,                      .write
		.cpu_reconfig_waitrequest     (cpu_reconfig_waitrequest),     //   input,   width = 1,                      .waitrequest
		.cpu_reconfig_readdatavalid   (cpu_reconfig_readdatavalid),   //   input,   width = 1,                      .readdatavalid
		.cpu_reconfig_byteenable      (cpu_reconfig_byteenable),      //  output,   width = 4,                      .byteenable
		.cpu_reconfig_readdata        (cpu_reconfig_readdata),        //   input,  width = 32,                      .readdata
		.cpu_reconfig_writedata       (cpu_reconfig_writedata),       //  output,  width = 32,                      .writedata
		.cpu_reconfig_lock            (cpu_reconfig_lock),            //  output,   width = 1,                      .lock
		.cpu_reconfig_debugaccess     (cpu_reconfig_debugaccess),     //  output,   width = 1,                      .debugaccess
		.reset_reset                  (reset_reset),                  //   input,   width = 1,                 reset.reset
		.cpu_p0_reset_pio_export      (cpu_p0_reset_pio_export),      //  output,   width = 4,      cpu_p0_reset_pio.export
		.cpu_p0_reset_pio_ack_export  (cpu_p0_reset_pio_ack_export),  //   input,   width = 4,  cpu_p0_reset_pio_ack.export
		.cpu_p0_port_params_export    (cpu_p0_port_params_export),    //   input,  width = 20,    cpu_p0_port_params.export
		.cpu_p1_reset_pio_export      (cpu_p1_reset_pio_export),      //  output,   width = 4,      cpu_p1_reset_pio.export
		.cpu_p1_reset_pio_ack_export  (cpu_p1_reset_pio_ack_export),  //   input,   width = 4,  cpu_p1_reset_pio_ack.export
		.cpu_p1_port_params_export    (cpu_p1_port_params_export),    //   input,  width = 20,    cpu_p1_port_params.export
		.cpu_p2_reset_pio_export      (cpu_p2_reset_pio_export),      //  output,   width = 4,      cpu_p2_reset_pio.export
		.cpu_p2_reset_pio_ack_export  (cpu_p2_reset_pio_ack_export),  //   input,   width = 4,  cpu_p2_reset_pio_ack.export
		.cpu_p2_port_params_export    (cpu_p2_port_params_export),    //   input,  width = 20,    cpu_p2_port_params.export
		.cpu_p3_reset_pio_export      (cpu_p3_reset_pio_export),      //  output,   width = 4,      cpu_p3_reset_pio.export
		.cpu_p3_reset_pio_ack_export  (cpu_p3_reset_pio_ack_export),  //   input,   width = 4,  cpu_p3_reset_pio_ack.export
		.cpu_p3_port_params_export    (cpu_p3_port_params_export),    //   input,  width = 20,    cpu_p3_port_params.export
		.cpu_p4_reset_pio_export      (cpu_p4_reset_pio_export),      //  output,   width = 4,      cpu_p4_reset_pio.export
		.cpu_p4_reset_pio_ack_export  (cpu_p4_reset_pio_ack_export),  //   input,   width = 4,  cpu_p4_reset_pio_ack.export
		.cpu_p4_port_params_export    (cpu_p4_port_params_export),    //   input,  width = 20,    cpu_p4_port_params.export
		.cpu_p5_reset_pio_export      (cpu_p5_reset_pio_export),      //  output,   width = 4,      cpu_p5_reset_pio.export
		.cpu_p5_reset_pio_ack_export  (cpu_p5_reset_pio_ack_export),  //   input,   width = 4,  cpu_p5_reset_pio_ack.export
		.cpu_p5_port_params_export    (cpu_p5_port_params_export),    //   input,  width = 20,    cpu_p5_port_params.export
		.cpu_p6_reset_pio_export      (cpu_p6_reset_pio_export),      //  output,   width = 4,      cpu_p6_reset_pio.export
		.cpu_p6_reset_pio_ack_export  (cpu_p6_reset_pio_ack_export),  //   input,   width = 4,  cpu_p6_reset_pio_ack.export
		.cpu_p6_port_params_export    (cpu_p6_port_params_export),    //   input,  width = 20,    cpu_p6_port_params.export
		.cpu_p7_reset_pio_export      (cpu_p7_reset_pio_export),      //  output,   width = 4,      cpu_p7_reset_pio.export
		.cpu_p7_reset_pio_ack_export  (cpu_p7_reset_pio_ack_export),  //   input,   width = 4,  cpu_p7_reset_pio_ack.export
		.cpu_p7_port_params_export    (cpu_p7_port_params_export),    //   input,  width = 20,    cpu_p7_port_params.export
		.cpu_p8_reset_pio_export      (cpu_p8_reset_pio_export),      //  output,   width = 4,      cpu_p8_reset_pio.export
		.cpu_p8_reset_pio_ack_export  (cpu_p8_reset_pio_ack_export),  //   input,   width = 4,  cpu_p8_reset_pio_ack.export
		.cpu_p8_port_params_export    (cpu_p8_port_params_export),    //   input,  width = 20,    cpu_p8_port_params.export
		.cpu_p9_reset_pio_export      (cpu_p9_reset_pio_export),      //  output,   width = 4,      cpu_p9_reset_pio.export
		.cpu_p9_reset_pio_ack_export  (cpu_p9_reset_pio_ack_export),  //   input,   width = 4,  cpu_p9_reset_pio_ack.export
		.cpu_p9_port_params_export    (cpu_p9_port_params_export),    //   input,  width = 20,    cpu_p9_port_params.export
		.cpu_p10_reset_pio_export     (cpu_p10_reset_pio_export),     //  output,   width = 4,     cpu_p10_reset_pio.export
		.cpu_p10_reset_pio_ack_export (cpu_p10_reset_pio_ack_export), //   input,   width = 4, cpu_p10_reset_pio_ack.export
		.cpu_p10_port_params_export   (cpu_p10_port_params_export),   //   input,  width = 20,   cpu_p10_port_params.export
		.cpu_p11_reset_pio_export     (cpu_p11_reset_pio_export),     //  output,   width = 4,     cpu_p11_reset_pio.export
		.cpu_p11_reset_pio_ack_export (cpu_p11_reset_pio_ack_export), //   input,   width = 4, cpu_p11_reset_pio_ack.export
		.cpu_p11_port_params_export   (cpu_p11_port_params_export),   //   input,  width = 20,   cpu_p11_port_params.export
		.cpu_p12_reset_pio_export     (cpu_p12_reset_pio_export),     //  output,   width = 4,     cpu_p12_reset_pio.export
		.cpu_p12_reset_pio_ack_export (cpu_p12_reset_pio_ack_export), //   input,   width = 4, cpu_p12_reset_pio_ack.export
		.cpu_p12_port_params_export   (cpu_p12_port_params_export),   //   input,  width = 20,   cpu_p12_port_params.export
		.cpu_p13_reset_pio_export     (cpu_p13_reset_pio_export),     //  output,   width = 4,     cpu_p13_reset_pio.export
		.cpu_p13_reset_pio_ack_export (cpu_p13_reset_pio_ack_export), //   input,   width = 4, cpu_p13_reset_pio_ack.export
		.cpu_p13_port_params_export   (cpu_p13_port_params_export),   //   input,  width = 20,   cpu_p13_port_params.export
		.cpu_p14_reset_pio_export     (cpu_p14_reset_pio_export),     //  output,   width = 4,     cpu_p14_reset_pio.export
		.cpu_p14_reset_pio_ack_export (cpu_p14_reset_pio_ack_export), //   input,   width = 4, cpu_p14_reset_pio_ack.export
		.cpu_p14_port_params_export   (cpu_p14_port_params_export),   //   input,  width = 20,   cpu_p14_port_params.export
		.cpu_p15_reset_pio_export     (cpu_p15_reset_pio_export),     //  output,   width = 4,     cpu_p15_reset_pio.export
		.cpu_p15_reset_pio_ack_export (cpu_p15_reset_pio_ack_export), //   input,   width = 4, cpu_p15_reset_pio_ack.export
		.cpu_p15_port_params_export   (cpu_p15_port_params_export),   //   input,  width = 20,   cpu_p15_port_params.export
		.cpu_p16_reset_pio_export     (cpu_p16_reset_pio_export),     //  output,   width = 4,     cpu_p16_reset_pio.export
		.cpu_p16_reset_pio_ack_export (cpu_p16_reset_pio_ack_export), //   input,   width = 4, cpu_p16_reset_pio_ack.export
		.cpu_p16_port_params_export   (cpu_p16_port_params_export),   //   input,  width = 20,   cpu_p16_port_params.export
		.cpu_p17_reset_pio_export     (cpu_p17_reset_pio_export),     //  output,   width = 4,     cpu_p17_reset_pio.export
		.cpu_p17_reset_pio_ack_export (cpu_p17_reset_pio_ack_export), //   input,   width = 4, cpu_p17_reset_pio_ack.export
		.cpu_p17_port_params_export   (cpu_p17_port_params_export),   //   input,  width = 20,   cpu_p17_port_params.export
		.cpu_p18_reset_pio_export     (cpu_p18_reset_pio_export),     //  output,   width = 4,     cpu_p18_reset_pio.export
		.cpu_p18_reset_pio_ack_export (cpu_p18_reset_pio_ack_export), //   input,   width = 4, cpu_p18_reset_pio_ack.export
		.cpu_p18_port_params_export   (cpu_p18_port_params_export),   //   input,  width = 20,   cpu_p18_port_params.export
		.cpu_p19_reset_pio_export     (cpu_p19_reset_pio_export),     //  output,   width = 4,     cpu_p19_reset_pio.export
		.cpu_p19_reset_pio_ack_export (cpu_p19_reset_pio_ack_export), //   input,   width = 4, cpu_p19_reset_pio_ack.export
		.cpu_p19_port_params_export   (cpu_p19_port_params_export)    //   input,  width = 20,   cpu_p19_port_params.export
	);

endmodule
