// mtod_subsys_pps_load_tod_0.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module mtod_subsys_pps_load_tod_0 (
		input  wire        period_clock,                //          period_clock.clk
		input  wire        reset,                       //                 reset.reset
		input  wire        csr_clock,                   //             csr_clock.clk
		input  wire        csr_reset,                   //             csr_reset.reset
		output wire [31:0] csr_readdata,                //                   csr.readdata
		input  wire        csr_write,                   //                      .write
		input  wire        csr_read,                    //                      .read
		input  wire [31:0] csr_writedata,               //                      .writedata
		output wire        csr_waitrequest,             //                      .waitrequest
		input  wire [5:0]  csr_address,                 //                      .address
		input  wire        pps_pulse_per_second,        //         pps_interface.pulse_per_second
		input  wire [95:0] time_of_day_96b,             //       time_of_day_96b.data
		output wire [95:0] time_of_data_96b_load_data,  // time_of_data_96b_load.data
		output wire        time_of_data_96b_load_valid, //                      .valid
		output wire        pps_irq                      //               pps_irq.irq
	);

	pps_load_tod mtod_subsys_pps_load_tod_0 (
		.period_clock                (period_clock),                //   input,   width = 1,          period_clock.clk
		.reset                       (reset),                       //   input,   width = 1,                 reset.reset
		.csr_clock                   (csr_clock),                   //   input,   width = 1,             csr_clock.clk
		.csr_reset                   (csr_reset),                   //   input,   width = 1,             csr_reset.reset
		.csr_readdata                (csr_readdata),                //  output,  width = 32,                   csr.readdata
		.csr_write                   (csr_write),                   //   input,   width = 1,                      .write
		.csr_read                    (csr_read),                    //   input,   width = 1,                      .read
		.csr_writedata               (csr_writedata),               //   input,  width = 32,                      .writedata
		.csr_waitrequest             (csr_waitrequest),             //  output,   width = 1,                      .waitrequest
		.csr_address                 (csr_address),                 //   input,   width = 6,                      .address
		.pps_pulse_per_second        (pps_pulse_per_second),        //   input,   width = 1,         pps_interface.pulse_per_second
		.time_of_day_96b             (time_of_day_96b),             //   input,  width = 96,       time_of_day_96b.data
		.time_of_data_96b_load_data  (time_of_data_96b_load_data),  //  output,  width = 96, time_of_data_96b_load.data
		.time_of_data_96b_load_valid (time_of_data_96b_load_valid), //  output,   width = 1,                      .valid
		.pps_irq                     (pps_irq)                      //  output,   width = 1,               pps_irq.irq
	);

endmodule
