# TCL File Generated by Component Editor 22.3
# Fri Mar 31 18:13:34 MYT 2023
# DO NOT MODIFY


# 
# tod_conduit_split "tod_conduit_split" v1.0
#  2023.03.31.18:13:34
# 
# 

# 
# request TCL package from ACDS 22.3
# 
package require -exact qsys 22.3


# 
# module tod_conduit_split
# 
set_module_property DESCRIPTION ""
set_module_property NAME tod_conduit_split
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME tod_conduit_split
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL tod_conduit_split
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file tod_conduit_split.sv SYSTEM_VERILOG PATH tod_conduit_split.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL tod_conduit_split
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file tod_conduit_split.sv SYSTEM_VERILOG PATH tod_conduit_split.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""
set_interface_property conduit_end IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end SV_INTERFACE_TYPE ""
set_interface_property conduit_end SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end data_conduit_in data Input 96
add_interface_port conduit_end valid_conduit_in valid Input 1


# 
# connection point conduit_end_1
# 
add_interface conduit_end_1 conduit end
set_interface_property conduit_end_1 associatedClock ""
set_interface_property conduit_end_1 associatedReset ""
set_interface_property conduit_end_1 ENABLED true
set_interface_property conduit_end_1 EXPORT_OF ""
set_interface_property conduit_end_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_1 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_1 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_1 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_1 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_1 data_conduit_out_1 data Output 96
add_interface_port conduit_end_1 valid_conduit_out_1 valid Output 1


# 
# connection point conduit_end_2
# 
add_interface conduit_end_2 conduit end
set_interface_property conduit_end_2 associatedClock ""
set_interface_property conduit_end_2 associatedReset ""
set_interface_property conduit_end_2 ENABLED true
set_interface_property conduit_end_2 EXPORT_OF ""
set_interface_property conduit_end_2 PORT_NAME_MAP ""
set_interface_property conduit_end_2 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_2 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_2 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_2 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_2 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_2 data_conduit_out_2 data Output 96
add_interface_port conduit_end_2 valid_conduit_out_2 valid Output 1


# 
# connection point conduit_end_3
# 
add_interface conduit_end_3 conduit end
set_interface_property conduit_end_3 associatedClock ""
set_interface_property conduit_end_3 associatedReset ""
set_interface_property conduit_end_3 ENABLED true
set_interface_property conduit_end_3 EXPORT_OF ""
set_interface_property conduit_end_3 PORT_NAME_MAP ""
set_interface_property conduit_end_3 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_3 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_3 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_3 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_3 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_3 data_conduit_out_3 data Output 96
add_interface_port conduit_end_3 valid_conduit_out_3 valid Output 1


# 
# connection point conduit_end_4
# 
add_interface conduit_end_4 conduit end
set_interface_property conduit_end_4 associatedClock ""
set_interface_property conduit_end_4 associatedReset ""
set_interface_property conduit_end_4 ENABLED true
set_interface_property conduit_end_4 EXPORT_OF ""
set_interface_property conduit_end_4 PORT_NAME_MAP ""
set_interface_property conduit_end_4 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_4 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_4 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_4 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_4 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_4 data_conduit_out_4 data Output 96
add_interface_port conduit_end_4 valid_conduit_out_4 valid Output 1


# 
# connection point conduit_end_5
# 
add_interface conduit_end_5 conduit end
set_interface_property conduit_end_5 associatedClock ""
set_interface_property conduit_end_5 associatedReset ""
set_interface_property conduit_end_5 ENABLED true
set_interface_property conduit_end_5 EXPORT_OF ""
set_interface_property conduit_end_5 PORT_NAME_MAP ""
set_interface_property conduit_end_5 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_5 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_5 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_5 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_5 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_5 data_conduit_out_5 data Output 96
add_interface_port conduit_end_5 valid_conduit_out_5 valid Output 1


# 
# connection point conduit_end_6
# 
add_interface conduit_end_6 conduit end
set_interface_property conduit_end_6 associatedClock ""
set_interface_property conduit_end_6 associatedReset ""
set_interface_property conduit_end_6 ENABLED true
set_interface_property conduit_end_6 EXPORT_OF ""
set_interface_property conduit_end_6 PORT_NAME_MAP ""
set_interface_property conduit_end_6 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_6 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_6 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_6 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_6 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_6 data_conduit_out_6 data Output 96
add_interface_port conduit_end_6 valid_conduit_out_6 valid Output 1


# 
# connection point conduit_end_7
# 
add_interface conduit_end_7 conduit end
set_interface_property conduit_end_7 associatedClock ""
set_interface_property conduit_end_7 associatedReset ""
set_interface_property conduit_end_7 ENABLED true
set_interface_property conduit_end_7 EXPORT_OF ""
set_interface_property conduit_end_7 PORT_NAME_MAP ""
set_interface_property conduit_end_7 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_7 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_7 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_7 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_7 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_7 data_conduit_out_7 data Output 96
add_interface_port conduit_end_7 valid_conduit_out_7 valid Output 1


# 
# connection point conduit_end_8
# 
add_interface conduit_end_8 conduit end
set_interface_property conduit_end_8 associatedClock ""
set_interface_property conduit_end_8 associatedReset ""
set_interface_property conduit_end_8 ENABLED true
set_interface_property conduit_end_8 EXPORT_OF ""
set_interface_property conduit_end_8 PORT_NAME_MAP ""
set_interface_property conduit_end_8 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_8 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_8 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_8 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_8 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_8 data_conduit_out_8 data Output 96
add_interface_port conduit_end_8 valid_conduit_out_8 valid Output 1


# 
# connection point conduit_end_9
# 
add_interface conduit_end_9 conduit end
set_interface_property conduit_end_9 associatedClock ""
set_interface_property conduit_end_9 associatedReset ""
set_interface_property conduit_end_9 ENABLED true
set_interface_property conduit_end_9 EXPORT_OF ""
set_interface_property conduit_end_9 PORT_NAME_MAP ""
set_interface_property conduit_end_9 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_9 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_9 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_9 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_9 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_9 data_conduit_out_9 data Output 96
add_interface_port conduit_end_9 valid_conduit_out_9 valid Output 1


# 
# connection point conduit_end_10
# 
add_interface conduit_end_10 conduit end
set_interface_property conduit_end_10 associatedClock ""
set_interface_property conduit_end_10 associatedReset ""
set_interface_property conduit_end_10 ENABLED true
set_interface_property conduit_end_10 EXPORT_OF ""
set_interface_property conduit_end_10 PORT_NAME_MAP ""
set_interface_property conduit_end_10 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_10 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_10 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_end_10 SV_INTERFACE_TYPE ""
set_interface_property conduit_end_10 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_end_10 data_conduit_out_10 data Output 96
add_interface_port conduit_end_10 valid_conduit_out_10 valid Output 1

