// eth_f_por.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module eth_f_por (
		output wire  ninit_done  // ninit_done.ninit_done
	);

	altera_s10_user_rst_clkgate eth_f_por (
		.ninit_done (ninit_done)  //  output,  width = 1, ninit_done.ninit_done
	);

endmodule
