# TCL File Generated by Component Editor 22.2
# Wed Jun 15 18:46:51 MYT 2022
# DO NOT MODIFY


# 
# eth_ptp_adpt "eth_ptp_adpt" v1.0
#  2022.06.15.18:46:51
# 
# 

# 
# request TCL package from ACDS 22.2
# 
package require -exact qsys 22.2


# 
# module eth_ptp_adpt
# 
set_module_property DESCRIPTION ""
set_module_property NAME eth_ptp_adpt
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME eth_ptp_adpt
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL eth_ptp_adpt_f_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file eth_ptp_adpt_f_top.sv SYSTEM_VERILOG PATH eth_ptp_adpt_f_top.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL eth_ptp_adpt_f_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file eth_ptp_adpt_f_top.sv SYSTEM_VERILOG PATH eth_ptp_adpt_f_top.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point tx_pll_locked
# 
add_interface tx_pll_locked conduit end
set_interface_property tx_pll_locked associatedClock ""
set_interface_property tx_pll_locked associatedReset ""
set_interface_property tx_pll_locked ENABLED true
set_interface_property tx_pll_locked EXPORT_OF ""
set_interface_property tx_pll_locked PORT_NAME_MAP ""
set_interface_property tx_pll_locked CMSIS_SVD_VARIABLES ""
set_interface_property tx_pll_locked SVD_ADDRESS_GROUP ""
set_interface_property tx_pll_locked IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_pll_locked tx_pll_locked tx_pll_locked Input 1


# 
# connection point o_clk_pll
# 
add_interface o_clk_pll clock start
set_interface_property o_clk_pll associatedDirectClock ""
set_interface_property o_clk_pll ENABLED true
set_interface_property o_clk_pll EXPORT_OF ""
set_interface_property o_clk_pll PORT_NAME_MAP ""
set_interface_property o_clk_pll CMSIS_SVD_VARIABLES ""
set_interface_property o_clk_pll SVD_ADDRESS_GROUP ""
set_interface_property o_clk_pll IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port o_clk_pll o_clk_pll clk Output 1


# 
# connection point i_reconfig_clk
# 
add_interface i_reconfig_clk clock end
set_interface_property i_reconfig_clk ENABLED true
set_interface_property i_reconfig_clk EXPORT_OF ""
set_interface_property i_reconfig_clk PORT_NAME_MAP ""
set_interface_property i_reconfig_clk CMSIS_SVD_VARIABLES ""
set_interface_property i_reconfig_clk SVD_ADDRESS_GROUP ""
set_interface_property i_reconfig_clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port i_reconfig_clk i_reconfig_clk clk Input 1


# 
# connection point i_reconfig_reset
# 
add_interface i_reconfig_reset reset end
set_interface_property i_reconfig_reset associatedClock ""
set_interface_property i_reconfig_reset synchronousEdges NONE
set_interface_property i_reconfig_reset ENABLED true
set_interface_property i_reconfig_reset EXPORT_OF ""
set_interface_property i_reconfig_reset PORT_NAME_MAP ""
set_interface_property i_reconfig_reset CMSIS_SVD_VARIABLES ""
set_interface_property i_reconfig_reset SVD_ADDRESS_GROUP ""
set_interface_property i_reconfig_reset IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port i_reconfig_reset i_reconfig_reset reset Input 1


# 
# connection point o_ptp_link
# 
add_interface o_ptp_link conduit end
set_interface_property o_ptp_link associatedClock ""
set_interface_property o_ptp_link associatedReset ""
set_interface_property o_ptp_link ENABLED true
set_interface_property o_ptp_link EXPORT_OF ""
set_interface_property o_ptp_link PORT_NAME_MAP ""
set_interface_property o_ptp_link CMSIS_SVD_VARIABLES ""
set_interface_property o_ptp_link SVD_ADDRESS_GROUP ""
set_interface_property o_ptp_link IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port o_ptp_link ptp_link ptp_link Output 1


# 
# connection point reconfig_asym
# 
add_interface reconfig_asym avalon end
set_interface_property reconfig_asym addressGroup 0
set_interface_property reconfig_asym addressUnits WORDS
set_interface_property reconfig_asym associatedClock i_reconfig_clk
set_interface_property reconfig_asym associatedReset i_reconfig_reset
set_interface_property reconfig_asym bitsPerSymbol 8
set_interface_property reconfig_asym bridgedAddressOffset ""
set_interface_property reconfig_asym bridgesToMaster ""
set_interface_property reconfig_asym burstOnBurstBoundariesOnly false
set_interface_property reconfig_asym burstcountUnits WORDS
set_interface_property reconfig_asym explicitAddressSpan 0
set_interface_property reconfig_asym holdTime 0
set_interface_property reconfig_asym linewrapBursts false
set_interface_property reconfig_asym maximumPendingReadTransactions 1
set_interface_property reconfig_asym maximumPendingWriteTransactions 0
set_interface_property reconfig_asym minimumResponseLatency 1
set_interface_property reconfig_asym readLatency 0
set_interface_property reconfig_asym readWaitTime 1
set_interface_property reconfig_asym setupTime 0
set_interface_property reconfig_asym timingUnits Cycles
set_interface_property reconfig_asym transparentBridge false
set_interface_property reconfig_asym waitrequestAllowance 0
set_interface_property reconfig_asym writeWaitTime 0
set_interface_property reconfig_asym ENABLED true
set_interface_property reconfig_asym EXPORT_OF ""
set_interface_property reconfig_asym PORT_NAME_MAP ""
set_interface_property reconfig_asym CMSIS_SVD_VARIABLES ""
set_interface_property reconfig_asym SVD_ADDRESS_GROUP ""
set_interface_property reconfig_asym IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reconfig_asym i_reconfig_asym_byteenable byteenable Input 4
add_interface_port reconfig_asym i_reconfig_asym_write write Input 1
add_interface_port reconfig_asym i_reconfig_asym_writedata writedata Input 32
add_interface_port reconfig_asym i_reconfig_asym_read read Input 1
add_interface_port reconfig_asym i_reconfig_asym_addr address Input 12
add_interface_port reconfig_asym o_reconfig_asym_readdata readdata Output 32
add_interface_port reconfig_asym o_reconfig_asym_readdata_valid readdatavalid Output 1
add_interface_port reconfig_asym o_reconfig_asym_waitrequest waitrequest Output 1
set_interface_assignment reconfig_asym embeddedsw.configuration.isFlash 0
set_interface_assignment reconfig_asym embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment reconfig_asym embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment reconfig_asym embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reconfig_p2p
# 
add_interface reconfig_p2p avalon end
set_interface_property reconfig_p2p addressGroup 0
set_interface_property reconfig_p2p addressUnits WORDS
set_interface_property reconfig_p2p associatedClock i_reconfig_clk
set_interface_property reconfig_p2p associatedReset i_reconfig_reset
set_interface_property reconfig_p2p bitsPerSymbol 8
set_interface_property reconfig_p2p bridgedAddressOffset ""
set_interface_property reconfig_p2p bridgesToMaster ""
set_interface_property reconfig_p2p burstOnBurstBoundariesOnly false
set_interface_property reconfig_p2p burstcountUnits WORDS
set_interface_property reconfig_p2p explicitAddressSpan 0
set_interface_property reconfig_p2p holdTime 0
set_interface_property reconfig_p2p linewrapBursts false
set_interface_property reconfig_p2p maximumPendingReadTransactions 1
set_interface_property reconfig_p2p maximumPendingWriteTransactions 0
set_interface_property reconfig_p2p minimumResponseLatency 1
set_interface_property reconfig_p2p readLatency 0
set_interface_property reconfig_p2p readWaitTime 1
set_interface_property reconfig_p2p setupTime 0
set_interface_property reconfig_p2p timingUnits Cycles
set_interface_property reconfig_p2p transparentBridge false
set_interface_property reconfig_p2p waitrequestAllowance 0
set_interface_property reconfig_p2p writeWaitTime 0
set_interface_property reconfig_p2p ENABLED true
set_interface_property reconfig_p2p EXPORT_OF ""
set_interface_property reconfig_p2p PORT_NAME_MAP ""
set_interface_property reconfig_p2p CMSIS_SVD_VARIABLES ""
set_interface_property reconfig_p2p SVD_ADDRESS_GROUP ""
set_interface_property reconfig_p2p IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reconfig_p2p i_reconfig_p2p_byteenable byteenable Input 4
add_interface_port reconfig_p2p i_reconfig_p2p_write write Input 1
add_interface_port reconfig_p2p i_reconfig_p2p_writedata writedata Input 32
add_interface_port reconfig_p2p i_reconfig_p2p_read read Input 1
add_interface_port reconfig_p2p i_reconfig_p2p_addr address Input 12
add_interface_port reconfig_p2p o_reconfig_p2p_readdata readdata Output 32
add_interface_port reconfig_p2p o_reconfig_p2p_readdata_valid readdatavalid Output 1
add_interface_port reconfig_p2p o_reconfig_p2p_waitrequest waitrequest Output 1
set_interface_assignment reconfig_p2p embeddedsw.configuration.isFlash 0
set_interface_assignment reconfig_p2p embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment reconfig_p2p embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment reconfig_p2p embeddedsw.configuration.isPrintableDevice 0

