// hssi_ss_1_alt_ehipc3_fm_sl_avmm_rcfg_191_yj6uisi.v

// This file was auto-generated from alt_ehipc3_fm_sl_avmm_rcfg_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module hssi_ss_1_alt_ehipc3_fm_sl_avmm_rcfg_191_yj6uisi (
		input  wire        clk_clk,                                        //                              clk.clk,          Clock Input
		input  wire [21:0] elane_avalon_universal_slave_0_address,         //   elane_avalon_universal_slave_0.address
		input  wire [0:0]  elane_avalon_universal_slave_0_burstcount,      //                                 .burstcount
		input  wire        elane_avalon_universal_slave_0_read,            //                                 .read
		input  wire        elane_avalon_universal_slave_0_write,           //                                 .write
		output wire        elane_avalon_universal_slave_0_waitrequest,     //                                 .waitrequest
		output wire        elane_avalon_universal_slave_0_readdatavalid,   //                                 .readdatavalid
		input  wire [3:0]  elane_avalon_universal_slave_0_byteenable,      //                                 .byteenable
		output wire [31:0] elane_avalon_universal_slave_0_readdata,        //                                 .readdata
		input  wire [31:0] elane_avalon_universal_slave_0_writedata,       //                                 .writedata
		input  wire        elane_avalon_universal_slave_0_lock,            //                                 .lock
		input  wire        elane_avalon_universal_slave_0_debugaccess,     //                                 .debugaccess
		output wire [21:0] master_avalon_universal_master_0_address,       // master_avalon_universal_master_0.address
		output wire [0:0]  master_avalon_universal_master_0_burstcount,    //                                 .burstcount
		output wire        master_avalon_universal_master_0_read,          //                                 .read
		output wire        master_avalon_universal_master_0_write,         //                                 .write
		input  wire        master_avalon_universal_master_0_waitrequest,   //                                 .waitrequest
		input  wire        master_avalon_universal_master_0_readdatavalid, //                                 .readdatavalid
		output wire [3:0]  master_avalon_universal_master_0_byteenable,    //                                 .byteenable
		input  wire [31:0] master_avalon_universal_master_0_readdata,      //                                 .readdata
		output wire [31:0] master_avalon_universal_master_0_writedata,     //                                 .writedata
		output wire        master_avalon_universal_master_0_lock,          //                                 .lock
		output wire        master_avalon_universal_master_0_debugaccess,   //                                 .debugaccess
		input  wire        reset_reset,                                    //                            reset.reset,        Reset Input
		input  wire [21:0] xcvr_avalon_universal_slave_0_address,          //    xcvr_avalon_universal_slave_0.address
		input  wire [0:0]  xcvr_avalon_universal_slave_0_burstcount,       //                                 .burstcount
		input  wire        xcvr_avalon_universal_slave_0_read,             //                                 .read
		input  wire        xcvr_avalon_universal_slave_0_write,            //                                 .write
		output wire        xcvr_avalon_universal_slave_0_waitrequest,      //                                 .waitrequest
		output wire        xcvr_avalon_universal_slave_0_readdatavalid,    //                                 .readdatavalid
		input  wire [3:0]  xcvr_avalon_universal_slave_0_byteenable,       //                                 .byteenable
		output wire [31:0] xcvr_avalon_universal_slave_0_readdata,         //                                 .readdata
		input  wire [31:0] xcvr_avalon_universal_slave_0_writedata,        //                                 .writedata
		input  wire        xcvr_avalon_universal_slave_0_lock,             //                                 .lock
		input  wire        xcvr_avalon_universal_slave_0_debugaccess       //                                 .debugaccess
	);

	wire  [31:0] elane_avalon_anti_slave_0_readdata;                          // mm_interconnect_0:elane_avalon_anti_slave_0_readdata -> elane:av_readdata
	wire         elane_avalon_anti_slave_0_waitrequest;                       // mm_interconnect_0:elane_avalon_anti_slave_0_waitrequest -> elane:av_waitrequest
	wire  [21:0] elane_avalon_anti_slave_0_address;                           // elane:av_address -> mm_interconnect_0:elane_avalon_anti_slave_0_address
	wire         elane_avalon_anti_slave_0_read;                              // elane:av_read -> mm_interconnect_0:elane_avalon_anti_slave_0_read
	wire         elane_avalon_anti_slave_0_readdatavalid;                     // mm_interconnect_0:elane_avalon_anti_slave_0_readdatavalid -> elane:av_readdatavalid
	wire         elane_avalon_anti_slave_0_write;                             // elane:av_write -> mm_interconnect_0:elane_avalon_anti_slave_0_write
	wire  [31:0] elane_avalon_anti_slave_0_writedata;                         // elane:av_writedata -> mm_interconnect_0:elane_avalon_anti_slave_0_writedata
	wire  [31:0] xcvr_avalon_anti_slave_0_readdata;                           // mm_interconnect_0:xcvr_avalon_anti_slave_0_readdata -> xcvr:av_readdata
	wire         xcvr_avalon_anti_slave_0_waitrequest;                        // mm_interconnect_0:xcvr_avalon_anti_slave_0_waitrequest -> xcvr:av_waitrequest
	wire  [21:0] xcvr_avalon_anti_slave_0_address;                            // xcvr:av_address -> mm_interconnect_0:xcvr_avalon_anti_slave_0_address
	wire         xcvr_avalon_anti_slave_0_read;                               // xcvr:av_read -> mm_interconnect_0:xcvr_avalon_anti_slave_0_read
	wire   [3:0] xcvr_avalon_anti_slave_0_byteenable;                         // xcvr:av_byteenable -> mm_interconnect_0:xcvr_avalon_anti_slave_0_byteenable
	wire         xcvr_avalon_anti_slave_0_readdatavalid;                      // mm_interconnect_0:xcvr_avalon_anti_slave_0_readdatavalid -> xcvr:av_readdatavalid
	wire         xcvr_avalon_anti_slave_0_begintransfer;                      // xcvr:av_begintransfer -> mm_interconnect_0:xcvr_avalon_anti_slave_0_begintransfer
	wire         xcvr_avalon_anti_slave_0_write;                              // xcvr:av_write -> mm_interconnect_0:xcvr_avalon_anti_slave_0_write
	wire  [31:0] xcvr_avalon_anti_slave_0_writedata;                          // xcvr:av_writedata -> mm_interconnect_0:xcvr_avalon_anti_slave_0_writedata
	wire  [31:0] mm_interconnect_0_master_avalon_anti_master_0_readdata;      // master:av_readdata -> mm_interconnect_0:master_avalon_anti_master_0_readdata
	wire         mm_interconnect_0_master_avalon_anti_master_0_waitrequest;   // master:av_waitrequest -> mm_interconnect_0:master_avalon_anti_master_0_waitrequest
	wire  [21:0] mm_interconnect_0_master_avalon_anti_master_0_address;       // mm_interconnect_0:master_avalon_anti_master_0_address -> master:av_address
	wire         mm_interconnect_0_master_avalon_anti_master_0_read;          // mm_interconnect_0:master_avalon_anti_master_0_read -> master:av_read
	wire         mm_interconnect_0_master_avalon_anti_master_0_readdatavalid; // master:av_readdatavalid -> mm_interconnect_0:master_avalon_anti_master_0_readdatavalid
	wire         mm_interconnect_0_master_avalon_anti_master_0_write;         // mm_interconnect_0:master_avalon_anti_master_0_write -> master:av_write
	wire  [31:0] mm_interconnect_0_master_avalon_anti_master_0_writedata;     // mm_interconnect_0:master_avalon_anti_master_0_writedata -> master:av_writedata

	hssi_ss_1_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (22),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (22),
		.UAV_BURSTCOUNT_W               (1),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (1),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (0)
	) elane (
		.clk                    (clk_clk),                                      //   input,   width = 1,                      clk.clk
		.reset                  (reset_reset),                                  //   input,   width = 1,                    reset.reset
		.uav_address            (elane_avalon_universal_slave_0_address),       //   input,  width = 22, avalon_universal_slave_0.address
		.uav_burstcount         (elane_avalon_universal_slave_0_burstcount),    //   input,   width = 1,                         .burstcount
		.uav_read               (elane_avalon_universal_slave_0_read),          //   input,   width = 1,                         .read
		.uav_write              (elane_avalon_universal_slave_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest        (elane_avalon_universal_slave_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (elane_avalon_universal_slave_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (elane_avalon_universal_slave_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata           (elane_avalon_universal_slave_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata          (elane_avalon_universal_slave_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock               (elane_avalon_universal_slave_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess        (elane_avalon_universal_slave_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.av_address             (elane_avalon_anti_slave_0_address),            //  output,  width = 22,      avalon_anti_slave_0.address
		.av_write               (elane_avalon_anti_slave_0_write),              //  output,   width = 1,                         .write
		.av_read                (elane_avalon_anti_slave_0_read),               //  output,   width = 1,                         .read
		.av_readdata            (elane_avalon_anti_slave_0_readdata),           //   input,  width = 32,                         .readdata
		.av_writedata           (elane_avalon_anti_slave_0_writedata),          //  output,  width = 32,                         .writedata
		.av_readdatavalid       (elane_avalon_anti_slave_0_readdatavalid),      //   input,   width = 1,                         .readdatavalid
		.av_waitrequest         (elane_avalon_anti_slave_0_waitrequest),        //   input,   width = 1,                         .waitrequest
		.av_begintransfer       (),                                             // (terminated),                                       
		.av_beginbursttransfer  (),                                             // (terminated),                                       
		.av_burstcount          (),                                             // (terminated),                                       
		.av_byteenable          (),                                             // (terminated),                                       
		.av_writebyteenable     (),                                             // (terminated),                                       
		.av_lock                (),                                             // (terminated),                                       
		.av_chipselect          (),                                             // (terminated),                                       
		.av_clken               (),                                             // (terminated),                                       
		.uav_clken              (1'b0),                                         // (terminated),                                       
		.av_debugaccess         (),                                             // (terminated),                                       
		.av_outputenable        (),                                             // (terminated),                                       
		.uav_response           (),                                             // (terminated),                                       
		.av_response            (2'b00),                                        // (terminated),                                       
		.uav_writeresponsevalid (),                                             // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                          // (terminated),                                       
	);

	hssi_ss_1_altera_merlin_master_translator_192_lykd4la #(
		.AV_ADDRESS_W                (22),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (22),
		.UAV_BURSTCOUNT_W            (1),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (1),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (0),
		.WAITREQUEST_ALLOWANCE       (0),
		.USE_OUTPUTENABLE            (0)
	) master (
		.clk                    (clk_clk),                                                     //   input,   width = 1,                       clk.clk
		.reset                  (reset_reset),                                                 //   input,   width = 1,                     reset.reset
		.uav_address            (master_avalon_universal_master_0_address),                    //  output,  width = 22, avalon_universal_master_0.address
		.uav_burstcount         (master_avalon_universal_master_0_burstcount),                 //  output,   width = 1,                          .burstcount
		.uav_read               (master_avalon_universal_master_0_read),                       //  output,   width = 1,                          .read
		.uav_write              (master_avalon_universal_master_0_write),                      //  output,   width = 1,                          .write
		.uav_waitrequest        (master_avalon_universal_master_0_waitrequest),                //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (master_avalon_universal_master_0_readdatavalid),              //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (master_avalon_universal_master_0_byteenable),                 //  output,   width = 4,                          .byteenable
		.uav_readdata           (master_avalon_universal_master_0_readdata),                   //   input,  width = 32,                          .readdata
		.uav_writedata          (master_avalon_universal_master_0_writedata),                  //  output,  width = 32,                          .writedata
		.uav_lock               (master_avalon_universal_master_0_lock),                       //  output,   width = 1,                          .lock
		.uav_debugaccess        (master_avalon_universal_master_0_debugaccess),                //  output,   width = 1,                          .debugaccess
		.av_address             (mm_interconnect_0_master_avalon_anti_master_0_address),       //   input,  width = 22,      avalon_anti_master_0.address
		.av_waitrequest         (mm_interconnect_0_master_avalon_anti_master_0_waitrequest),   //  output,   width = 1,                          .waitrequest
		.av_read                (mm_interconnect_0_master_avalon_anti_master_0_read),          //   input,   width = 1,                          .read
		.av_readdata            (mm_interconnect_0_master_avalon_anti_master_0_readdata),      //  output,  width = 32,                          .readdata
		.av_readdatavalid       (mm_interconnect_0_master_avalon_anti_master_0_readdatavalid), //  output,   width = 1,                          .readdatavalid
		.av_write               (mm_interconnect_0_master_avalon_anti_master_0_write),         //   input,   width = 1,                          .write
		.av_writedata           (mm_interconnect_0_master_avalon_anti_master_0_writedata),     //   input,  width = 32,                          .writedata
		.av_burstcount          (1'b1),                                                        // (terminated),                                        
		.av_byteenable          (4'b1111),                                                     // (terminated),                                        
		.av_beginbursttransfer  (1'b0),                                                        // (terminated),                                        
		.av_begintransfer       (1'b0),                                                        // (terminated),                                        
		.av_chipselect          (1'b0),                                                        // (terminated),                                        
		.av_lock                (1'b0),                                                        // (terminated),                                        
		.av_debugaccess         (1'b0),                                                        // (terminated),                                        
		.uav_outputenable       (1'b0),                                                        // (terminated),                                        
		.uav_clken              (),                                                            // (terminated),                                        
		.av_clken               (1'b1),                                                        // (terminated),                                        
		.uav_response           (2'b00),                                                       // (terminated),                                        
		.av_response            (),                                                            // (terminated),                                        
		.uav_writeresponsevalid (1'b0),                                                        // (terminated),                                        
		.av_writeresponsevalid  ()                                                             // (terminated),                                        
	);

	hssi_ss_1_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (22),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (22),
		.UAV_BURSTCOUNT_W               (1),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (1),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (0)
	) xcvr (
		.clk                    (clk_clk),                                     //   input,   width = 1,                      clk.clk
		.reset                  (reset_reset),                                 //   input,   width = 1,                    reset.reset
		.uav_address            (xcvr_avalon_universal_slave_0_address),       //   input,  width = 22, avalon_universal_slave_0.address
		.uav_burstcount         (xcvr_avalon_universal_slave_0_burstcount),    //   input,   width = 1,                         .burstcount
		.uav_read               (xcvr_avalon_universal_slave_0_read),          //   input,   width = 1,                         .read
		.uav_write              (xcvr_avalon_universal_slave_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest        (xcvr_avalon_universal_slave_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (xcvr_avalon_universal_slave_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (xcvr_avalon_universal_slave_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata           (xcvr_avalon_universal_slave_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata          (xcvr_avalon_universal_slave_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock               (xcvr_avalon_universal_slave_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess        (xcvr_avalon_universal_slave_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.av_address             (xcvr_avalon_anti_slave_0_address),            //  output,  width = 22,      avalon_anti_slave_0.address
		.av_write               (xcvr_avalon_anti_slave_0_write),              //  output,   width = 1,                         .write
		.av_read                (xcvr_avalon_anti_slave_0_read),               //  output,   width = 1,                         .read
		.av_readdata            (xcvr_avalon_anti_slave_0_readdata),           //   input,  width = 32,                         .readdata
		.av_writedata           (xcvr_avalon_anti_slave_0_writedata),          //  output,  width = 32,                         .writedata
		.av_begintransfer       (xcvr_avalon_anti_slave_0_begintransfer),      //  output,   width = 1,                         .begintransfer
		.av_byteenable          (xcvr_avalon_anti_slave_0_byteenable),         //  output,   width = 4,                         .byteenable
		.av_readdatavalid       (xcvr_avalon_anti_slave_0_readdatavalid),      //   input,   width = 1,                         .readdatavalid
		.av_waitrequest         (xcvr_avalon_anti_slave_0_waitrequest),        //   input,   width = 1,                         .waitrequest
		.av_beginbursttransfer  (),                                            // (terminated),                                       
		.av_burstcount          (),                                            // (terminated),                                       
		.av_writebyteenable     (),                                            // (terminated),                                       
		.av_lock                (),                                            // (terminated),                                       
		.av_chipselect          (),                                            // (terminated),                                       
		.av_clken               (),                                            // (terminated),                                       
		.uav_clken              (1'b0),                                        // (terminated),                                       
		.av_debugaccess         (),                                            // (terminated),                                       
		.av_outputenable        (),                                            // (terminated),                                       
		.uav_response           (),                                            // (terminated),                                       
		.av_response            (2'b00),                                       // (terminated),                                       
		.uav_writeresponsevalid (),                                            // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                         // (terminated),                                       
	);

	hssi_ss_1_altera_mm_interconnect_1920_ukl2fly mm_interconnect_0 (
		.elane_avalon_anti_slave_0_address         (elane_avalon_anti_slave_0_address),                           //   input,  width = 22,         elane_avalon_anti_slave_0.address
		.elane_avalon_anti_slave_0_waitrequest     (elane_avalon_anti_slave_0_waitrequest),                       //  output,   width = 1,                                  .waitrequest
		.elane_avalon_anti_slave_0_read            (elane_avalon_anti_slave_0_read),                              //   input,   width = 1,                                  .read
		.elane_avalon_anti_slave_0_readdata        (elane_avalon_anti_slave_0_readdata),                          //  output,  width = 32,                                  .readdata
		.elane_avalon_anti_slave_0_readdatavalid   (elane_avalon_anti_slave_0_readdatavalid),                     //  output,   width = 1,                                  .readdatavalid
		.elane_avalon_anti_slave_0_write           (elane_avalon_anti_slave_0_write),                             //   input,   width = 1,                                  .write
		.elane_avalon_anti_slave_0_writedata       (elane_avalon_anti_slave_0_writedata),                         //   input,  width = 32,                                  .writedata
		.xcvr_avalon_anti_slave_0_address          (xcvr_avalon_anti_slave_0_address),                            //   input,  width = 22,          xcvr_avalon_anti_slave_0.address
		.xcvr_avalon_anti_slave_0_waitrequest      (xcvr_avalon_anti_slave_0_waitrequest),                        //  output,   width = 1,                                  .waitrequest
		.xcvr_avalon_anti_slave_0_byteenable       (xcvr_avalon_anti_slave_0_byteenable),                         //   input,   width = 4,                                  .byteenable
		.xcvr_avalon_anti_slave_0_begintransfer    (xcvr_avalon_anti_slave_0_begintransfer),                      //   input,   width = 1,                                  .begintransfer
		.xcvr_avalon_anti_slave_0_read             (xcvr_avalon_anti_slave_0_read),                               //   input,   width = 1,                                  .read
		.xcvr_avalon_anti_slave_0_readdata         (xcvr_avalon_anti_slave_0_readdata),                           //  output,  width = 32,                                  .readdata
		.xcvr_avalon_anti_slave_0_readdatavalid    (xcvr_avalon_anti_slave_0_readdatavalid),                      //  output,   width = 1,                                  .readdatavalid
		.xcvr_avalon_anti_slave_0_write            (xcvr_avalon_anti_slave_0_write),                              //   input,   width = 1,                                  .write
		.xcvr_avalon_anti_slave_0_writedata        (xcvr_avalon_anti_slave_0_writedata),                          //   input,  width = 32,                                  .writedata
		.master_avalon_anti_master_0_address       (mm_interconnect_0_master_avalon_anti_master_0_address),       //  output,  width = 22,       master_avalon_anti_master_0.address
		.master_avalon_anti_master_0_write         (mm_interconnect_0_master_avalon_anti_master_0_write),         //  output,   width = 1,                                  .write
		.master_avalon_anti_master_0_read          (mm_interconnect_0_master_avalon_anti_master_0_read),          //  output,   width = 1,                                  .read
		.master_avalon_anti_master_0_readdata      (mm_interconnect_0_master_avalon_anti_master_0_readdata),      //   input,  width = 32,                                  .readdata
		.master_avalon_anti_master_0_writedata     (mm_interconnect_0_master_avalon_anti_master_0_writedata),     //  output,  width = 32,                                  .writedata
		.master_avalon_anti_master_0_readdatavalid (mm_interconnect_0_master_avalon_anti_master_0_readdatavalid), //   input,   width = 1,                                  .readdatavalid
		.master_avalon_anti_master_0_waitrequest   (mm_interconnect_0_master_avalon_anti_master_0_waitrequest),   //   input,   width = 1,                                  .waitrequest
		.elane_reset_reset_bridge_in_reset_reset   (reset_reset),                                                 //   input,   width = 1, elane_reset_reset_bridge_in_reset.reset
		.clock_in_out_clk_clk                      (clk_clk)                                                      //   input,   width = 1,                  clock_in_out_clk.clk
	);

endmodule
