// ftile_iopll_todsync_sampling.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module ftile_iopll_todsync_sampling (
		input  wire  refclk,   //  refclk.clk
		output wire  locked,   //  locked.export
		input  wire  rst,      //   reset.reset
		output wire  outclk_0  // outclk0.clk
	);

	ftile_iopll_todsync_sampling_altera_iopll_1931_k7xuzoa ftile_iopll_todsync_sampling (
		.refclk   (refclk),   //   input,  width = 1,  refclk.clk
		.locked   (locked),   //  output,  width = 1,  locked.export
		.rst      (rst),      //   input,  width = 1,   reset.reset
		.outclk_0 (outclk_0)  //  output,  width = 1, outclk0.clk
	);

endmodule
