// -----------------------------------------------------------------------------
//  Generated by Magillem, from Arteris IPD division
//  Version: 5.16.0 (20230705092541_5.16.0)
//  Date   : 2024-11-12 05:09:33
// -----------------------------------------------------------------------------
//  Verilog Register Bank
// -----------------------------------------------------------------------------
//  Component Name: Short_PRACH_Registers_L2
//  File Ref      : /nfs/site/disks/ceg_user_bkhantwa/ipxact/ip_xact_rdl/csrgen_output/_workspace_mrv_gen_py_/xmlProject/_local_copy_Vendor_Library_Short_PRACH_Registers_L2_1.0.xml
//  Protocol      : AVALON
//  Wait State    : WS1_OUTPUT
// -----------------------------------------------------------------------------

module Short_PRACH_Registers_L2(

   // short_Prach2_cfg_index.sprach2_cfg_index
   output reg [7:0] short_Prach2_cfg_index_sprach2_cfg_index,
   // short_Prach2_cfg_time_index.sprach2_cfg_time_index
   output reg [31:0] short_Prach2_cfg_time_index_sprach2_cfg_time_index,
   // n_short_prach2_slot.n_sprach2_slot
   output reg [31:0] n_short_prach2_slot_n_sprach2_slot,
   // active_short_prach2_slot.active_sprach2_slot
   output reg [31:0] active_short_prach2_slot_active_sprach2_slot,
   // short_prach2_freq_idx.sprach2_freq_idx
   output reg [31:0] short_prach2_freq_idx_sprach2_freq_idx,
   // short_prach2_gain_real.sp_gain_real_l2
   output reg [15:0] short_prach2_gain_real_sp_gain_real_l2,
   // short_prach2_gain_imag.sp_gain_imag_l2
   output reg [15:0] short_prach2_gain_imag_sp_gain_imag_l2,

   // Bus interface
   input wire clk,
   input wire reset,
   input wire [31:0] writedata,
   input wire read,
   input wire write,
   input wire [3:0] byteenable,
   output reg [31:0] readdata,
   output reg readdatavalid,
   input wire [4:0] address
);

wire reset_n = !reset;

// -----------------------------------------------------------------------------
// Protocol management
// -----------------------------------------------------------------------------

reg [31:0] rdata_comb;
always @(negedge reset_n, posedge clk)
   if (!reset_n) readdata[31:0] <= 32'h00000000; else readdata[31:0] <= rdata_comb[31:0];

// Read data is always valid the cycle after read transaction is asserted
always @(negedge reset_n, posedge clk)
   if (!reset_n) readdatavalid <= 1'b0; else readdatavalid <= read;

wire we = write;
wire re = read;
wire [4:0] addr = address[4:0];
wire [31:0] din = writedata[31:0];

// -----------------------------------------------------------------------------
// Write byte enables
// -----------------------------------------------------------------------------

// Register short_Prach2_cfg_index
wire we_short_Prach2_cfg_index = we & (addr[4:0] == 5'h00) ? byteenable[0] : 1'b0;
// Register short_Prach2_cfg_time_index
wire [3:0] we_short_Prach2_cfg_time_index = we & (addr[4:0] == 5'h04) ? byteenable[3:0] : {4{1'b0}};
// Register n_short_prach2_slot
wire [3:0] we_n_short_prach2_slot = we & (addr[4:0] == 5'h08) ? byteenable[3:0] : {4{1'b0}};
// Register active_short_prach2_slot
wire [3:0] we_active_short_prach2_slot = we & (addr[4:0] == 5'h0c) ? byteenable[3:0] : {4{1'b0}};
// Register short_prach2_freq_idx
wire [3:0] we_short_prach2_freq_idx = we & (addr[4:0] == 5'h10) ? byteenable[3:0] : {4{1'b0}};
// Register short_prach2_gain_real
wire [1:0] we_short_prach2_gain_real = we & (addr[4:0] == 5'h14) ? byteenable[1:0] : {2{1'b0}};
// Register short_prach2_gain_imag
wire [1:0] we_short_prach2_gain_imag = we & (addr[4:0] == 5'h18) ? byteenable[1:0] : {2{1'b0}};

// -----------------------------------------------------------------------------
// Read byte enables
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Register short_Prach2_cfg_index implementation
// -----------------------------------------------------------------------------

// short_Prach2_cfg_index_sprach2_cfg_index
//    bitfield description: Bit [7:0] - Prach2_cfg_index
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 8'h1b

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      short_Prach2_cfg_index_sprach2_cfg_index <= 8'h1b;
   end
   else begin
      if (we_short_Prach2_cfg_index) begin
         short_Prach2_cfg_index_sprach2_cfg_index[7:0] <= din[7:0];
      end
   end

// -----------------------------------------------------------------------------
// Register short_Prach2_cfg_time_index implementation
// -----------------------------------------------------------------------------

// short_Prach2_cfg_time_index_sprach2_cfg_time_index
//    bitfield description: Prach2_cfg_time_index
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 32'h00000000

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      short_Prach2_cfg_time_index_sprach2_cfg_time_index <= 32'h00000000;
   end
   else begin
      if (we_short_Prach2_cfg_time_index[0]) begin
         short_Prach2_cfg_time_index_sprach2_cfg_time_index[7:0] <= din[7:0];
      end
      if (we_short_Prach2_cfg_time_index[1]) begin
         short_Prach2_cfg_time_index_sprach2_cfg_time_index[15:8] <= din[15:8];
      end
      if (we_short_Prach2_cfg_time_index[2]) begin
         short_Prach2_cfg_time_index_sprach2_cfg_time_index[23:16] <= din[23:16];
      end
      if (we_short_Prach2_cfg_time_index[3]) begin
         short_Prach2_cfg_time_index_sprach2_cfg_time_index[31:24] <= din[31:24];
      end
   end

// -----------------------------------------------------------------------------
// Register n_short_prach2_slot implementation
// -----------------------------------------------------------------------------

// n_short_prach2_slot_n_sprach2_slot
//    bitfield description: n_prach2_slot
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 32'h00000000

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      n_short_prach2_slot_n_sprach2_slot <= 32'h00000000;
   end
   else begin
      if (we_n_short_prach2_slot[0]) begin
         n_short_prach2_slot_n_sprach2_slot[7:0] <= din[7:0];
      end
      if (we_n_short_prach2_slot[1]) begin
         n_short_prach2_slot_n_sprach2_slot[15:8] <= din[15:8];
      end
      if (we_n_short_prach2_slot[2]) begin
         n_short_prach2_slot_n_sprach2_slot[23:16] <= din[23:16];
      end
      if (we_n_short_prach2_slot[3]) begin
         n_short_prach2_slot_n_sprach2_slot[31:24] <= din[31:24];
      end
   end

// -----------------------------------------------------------------------------
// Register active_short_prach2_slot implementation
// -----------------------------------------------------------------------------

// active_short_prach2_slot_active_sprach2_slot
//    bitfield description: active_prach2_slot
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 32'h00000000

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      active_short_prach2_slot_active_sprach2_slot <= 32'h00000000;
   end
   else begin
      if (we_active_short_prach2_slot[0]) begin
         active_short_prach2_slot_active_sprach2_slot[7:0] <= din[7:0];
      end
      if (we_active_short_prach2_slot[1]) begin
         active_short_prach2_slot_active_sprach2_slot[15:8] <= din[15:8];
      end
      if (we_active_short_prach2_slot[2]) begin
         active_short_prach2_slot_active_sprach2_slot[23:16] <= din[23:16];
      end
      if (we_active_short_prach2_slot[3]) begin
         active_short_prach2_slot_active_sprach2_slot[31:24] <= din[31:24];
      end
   end

// -----------------------------------------------------------------------------
// Register short_prach2_freq_idx implementation
// -----------------------------------------------------------------------------

// short_prach2_freq_idx_sprach2_freq_idx
//    bitfield description: prach2_freq_idx
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 32'h00000000

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      short_prach2_freq_idx_sprach2_freq_idx <= 32'h00000000;
   end
   else begin
      if (we_short_prach2_freq_idx[0]) begin
         short_prach2_freq_idx_sprach2_freq_idx[7:0] <= din[7:0];
      end
      if (we_short_prach2_freq_idx[1]) begin
         short_prach2_freq_idx_sprach2_freq_idx[15:8] <= din[15:8];
      end
      if (we_short_prach2_freq_idx[2]) begin
         short_prach2_freq_idx_sprach2_freq_idx[23:16] <= din[23:16];
      end
      if (we_short_prach2_freq_idx[3]) begin
         short_prach2_freq_idx_sprach2_freq_idx[31:24] <= din[31:24];
      end
   end

// -----------------------------------------------------------------------------
// Register short_prach2_gain_real implementation
// -----------------------------------------------------------------------------

// short_prach2_gain_real_sp_gain_real_l2
//    bitfield description: sp_gain_real_l2
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h4000

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      short_prach2_gain_real_sp_gain_real_l2 <= 16'h4000;
   end
   else begin
      if (we_short_prach2_gain_real[0]) begin
         short_prach2_gain_real_sp_gain_real_l2[7:0] <= din[7:0];
      end
      if (we_short_prach2_gain_real[1]) begin
         short_prach2_gain_real_sp_gain_real_l2[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Register short_prach2_gain_imag implementation
// -----------------------------------------------------------------------------

// short_prach2_gain_imag_sp_gain_imag_l2
//    bitfield description: sp_gain_imag_l2
//    customType          : RW
//    hwAccess            : RO
//    reset value         : 16'h0000

always @(negedge reset_n, posedge clk)
   if (!reset_n) begin
      short_prach2_gain_imag_sp_gain_imag_l2 <= 16'h0000;
   end
   else begin
      if (we_short_prach2_gain_imag[0]) begin
         short_prach2_gain_imag_sp_gain_imag_l2[7:0] <= din[7:0];
      end
      if (we_short_prach2_gain_imag[1]) begin
         short_prach2_gain_imag_sp_gain_imag_l2[15:8] <= din[15:8];
      end
   end

// -----------------------------------------------------------------------------
// Data read management
// -----------------------------------------------------------------------------

always @(*)
begin
   rdata_comb = 32'h00000000;
   if (re) begin
      case (addr)
         // Register short_Prach2_cfg_index: short_Prach2_cfg_index_sprach2_cfg_index (RW)
         5'h00: begin
            rdata_comb[7:0] = short_Prach2_cfg_index_sprach2_cfg_index[7:0];
         end
         // Register short_Prach2_cfg_time_index: short_Prach2_cfg_time_index_sprach2_cfg_time_index (RW)
         5'h04: begin
            rdata_comb[31:0] = short_Prach2_cfg_time_index_sprach2_cfg_time_index[31:0];
         end
         // Register n_short_prach2_slot: n_short_prach2_slot_n_sprach2_slot (RW)
         5'h08: begin
            rdata_comb[31:0] = n_short_prach2_slot_n_sprach2_slot[31:0];
         end
         // Register active_short_prach2_slot: active_short_prach2_slot_active_sprach2_slot (RW)
         5'h0c: begin
            rdata_comb[31:0] = active_short_prach2_slot_active_sprach2_slot[31:0];
         end
         // Register short_prach2_freq_idx: short_prach2_freq_idx_sprach2_freq_idx (RW)
         5'h10: begin
            rdata_comb[31:0] = short_prach2_freq_idx_sprach2_freq_idx[31:0];
         end
         // Register short_prach2_gain_real: short_prach2_gain_real_sp_gain_real_l2 (RW)
         5'h14: begin
            rdata_comb[15:0] = short_prach2_gain_real_sp_gain_real_l2[15:0];
         end
         // Register short_prach2_gain_imag: short_prach2_gain_imag_sp_gain_imag_l2 (RW)
         5'h18: begin
            rdata_comb[15:0] = short_prach2_gain_imag_sp_gain_imag_l2[15:0];
         end
         default: begin
            rdata_comb = 32'h00000000;
         end
      endcase
   end
end

endmodule